/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "FBSDKErrorRecoveryAttempter.h"


@interface _FBSDKTemporaryErrorRecoveryAttempter : FBSDKErrorRecoveryAttempter {
}
-(void)attemptRecoveryFromError:(id)error optionIndex:(unsigned)index delegate:(id)delegate didRecoverSelector:(SEL)selector contextInfo:(void*)info;
@end

