/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "NSCoding.h"
#import "NSCopying.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableDictionary, NSURLCredential, NSOperationQueue, NSMutableArray, NSURL;

__attribute__((visibility("hidden")))
@interface AFHTTPClient : XXUnknownSuperclass <NSCoding, NSCopying> {
	BOOL _allowsInvalidSSLCertificate;
	NSURL* _baseURL;
	unsigned _stringEncoding;
	int _parameterEncoding;
	NSMutableArray* _registeredHTTPOperationClassNames;
	NSMutableDictionary* _defaultHeaders;
	NSURLCredential* _defaultCredential;
	NSOperationQueue* _operationQueue;
	int _defaultSSLPinningMode;
}
@property(assign, nonatomic) BOOL allowsInvalidSSLCertificate;
@property(assign, nonatomic) int defaultSSLPinningMode;
@property(assign, nonatomic) int parameterEncoding;
@property(assign, nonatomic) unsigned stringEncoding;
@property(retain, nonatomic) NSOperationQueue* operationQueue;
@property(retain, nonatomic) NSURLCredential* defaultCredential;
@property(retain, nonatomic) NSMutableDictionary* defaultHeaders;
@property(retain, nonatomic) NSMutableArray* registeredHTTPOperationClassNames;
@property(retain, nonatomic) NSURL* baseURL;
+(id)clientWithBaseURL:(id)baseURL;
-(void).cxx_destruct;
-(id)copyWithZone:(NSZone*)zone;
-(void)encodeWithCoder:(id)coder;
-(id)initWithCoder:(id)coder;
-(void)patchPath:(id)path parameters:(id)parameters success:(id)success failure:(id)failure;
-(void)deletePath:(id)path parameters:(id)parameters success:(id)success failure:(id)failure;
-(void)putPath:(id)path parameters:(id)parameters success:(id)success failure:(id)failure;
-(void)postPath:(id)path parameters:(id)parameters success:(id)success failure:(id)failure;
-(void)getPath:(id)path parameters:(id)parameters success:(id)success failure:(id)failure;
-(void)enqueueBatchOfHTTPRequestOperations:(id)httprequestOperations progressBlock:(id)block completionBlock:(id)block3;
-(void)enqueueBatchOfHTTPRequestOperationsWithRequests:(id)requests progressBlock:(id)block completionBlock:(id)block3;
-(void)cancelAllHTTPOperationsWithMethod:(id)method path:(id)path;
-(void)enqueueHTTPRequestOperation:(id)operation;
-(id)HTTPRequestOperationWithRequest:(id)request success:(id)success failure:(id)failure;
-(id)multipartFormRequestWithMethod:(id)method path:(id)path parameters:(id)parameters constructingBodyWithBlock:(id)block;
-(id)requestWithMethod:(id)method path:(id)path parameters:(id)parameters;
-(void)clearAuthorizationHeader;
-(void)setAuthorizationHeaderWithToken:(id)token;
-(void)setAuthorizationHeaderWithUsername:(id)username password:(id)password;
-(void)setDefaultHeader:(id)header value:(id)value;
-(id)defaultValueForHeader:(id)header;
-(void)unregisterHTTPOperationClass:(Class)aClass;
-(BOOL)registerHTTPOperationClass:(Class)aClass;
-(id)description;
-(void)dealloc;
-(id)initWithBaseURL:(id)baseURL;
-(id)init;
@end

