/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AFHTTPRequestOperation.h"

@class NSRecursiveLock, NSError;

__attribute__((visibility("hidden")))
@interface AFJSONRequestOperation : AFHTTPRequestOperation {
	id _responseJSON;
	unsigned _JSONReadingOptions;
	NSError* _JSONError;
}
@property(assign, nonatomic) unsigned JSONReadingOptions;
@property(retain, nonatomic) NSRecursiveLock* lock;
@property(retain, nonatomic) NSError* JSONError;
@property(retain, nonatomic) id responseJSON;
+(BOOL)canProcessRequest:(id)request;
+(id)acceptableContentTypes;
+(id)JSONRequestOperationWithRequest:(id)request success:(id)success failure:(id)failure;
-(void).cxx_destruct;
-(void)setCompletionBlockWithSuccess:(id)success failure:(id)failure;
-(id)error;
@end

