/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "HSAlertViewDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "SKStoreProductViewControllerDelegate.h"

@class NSObject, HSAlertView, NSString;
@protocol AppiraterDelegate;

__attribute__((visibility("hidden")))
@interface Appirater : XXUnknownSuperclass <HSAlertViewDelegate, SKStoreProductViewControllerDelegate> {
	HSAlertView* ratingAlert;
	NSString* localytics;
	NSObject<AppiraterDelegate>* delegate;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) NSObject<AppiraterDelegate>* delegate;
@property(retain, nonatomic) HSAlertView* ratingAlert;
+(void)closeModal;
+(void)rateApp;
+(id)topMostViewController:(id)controller;
+(id)getRootViewController;
+(void)showPrompt;
+(void)userDidSignificantEvent:(BOOL)user;
+(void)appEnteredForeground:(BOOL)foreground;
+(void)appWillResignActive;
+(void)appLaunched:(BOOL)launched;
+(void)appLaunched;
+(id)sharedInstance;
+(void)setModalOpen:(BOOL)open;
+(void)setStatusBarStyle:(int)style;
+(void)setOpenInAppStore:(BOOL)appStore;
+(void)setUsesAnimation:(BOOL)animation;
+(void)setDelegate:(id)delegate;
+(void)reset;
+(void)setForceRatingConditionsMet:(BOOL)met;
+(void)setDebug:(BOOL)debug;
+(void)setTimeBeforeReminding:(double)reminding;
+(void)setSignificantEventsUntilPrompt:(int)prompt;
+(void)setUsesUntilPrompt:(int)prompt;
+(void)setDaysUntilPrompt:(double)prompt;
+(void)setAppId:(id)anId;
-(void).cxx_destruct;
-(void)productViewControllerDidFinish:(id)productViewController;
-(void)alertView:(id)view didDismissWithButtonIndex:(int)buttonIndex;
-(void)hideRatingAlert;
-(BOOL)userHasRatedCurrentVersion;
-(BOOL)userHasDeclinedToRate;
-(void)incrementSignificantEventAndRate:(BOOL)rate;
-(void)incrementAndRate:(BOOL)rate;
-(void)incrementSignificantEventCount;
-(void)incrementUseCount;
-(BOOL)ratingConditionsHaveBeenMet;
-(void)showRatingAlert:(id)alert;
-(void)showRatingAlert;
-(BOOL)connectedToNetwork;
@end

