/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSUserDefaults;

__attribute__((visibility("hidden")))
@interface AppiraterHelper : XXUnknownSuperclass {
	NSUserDefaults* userDefaults;
	BOOL trigger;
}
+(id)sharedClient;
-(void).cxx_destruct;
-(void)foundHiddenCoinPile;
-(void)purchasedItemsFromStoreWorth:(int)storeWorth;
-(void)earnedSuperStar;
-(void)cameInTop3WorldCup;
-(void)wonChallenge;
-(void)ping;
-(void)trigger;
-(void)reset;
-(void)checkVersion;
-(id)init;
@end

