/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "TournamentButton.h"

@class CCSprite;

__attribute__((visibility("hidden")))
@interface BigTournamentButton : TournamentButton {
	CCSprite* icon;
}
+(id)tournamentButtonWithMenu:(id)menu;
-(void).cxx_destruct;
-(void)cleanup;
-(void)adjustEmptyLabel;
@end

