/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Powerup.h"
#import "PowerupProtocol.h"
#import "Boom-Structs.h"


__attribute__((visibility("hidden")))
@interface BigWheelPowerup : Powerup <PowerupProtocol> {
	b2Vec2 origin;
}
+(id)spriteWithBatchNode:(id)batchNode rect:(CGRect)rect;
+(id)spriteWithFile:(id)file rect:(CGRect)rect;
-(id).cxx_construct;
-(void)cleanup;
-(void)triggerPowerup;
-(void)postInitialization;
-(void)setBounce:(float)bounce;
-(void)setAngle:(float)angle;
-(void)BigWheelInit;
-(id)initWithBatchNode:(id)batchNode rect:(CGRect)rect;
-(id)initWithFile:(id)file rect:(CGRect)rect;
-(id)init;
@end

