/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "CCActionInterval.h"


__attribute__((visibility("hidden")))
@interface CCAccelDeccelAmplitude : CCActionInterval {
	float rate_;
	CCActionInterval* other_;
}
@property(assign, nonatomic) float rate;
+(id)actionWithAction:(id)action duration:(float)duration;
-(id)reverse;
-(void)update:(float)update;
-(void)startWithTarget:(id)target;
-(void)dealloc;
-(id)initWithAction:(id)action duration:(float)duration;
@end

