/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

__attribute__((visibility("hidden")))
@interface CCBMFontConfiguration : XXUnknownSuperclass {
	NSString* atlasName_;
	FontDefHashElement* fontDefDictionary_;
	int commonHeight_;
	BMFontPadding padding_;
	KerningHashElement* kerningDictionary_;
}
@property(retain, nonatomic) NSString* atlasName;
+(id)configurationWithFNTFile:(id)fntfile;
-(void)parseKerningEntry:(id)entry;
-(void)parseCharacterDefinition:(id)definition charDef:(BMFontDef*)def;
-(void)parseCommonArguments:(id)arguments;
-(void)parseInfoArguments:(id)arguments;
-(void)parseImageFileName:(id)name fntFile:(id)file;
-(BOOL)parseConfigFile:(id)file;
-(void)purgeKerningDictionary;
-(void)purgeFontDefDictionary;
-(id)description;
-(void)dealloc;
-(id)initWithFNTfile:(id)fntfile;
@end

