/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "CCCardinalSplineBy.h"


__attribute__((visibility("hidden")))
@interface CCCatmullRomBy : CCCardinalSplineBy {
}
+(id)actionWithDuration:(float)duration points:(id)points;
-(id)initWithDuration:(float)duration points:(id)points;
@end

