/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "NSCopying.h"
#import "CCActionInstant.h"


__attribute__((visibility("hidden")))
@interface CCCallBlockN : CCActionInstant <NSCopying> {
	id block_;
}
+(id)actionWithBlock:(id)block;
-(void)dealloc;
-(void)execute;
-(void)update:(float)update;
-(id)copyWithZone:(NSZone*)zone;
-(id)initWithBlock:(id)block;
@end

