/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "CCActionEase.h"
#import "NSCopying.h"


__attribute__((visibility("hidden")))
@interface CCEaseSineOut : CCActionEase <NSCopying> {
}
-(id)reverse;
-(void)update:(float)update;
@end

