/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "NSObject.h"


@protocol CCESRenderer <NSObject>
-(unsigned)msaaColorBuffer;
-(unsigned)msaaFrameBuffer;
-(unsigned)defaultFrameBuffer;
-(unsigned)colorRenderBuffer;
-(CGSize)backingSize;
-(id)context;
-(BOOL)resizeFromLayer:(id)layer;
-(id)initWithDepthFormat:(unsigned)depthFormat withPixelFormat:(unsigned)pixelFormat withSharegroup:(id)sharegroup withMultiSampling:(BOOL)multiSampling withNumberOfSamples:(unsigned)samples;
@end

