/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "NSCopying.h"
#import "CCActionInterval.h"


__attribute__((visibility("hidden")))
@interface CCFadeTo : CCActionInterval <NSCopying> {
	unsigned char toOpacity_;
	unsigned char fromOpacity_;
}
+(id)actionWithDuration:(float)duration opacity:(unsigned char)opacity;
-(void)update:(float)update;
-(void)startWithTarget:(id)target;
-(id)copyWithZone:(NSZone*)zone;
-(id)initWithDuration:(float)duration opacity:(unsigned char)opacity;
@end

