/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "CCAction.h"
#import "Boom-Structs.h"
#import "NSCopying.h"

@class CCNode;

__attribute__((visibility("hidden")))
@interface CCFollow : CCAction <NSCopying> {
	CCNode* followedNode_;
	BOOL boundarySet;
	BOOL boundaryFullyCovered;
	CGPoint halfScreenSize;
	CGPoint fullScreenSize;
	float leftBoundary;
	float rightBoundary;
	float topBoundary;
	float bottomBoundary;
}
@property(assign, nonatomic) BOOL boundarySet;
+(id)actionWithTarget:(id)target worldBoundary:(CGRect)boundary;
+(id)actionWithTarget:(id)target;
-(void)dealloc;
-(void)stop;
-(BOOL)isDone;
-(void)step:(float)step;
-(id)copyWithZone:(NSZone*)zone;
-(id)initWithTarget:(id)target worldBoundary:(CGRect)boundary;
-(id)initWithTarget:(id)target;
@end

