/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "CCGridAction.h"


__attribute__((visibility("hidden")))
@interface CCGrid3DAction : CCGridAction {
}
-(void)setVertex:(ccGridSize)vertex vertex:(ccVertex3F)vertex2;
-(ccVertex3F)originalVertex:(ccGridSize)vertex;
-(ccVertex3F)vertex:(ccGridSize)vertex;
-(id)grid;
@end

