/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "CCGridBase.h"


__attribute__((visibility("hidden")))
@interface CCGrid3D : CCGridBase {
	void* texCoordinates;
	void* vertices;
	void* originalVertices;
	unsigned short* indices;
}
-(void)reuse;
-(void)setVertex:(ccGridSize)vertex vertex:(ccVertex3F)vertex2;
-(ccVertex3F)originalVertex:(ccGridSize)vertex;
-(ccVertex3F)vertex:(ccGridSize)vertex;
-(void)calculateVertexPoints;
-(void)blit;
-(void)dealloc;
@end

