/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "CCRGBAProtocol.h"
#import "Boom-Structs.h"
#import "CCMenuItem.h"

@class NSString;
@protocol CCLabelProtocol;

__attribute__((visibility("hidden")))
@interface CCMenuItemLabel : CCMenuItem <CCRGBAProtocol> {
	CCNode<CCRGBAProtocol, CCLabelProtocol>* label_;
	ccColor3B colorBackup;
	ccColor3B disabledColor_;
	float originalScale_;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) CCNode<CCRGBAProtocol, CCLabelProtocol>* label;
@property(assign, nonatomic) ccColor3B disabledColor;
+(id)itemWithLabel:(id)label block:(id)block;
+(id)itemWithLabel:(id)label target:(id)target selector:(SEL)selector;
+(id)itemWithLabel:(id)label;
-(ccColor3B)color;
-(void)setColor:(ccColor3B)color;
-(unsigned char)opacity;
-(void)setOpacity:(unsigned char)opacity;
-(void)setIsEnabled:(BOOL)enabled;
-(void)unselected;
-(void)selected;
-(void)activate;
-(void)setString:(id)string;
-(id)initWithLabel:(id)label block:(id)block;
-(id)initWithLabel:(id)label target:(id)target selector:(SEL)selector;
@end

