/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "CCMenuItemLabel.h"


__attribute__((visibility("hidden")))
@interface CCMenuItemAtlasFont : CCMenuItemLabel {
}
+(id)itemWithString:(id)string charMapFile:(id)file itemWidth:(int)width itemHeight:(int)height startCharMap:(BOOL)map block:(id)block;
+(id)itemWithString:(id)string charMapFile:(id)file itemWidth:(int)width itemHeight:(int)height startCharMap:(BOOL)map target:(id)target selector:(SEL)selector;
+(id)itemWithString:(id)string charMapFile:(id)file itemWidth:(int)width itemHeight:(int)height startCharMap:(BOOL)map;
+(id)itemFromString:(id)string charMapFile:(id)file itemWidth:(int)width itemHeight:(int)height startCharMap:(BOOL)map block:(id)block;
+(id)itemFromString:(id)string charMapFile:(id)file itemWidth:(int)width itemHeight:(int)height startCharMap:(BOOL)map target:(id)target selector:(SEL)selector;
+(id)itemFromString:(id)string charMapFile:(id)file itemWidth:(int)width itemHeight:(int)height startCharMap:(BOOL)map;
-(void)dealloc;
-(id)initWithString:(id)string charMapFile:(id)file itemWidth:(int)width itemHeight:(int)height startCharMap:(BOOL)map block:(id)block;
-(id)initWithString:(id)string charMapFile:(id)file itemWidth:(int)width itemHeight:(int)height startCharMap:(BOOL)map target:(id)target selector:(SEL)selector;
-(id)initFromString:(id)string charMapFile:(id)file itemWidth:(int)width itemHeight:(int)height startCharMap:(BOOL)map block:(id)block;
-(id)initFromString:(id)string charMapFile:(id)file itemWidth:(int)width itemHeight:(int)height startCharMap:(BOOL)map target:(id)target selector:(SEL)selector;
@end

