/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "CCNode.h"


__attribute__((visibility("hidden")))
@interface CCMenuItem : CCNode {
	id block_;
	BOOL isEnabled_;
	BOOL isSelected_;
}
@property(readonly, assign, nonatomic) BOOL isSelected;
+(id)itemWithBlock:(id)block;
+(id)itemWithTarget:(id)target selector:(SEL)selector;
-(void)setTarget:(id)target selector:(SEL)selector;
-(void)setBlock:(id)block;
-(CGRect)rect;
-(BOOL)isEnabled;
-(void)setIsEnabled:(BOOL)enabled;
-(void)activate;
-(void)unselected;
-(void)selected;
-(void)cleanup;
-(void)dealloc;
-(id)initWithBlock:(id)block;
-(id)initWithTarget:(id)target selector:(SEL)selector;
-(id)init;
@end

