/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "CCNode.h"


__attribute__((visibility("hidden")))
@interface CCParallaxNode : CCNode {
	ccArray* parallaxArray_;
	CGPoint lastPosition;
}
@property(assign, nonatomic) ccArray* parallaxArray;
-(void)visit;
-(CGPoint)absolutePosition_;
-(void)removeAllChildrenWithCleanup:(BOOL)cleanup;
-(void)removeChild:(id)child cleanup:(BOOL)cleanup;
-(void)addChild:(id)child z:(int)z parallaxRatio:(CGPoint)ratio positionOffset:(CGPoint)offset;
-(void)addChild:(id)child z:(int)z tag:(int)tag;
-(void)dealloc;
-(id)init;
@end

