/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "CCParticleSystemQuad.h"


__attribute__((visibility("hidden")))
@interface CCParticleSpiral : CCParticleSystemQuad {
}
-(id)initWithTotalParticles:(unsigned)totalParticles;
-(id)init;
@end

