/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "NSCopying.h"
#import "CCActionInstant.h"


__attribute__((visibility("hidden")))
@interface CCPlace : CCActionInstant <NSCopying> {
	CGPoint position;
}
+(id)actionWithPosition:(CGPoint)position;
-(void)update:(float)update;
-(id)copyWithZone:(NSZone*)zone;
-(id)initWithPosition:(CGPoint)position;
@end

