/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "NSCopying.h"
#import "CCActionInterval.h"


__attribute__((visibility("hidden")))
@interface CCProgressFromTo : CCActionInterval <NSCopying> {
	float to_;
	float from_;
}
+(id)actionWithDuration:(float)duration from:(float)from to:(float)to;
-(void)update:(float)update;
-(void)startWithTarget:(id)target;
-(id)reverse;
-(id)copyWithZone:(NSZone*)zone;
-(id)initWithDuration:(float)duration from:(float)from to:(float)to;
@end

