/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "NSCopying.h"
#import "CCActionInterval.h"


__attribute__((visibility("hidden")))
@interface CCScaleTo : CCActionInterval <NSCopying> {
	float scaleX_;
	float scaleY_;
	float startScaleX_;
	float startScaleY_;
	float endScaleX_;
	float endScaleY_;
	float deltaX_;
	float deltaY_;
}
+(id)actionWithDuration:(float)duration scaleX:(float)x scaleY:(float)y;
+(id)actionWithDuration:(float)duration scale:(float)scale;
-(void)update:(float)update;
-(void)startWithTarget:(id)target;
-(id)copyWithZone:(NSZone*)zone;
-(id)initWithDuration:(float)duration scaleX:(float)x scaleY:(float)y;
-(id)initWithDuration:(float)duration scale:(float)scale;
@end

