/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "NSCopying.h"
#import "CCActionInterval.h"


__attribute__((visibility("hidden")))
@interface CCSkewTo : CCActionInterval <NSCopying> {
	float skewX_;
	float skewY_;
	float startSkewX_;
	float startSkewY_;
	float endSkewX_;
	float endSkewY_;
	float deltaX_;
	float deltaY_;
}
+(id)actionWithDuration:(float)duration skewX:(float)x skewY:(float)y;
-(void)update:(float)update;
-(void)startWithTarget:(id)target;
-(id)copyWithZone:(NSZone*)zone;
-(id)initWithDuration:(float)duration skewX:(float)x skewY:(float)y;
@end

