/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "CCLayer.h"

@class CCSprite, CCMenuItem;

__attribute__((visibility("hidden")))
@interface CCSlider : CCLayer {
	float value;
	float minX;
	float maxX;
	CCMenuItem* _thumb;
	CCSprite* _bg;
}
@property(assign, nonatomic) float value;
+(id)sliderWithBackgroundSprite:(id)backgroundSprite thumbMenuItem:(id)item;
+(id)sliderWithBackgroundFile:(id)backgroundFile thumbFile:(id)file;
-(void)ccTouchEnded:(id)ended withEvent:(id)event;
-(void)ccTouchMoved:(id)moved withEvent:(id)event;
-(BOOL)ccTouchBegan:(id)began withEvent:(id)event;
-(CGPoint)locationFromTouch:(id)touch;
-(void)registerWithTouchDispatcher;
-(BOOL)isTouchForMe:(CGPoint)me;
-(int)mouseDelegatePriority;
-(id)initWithBackgroundSprite:(id)backgroundSprite thumbMenuItem:(id)item;
-(id)initWithBackgroundFile:(id)backgroundFile thumbFile:(id)file;
@end

