/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "NSCopying.h"
#import "CCActionInterval.h"


__attribute__((visibility("hidden")))
@interface CCSpawn : CCActionInterval <NSCopying> {
	CCFiniteTimeAction* one_;
	CCFiniteTimeAction* two_;
}
+(id)actionOne:(id)one two:(id)two;
+(id)actionWithArray:(id)array;
+(id)actions:(id)actions;
+(id)actionsWithArray:(id)array;
-(id)reverse;
-(void)update:(float)update;
-(void)stop;
-(void)startWithTarget:(id)target;
-(void)dealloc;
-(id)copyWithZone:(NSZone*)zone;
-(id)initOne:(id)one two:(id)two;
@end

