/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "NSCopying.h"
#import "CCActionInterval.h"


__attribute__((visibility("hidden")))
@interface CCTargetedAction : CCActionInterval <NSCopying> {
	id forcedTarget_;
	CCFiniteTimeAction* action_;
}
@property(retain, nonatomic) id forcedTarget;
+(id)actionWithTarget:(id)target action:(id)action;
-(void)update:(float)update;
-(void)stop;
-(void)startWithTarget:(id)target;
-(void)dealloc;
-(id)copyWithZone:(NSZone*)zone;
-(id)initWithTarget:(id)target action:(id)action;
@end

