/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "CCGridAction.h"
#import "Boom-Structs.h"


__attribute__((visibility("hidden")))
@interface CCTiledGrid3DAction : CCGridAction {
}
-(void)setTile:(ccGridSize)tile coords:(ccQuad3)coords;
-(ccQuad3)originalTile:(ccGridSize)tile;
-(ccQuad3)tile:(ccGridSize)tile;
-(id)grid;
@end

