/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

__attribute__((visibility("hidden")))
@interface CCTMXTilesetInfo : XXUnknownSuperclass {
	NSString* name_;
	unsigned firstGid_;
	CGSize tileSize_;
	unsigned spacing_;
	unsigned margin_;
	NSString* sourceImage_;
	CGSize imageSize_;
}
@property(assign, nonatomic) CGSize imageSize;
@property(retain, nonatomic) NSString* sourceImage;
@property(assign, nonatomic) unsigned margin;
@property(assign, nonatomic) unsigned spacing;
@property(assign, nonatomic) CGSize tileSize;
@property(assign, nonatomic) unsigned firstGid;
@property(retain, nonatomic) NSString* name;
-(CGRect)rectForGID:(unsigned)gid;
-(void)dealloc;
@end

