/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "CCTransitionScene.h"
#import "Boom-Structs.h"


__attribute__((visibility("hidden")))
@interface CCTransitionJumpZoom : CCTransitionScene {
}
-(void)onEnter;
@end

