/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "CCTransitionScene.h"
#import "CCTransitionEaseScene.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface CCTransitionFadeTR : CCTransitionScene <CCTransitionEaseScene> {
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
-(id)easeActionWithAction:(id)action;
-(id)actionWithSize:(ccGridSize)size;
-(void)onEnter;
-(void)sceneOrder;
@end

