/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "CCTransitionScene.h"
#import "Boom-Structs.h"


__attribute__((visibility("hidden")))
@interface CCTransitionProgress : CCTransitionScene {
	float to_;
	float from_;
	CCScene* sceneToBeModified_;
}
-(id)progressTimerNodeWithRenderTexture:(id)renderTexture;
-(void)setupTransition;
-(void)sceneOrder;
-(void)onExit;
-(void)onEnter;
@end

