/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

__attribute__((visibility("hidden")))
@interface CDBufferLoadRequest : XXUnknownSuperclass {
	NSString* filePath;
	int soundId;
}
@property(readonly, assign) int soundId;
@property(readonly, assign) NSString* filePath;
-(void)dealloc;
-(id)init:(int)init filePath:(id)path;
@end

