/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface CDFloatInterpolator : XXUnknownSuperclass {
	float start;
	float end;
	float lastValue;
	int interpolationType;
}
@property(assign, nonatomic) int interpolationType;
@property(assign, nonatomic) float end;
@property(assign, nonatomic) float start;
-(id)init:(int)init startVal:(float)val endVal:(float)val3;
-(float)interpolate:(float)interpolate;
@end

