/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "CDPropertyModifier.h"


__attribute__((visibility("hidden")))
@interface CDSoundSourceFader : CDPropertyModifier {
}
-(Class)_allowableType;
-(void)_stopTarget;
-(float)_getTargetProperty;
-(void)_setTargetProperty:(float)property;
@end

