/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "CDAudioInterruptProtocol.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSObject, NSString;

__attribute__((visibility("hidden")))
@interface CDSoundEngine : XXUnknownSuperclass <CDAudioInterruptProtocol> {
	bufferInfo* _buffers;
	sourceInfo* _sources;
	sourceGroup* _sourceGroups;
	ALCcontext_structRef context;
	unsigned _sourceGroupTotal;
	unsigned long _audioSessionCategory;
	BOOL _handleAudioSession;
	float _preMuteGain;
	NSObject* _mutexBufferLoad;
	BOOL mute_;
	BOOL enabled_;
	int lastErrorCode_;
	BOOL functioning_;
	float asynchLoadProgress_;
	BOOL getGainWorks_;
	int sourceTotal_;
	int bufferTotal;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(readonly, assign) unsigned sourceGroupTotal;
@property(readonly, assign) int sourceTotal;
@property(readonly, assign) BOOL getGainWorks;
@property(assign) float asynchLoadProgress;
@property(readonly, assign) BOOL functioning;
@property(readonly, assign) int lastErrorCode;
@property(assign, nonatomic) float masterGain;
+(void)setMixerSampleRate:(float)rate;
-(void)_dumpSourceGroupsInfo;
-(ALCcontext_structRef)openALContext;
-(BOOL)sourceGroupEnabled:(int)enabled;
-(void)setSourceGroupEnabled:(int)enabled enabled:(BOOL)enabled2;
-(void)setSourceGroupNonInterruptible:(int)interruptible isNonInterruptible:(BOOL)interruptible2;
-(void)stopAllSounds;
-(void)stopSound:(unsigned)sound;
-(void)stopSourceGroup:(int)group;
-(void)_soundSourcePreRelease:(id)release;
-(id)soundSourceForSound:(int)sound sourceGroupId:(int)anId;
-(BOOL)_soundSourceAttachToBuffer:(id)buffer soundId:(int)anId;
-(unsigned)playSound:(int)sound sourceGroupId:(int)anId pitch:(float)pitch pan:(float)pan gain:(float)gain loop:(BOOL)loop;
-(int)_getSourceIndexForSourceGroup:(int)sourceGroup;
-(void)_lockSource:(int)source lock:(BOOL)lock;
-(void)setEnabled:(BOOL)enabled;
-(BOOL)enabled;
-(void)setMute:(BOOL)mute;
-(BOOL)mute;
-(int)bufferFrequencyInHertz:(int)hertz;
-(int)bufferSizeInBytes:(int)bytes;
-(float)bufferDurationInSeconds:(int)seconds;
-(BOOL)validateBufferId:(int)anId;
-(BOOL)loadBuffer:(int)buffer filePath:(id)path;
-(BOOL)loadBufferFromData:(int)data soundData:(void*)data2 format:(int)format size:(int)size freq:(int)freq;
-(BOOL)_resizeBuffers:(int)buffers;
-(void)loadBuffersAsynchronously:(id)asynchronously;
-(BOOL)unloadBuffer:(int)buffer;
-(id)init;
-(void)defineSourceGroups:(id)groups;
-(void)defineSourceGroups:(int*)groups total:(unsigned)total;
-(BOOL)_setUpSourceGroups:(int*)groups total:(unsigned)total;
-(BOOL)_redefineSourceGroups:(int*)groups total:(unsigned)total;
-(void)_freeSourceGroups;
-(void)dealloc;
-(BOOL)_initOpenAL;
-(void)_generateBuffers:(int)buffers endIndex:(int)index;
-(void)_generateSources;
-(void)_testGetGain;
@end

