/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class CCNode;

__attribute__((visibility("hidden")))
@interface CGPointObject : XXUnknownSuperclass {
	CGPoint ratio_;
	CGPoint offset_;
	CCNode* child_;
}
@property(assign, nonatomic) CCNode* child;
@property(assign, nonatomic) CGPoint offset;
@property(assign, nonatomic) CGPoint ratio;
+(id)pointWithCGPoint:(CGPoint)cgpoint offset:(CGPoint)offset;
-(id)initWithCGPoint:(CGPoint)cgpoint offset:(CGPoint)offset;
@end

