/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "HSMenuLayer.h"

@class CCMenu;

__attribute__((visibility("hidden")))
@interface ChallengeConfirmDelete : HSMenuLayer {
	CCMenu* menuItems;
	id cancelBlock;
	id deleteBlock;
}
+(id)layerWithMenu:(id)menu message:(id)message cancelBlock:(id)block acceptBlock:(id)block4;
-(void).cxx_destruct;
-(void)deleteGame;
-(void)cancel;
-(void)cleanup;
-(id)initWithMenu:(id)menu message:(id)message cancelBlock:(id)block deleteBlock:(id)block4;
-(id)initWithMenu:(id)menu;
@end

