/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "FBSDKSharingDelegate.h"

@class NSMutableArray, NSDate, NSUserDefaults, NSString;

__attribute__((visibility("hidden")))
@interface ChallengeInitiator : XXUnknownSuperclass <FBSDKSharingDelegate> {
	NSUserDefaults* userDefaults;
	NSString* sessionID;
	NSDate* sessionPing;
	unsigned sessionCounter;
	NSMutableArray* challengeWithFacebookIDs;
	BOOL justAwoke;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
+(id)sharedClient;
-(void).cxx_destruct;
-(void)sharerDidCancel:(id)sharer;
-(void)sharer:(id)sharer didFailWithError:(id)error;
-(void)sharer:(id)sharer didCompleteWithResults:(id)results;
-(void)inviteFacebookFriends;
-(void)facebookChallengeCountdown;
-(void)handleScheduledContinuesRandomChallenge;
-(void)cancelContinuesRandomChallengeNotification;
-(BOOL)scheduleContinuesRandomChallenge;
-(void)cancelInitialRandomChallengeNotification;
-(void)scheduleInitialRandomChallengeNotification;
-(BOOL)shouldAutoSendRandomChallenge:(id)challenge;
-(void)sentRandomChallenge:(BOOL)challenge;
-(void)sentRandomChallenge;
-(int)sentRandomChallengesCounter;
-(BOOL)hasSentRandomChallenge;
-(void)playedChallenge;
-(BOOL)hasPlayedChallenge;
-(void)handleDidEnterBackground;
-(void)handleDidBecomeActive;
-(void)save;
-(void)sessionPing;
-(void)reset;
-(id)init;
@end

