/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "HSMenuItem.h"
#import "ChallengeClientSyncDelegate.h"

@class HSBadgeIndicator;

__attribute__((visibility("hidden")))
@interface ChallengeButton : HSMenuItem <ChallengeClientSyncDelegate> {
	BOOL badgeDisabled;
	HSBadgeIndicator* newChallengesBadge;
	float lastChallengeLaunchQueueTimer;
}
+(id)challengeButtonWithMenu:(id)menu disableBadge:(BOOL)badge finalBlock:(id)block;
+(id)challengeButtonWithMenu:(id)menu disableBadge:(BOOL)badge block:(id)block;
+(id)challengeButtonWithMenu:(id)menu block:(id)block;
+(id)challengeButtonWithMenu:(id)menu;
-(void).cxx_destruct;
-(void)syncEnded:(BOOL)ended;
-(void)syncStarted;
-(void)cleanup;
-(void)onEnter;
-(void)update:(float)update;
-(void)enabledChallengesSynchronization;
-(void)updateChallengesBadge;
-(void)setup;
@end

