/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "HSMenuItem.h"

@class HSLabelTTF, HSAdjustedSprite, HSFacebookUser;

__attribute__((visibility("hidden")))
@interface CheckButton : HSMenuItem {
	HSFacebookUser* user;
	HSAdjustedSprite* check;
	HSAdjustedSprite* avatar;
	HSLabelTTF* labelNode;
}
@property(retain, nonatomic) HSFacebookUser* user;
@property(retain, nonatomic) HSLabelTTF* labelNode;
@property(retain, nonatomic) HSAdjustedSprite* avatar;
@property(retain, nonatomic) HSAdjustedSprite* check;
+(id)itemWithUser:(id)user name:(id)name avatar:(BOOL)avatar block:(id)block;
-(void).cxx_destruct;
-(BOOL)isChecked;
-(void)unCheck;
-(void)check;
-(void)setup:(id)setup name:(id)name avatar:(BOOL)avatar;
-(void)updateAvatar:(id)avatar user:(id)user;
-(void)cleanup;
@end

