/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "HSOpacityNode.h"
#import "Boom-Structs.h"


__attribute__((visibility("hidden")))
@interface CoinRain : HSOpacityNode {
}
-(void)update:(float)update;
-(void)addCoins;
-(id)init;
@end

