/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "HSMenuItem.h"


__attribute__((visibility("hidden")))
@interface FatTextButton : HSMenuItem {
}
+(id)orangeFatTextButtonWithLockAndBlock:(id)lockAndBlock;
+(id)orangeFatTextButtonWithLabel:(id)label block:(id)block;
+(id)greenFatTextButtonWithBigLabel:(id)bigLabel block:(id)block;
+(id)greenFatTextButtonWithLabel:(id)label block:(id)block;
@end

