/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "FBSDKWebDialogDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class FBSDKWebDialog, FBSDKGameRequestContent, NSString;
@protocol FBSDKGameRequestDialogDelegate;

@interface FBSDKGameRequestDialog : XXUnknownSuperclass <FBSDKWebDialogDelegate> {
	BOOL _dialogIsFrictionless;
	FBSDKWebDialog* _webDialog;
	BOOL _frictionlessRequestsEnabled;
	id<FBSDKGameRequestDialogDelegate> _delegate;
	FBSDKGameRequestContent* _content;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) BOOL frictionlessRequestsEnabled;
@property(copy, nonatomic) FBSDKGameRequestContent* content;
@property(assign, nonatomic) __weak id<FBSDKGameRequestDialogDelegate> delegate;
+(id)showWithContent:(id)content delegate:(id)delegate;
+(void)initialize;
-(void).cxx_destruct;
-(id)_filtersNameForFilters:(unsigned)filters;
-(id)_actionTypeNameForActionType:(unsigned)actionType;
-(void)_handleCompletionWithDialogResults:(id)dialogResults error:(id)error;
-(void)_cleanUp;
-(void)webDialogDidCancel:(id)webDialog;
-(void)webDialog:(id)dialog didFailWithError:(id)error;
-(void)webDialog:(id)dialog didCompleteWithResults:(id)results;
-(BOOL)validateWithError:(id*)error;
-(BOOL)show;
-(BOOL)canShow;
-(void)dealloc;
-(id)init;
@end

