/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UIColor;

@interface FBSDKIcon : XXUnknownSuperclass {
	UIColor* _color;
}
@property(readonly, assign, nonatomic) UIColor* color;
-(void).cxx_destruct;
-(CGPathRef)pathWithSize:(CGSize)size;
-(id)imageWithSize:(CGSize)size;
-(id)init;
-(id)initWithColor:(id)color;
@end

