/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"

@protocol FBSDKSharingContent, FBSDKSharingDelegate;

@protocol FBSDKSharing <NSObject>
@property(assign, nonatomic) BOOL shouldFailOnDataError;
@property(copy, nonatomic) id<FBSDKSharingContent> shareContent;
@property(assign, nonatomic) __weak id<FBSDKSharingDelegate> delegate;
-(BOOL)validateWithError:(id*)error;
@end

