/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "FBSDKCopying.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSDictionary, NSString;
@protocol FBSDKBridgeAPIProtocol;

@interface FBSDKBridgeAPIRequest : XXUnknownSuperclass <FBSDKCopying> {
	NSString* _actionID;
	NSString* _methodName;
	NSString* _methodVersion;
	NSDictionary* _parameters;
	unsigned _protocolType;
	NSString* _scheme;
	NSDictionary* _userInfo;
	id<FBSDKBridgeAPIProtocol> _protocol;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(readonly, assign, nonatomic) id<FBSDKBridgeAPIProtocol> protocol;
@property(readonly, copy, nonatomic) NSDictionary* userInfo;
@property(readonly, copy, nonatomic) NSString* scheme;
@property(readonly, assign, nonatomic) unsigned protocolType;
@property(readonly, copy, nonatomic) NSDictionary* parameters;
@property(readonly, copy, nonatomic) NSString* methodVersion;
@property(readonly, copy, nonatomic) NSString* methodName;
@property(readonly, copy, nonatomic) NSString* actionID;
+(id)_protocolForType:(unsigned)type scheme:(id)scheme;
+(id)protocolMap;
+(id)bridgeAPIRequestWithProtocolType:(unsigned)protocolType scheme:(id)scheme methodName:(id)name methodVersion:(id)version parameters:(id)parameters userInfo:(id)info;
-(void).cxx_destruct;
-(id)copyWithZone:(NSZone*)zone;
-(id)requestURL:(id*)url;
-(id)init;
-(id)initWithProtocol:(id)protocol protocolType:(unsigned)type scheme:(id)scheme methodName:(id)name methodVersion:(id)version parameters:(id)parameters userInfo:(id)info;
@end

