/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol FBSDKWebDialogViewDelegate <NSObject>
-(void)webDialogViewDidFinishLoad:(id)webDialogView;
-(void)webDialogViewDidCancel:(id)webDialogView;
-(void)webDialogView:(id)view didFailWithError:(id)error;
-(void)webDialogView:(id)view didCompleteWithResults:(id)results;
@end

