/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UILabel, FBSDKLikeBoxBorderView, NSString;

@interface FBSDKLikeBoxView : XXUnknownSuperclass {
	FBSDKLikeBoxBorderView* _borderView;
	UILabel* _likeCountLabel;
	unsigned _caretPosition;
}
@property(copy, nonatomic) NSString* text;
@property(assign, nonatomic) unsigned caretPosition;
-(void).cxx_destruct;
-(void)_initializeContent;
-(CGSize)sizeThatFits:(CGSize)fits;
-(void)layoutSubviews;
-(CGSize)intrinsicContentSize;
-(id)initWithCoder:(id)coder;
-(id)initWithFrame:(CGRect)frame;
@end

