/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol FBSDKBridgeAPIProtocol <NSObject>
-(id)responseParametersForActionID:(id)actionID queryParameters:(id)parameters cancelled:(BOOL*)cancelled error:(id*)error;
-(id)requestURLWithActionID:(id)actionID scheme:(id)scheme methodName:(id)name methodVersion:(id)version parameters:(id)parameters error:(id*)error;
@end

