/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


@interface FBSDKMath : XXUnknownSuperclass {
}
+(unsigned)hashWithPointer:(const void*)pointer;
+(unsigned)hashWithLong:(unsigned long long)aLong;
+(unsigned)hashWithIntegerArray:(unsigned*)integerArray count:(unsigned)count;
+(unsigned)hashWithInteger:(unsigned)integer andInteger:(unsigned)integer2;
+(unsigned)hashWithInteger:(unsigned)integer;
+(unsigned)hashWithFloat:(float)aFloat;
+(unsigned)hashWithDouble:(double)aDouble;
+(unsigned)hashWithCString:(const char*)cstring;
+(unsigned)hashWithCGFloat:(float)cgfloat;
+(CGSize)floorForSize:(CGSize)size;
+(CGPoint)floorForPoint:(CGPoint)point;
+(CGSize)ceilForSize:(CGSize)size;
+(CGPoint)ceilForPoint:(CGPoint)point;
-(id)init;
@end

