/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface FBSDKAppEventsUtility : XXUnknownSuperclass {
}
+(long)unixTimeNow;
+(id)tokenStringToUseFor:(id)aFor;
+(id)retrievePersistedAnonymousID;
+(id)persistenceFilePath:(id)path;
+(void)persistAnonymousID:(id)anId;
+(BOOL)validateIdentifier:(id)identifier;
+(BOOL)regexValidateIdentifier:(id)identifier;
+(void)logAndNotify:(id)notify allowLogAsDeveloperError:(BOOL)error;
+(void)logAndNotify:(id)notify;
+(id)flushReasonToString:(unsigned)string;
+(void)ensureOnMainThread;
+(void)clearLibraryFiles;
+(id)attributionID;
+(id)anonymousID;
+(unsigned)advertisingTrackingStatus;
+(id)advertiserID;
+(id)activityParametersDictionaryForEvent:(id)event implicitEventsOnly:(BOOL)only shouldAccessAdvertisingID:(BOOL)anId;
-(id)init;
@end

