/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "NSSecureCoding.h"
#import "NSCopying.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableDictionary;

@interface FBSDKErrorConfiguration : XXUnknownSuperclass <NSSecureCoding, NSCopying> {
	NSMutableDictionary* _configurationDictionary;
}
+(BOOL)supportsSecureCoding;
-(void).cxx_destruct;
-(id)copyWithZone:(NSZone*)zone;
-(void)encodeWithCoder:(id)coder;
-(id)initWithCoder:(id)coder;
-(void)parseArray:(id)array;
-(id)recoveryConfigurationForCode:(id)code subcode:(id)subcode request:(id)request;
-(id)initWithDictionary:(id)dictionary;
-(id)init;
@end

