/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "FBSDKSharingContent.h"
#import "Boom-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSURL, NSArray, FBSDKShareVideo, NSString, FBSDKSharePhoto;

@interface FBSDKShareVideoContent : XXUnknownSuperclass <FBSDKSharingContent> {
	NSURL* _contentURL;
	NSArray* _peopleIDs;
	NSString* _placeID;
	NSString* _ref;
	FBSDKSharePhoto* _previewPhoto;
	FBSDKShareVideo* _video;
}
@property(copy, nonatomic) NSString* ref;
@property(copy, nonatomic) NSString* placeID;
@property(copy, nonatomic) NSArray* peopleIDs;
@property(copy, nonatomic) NSURL* contentURL;
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(copy, nonatomic) FBSDKShareVideo* video;
@property(copy, nonatomic) FBSDKSharePhoto* previewPhoto;
+(BOOL)supportsSecureCoding;
-(void).cxx_destruct;
-(id)copyWithZone:(NSZone*)zone;
-(void)encodeWithCoder:(id)coder;
-(id)initWithCoder:(id)coder;
-(BOOL)isEqualToShareVideoContent:(id)shareVideoContent;
-(BOOL)isEqual:(id)equal;
@end

