/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface FBSDKAppEventsDeviceInfo : XXUnknownSuperclass {
}
+(id)_getCarrier;
+(unsigned)_readSysCtlUInt:(int)int type:(int)type;
+(unsigned)_coreCount;
+(id)_getRemainingDiskSpace;
+(id)_getTotalDiskSpace;
+(void)initialize;
+(void)extendDictionaryWithDeviceInfo:(id)deviceInfo;
-(id)_generateEncoding;
-(void)_collectGroup1Data;
-(BOOL)_isGroup1Expired;
-(void)_collectPersistentData;
-(void)setEncodedDeviceInfo:(id)info;
-(id)encodedDeviceInfo;
@end

