/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableSet, NSString;

@interface FBSDKViewImpressionTracker : XXUnknownSuperclass {
	NSMutableSet* _trackedImpressions;
	NSString* _eventName;
}
@property(readonly, copy, nonatomic) NSString* eventName;
+(id)impressionTrackerWithEventName:(id)eventName;
-(void).cxx_destruct;
-(void)_applicationDidEnterBackgroundNotification:(id)_application;
-(void)logImpressionWithIdentifier:(id)identifier parameters:(id)parameters;
-(void)dealloc;
-(id)initWithEventName:(id)eventName;
@end

