/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SingleFileDownloaderDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSArray, NSMutableArray, NSString;
@protocol FilesDownloaderDelegate;

__attribute__((visibility("hidden")))
@interface FilesDownloader : XXUnknownSuperclass <SingleFileDownloaderDelegate> {
	NSArray* _filenames;
	NSString* _sourcePath;
	NSMutableArray* _sizeCheckers;
	NSMutableArray* _fileDownloaders;
	int _status;
	int _curFile;
	NSMutableArray* _fileSizes;
	id<FilesDownloaderDelegate> _delegate;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain) id<FilesDownloaderDelegate> delegate;
@property(copy) NSString* sourcePath;
+(id)downloaderWithFiles:(id)files withSourcePath:(id)sourcePath;
-(void)downloadFailedWithError:(id)error;
-(void)downloadFinished;
-(void)downloadSizeUpdated;
-(int)totalContentLength;
-(int)totalContentDownloaded;
-(float)totalPercentsDone;
-(id)destinationPathForFileWithName:(id)name;
-(void)downloadComplete;
-(void)stopDownloading;
-(void)startDownloading;
-(void)cancel;
-(void)start;
-(void)stopSizeChecking;
-(void)startSizeChecking;
-(void)dealloc;
-(id)initWithFiles:(id)files withSourcePath:(id)sourcePath;
@end

