/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSData, NSFileHandle;

__attribute__((visibility("hidden")))
@interface GhostData : XXUnknownSuperclass {
	NSFileHandle* ghostFile;
	NSData* ghostData;
	NSData* ghostHeader;
	NSData* ghostOutfit;
	unsigned ghostVersion;
	unsigned long ghostRecLen;
	unsigned heroStyleID;
	unsigned engineStyleID;
	unsigned wheelStyleID;
}
@property(readonly, assign, nonatomic) unsigned wheelStyleID;
@property(readonly, assign, nonatomic) unsigned engineStyleID;
@property(readonly, assign, nonatomic) unsigned heroStyleID;
@property(readonly, assign, nonatomic) unsigned long ghostRecLen;
@property(readonly, assign, nonatomic) unsigned ghostVersion;
-(void).cxx_destruct;
-(void)parseGhostHeader;
-(id)initWithData:(id)data;
-(id)initWithFile:(id)file;
@end

