/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "TrialGameControllerDelegate.h"
#import "HSMenuLayer.h"

@class NSMutableDictionary, UIImage, CCSprite, NSMutableArray, MedalReward, NSDictionary, Level, HSMenuItem, HSAdjustedOpacityNode, SuperStarSunBeams, HSLabelSafeBMFont, HSScale9Sprite, TrialLayer, TrialSession;

__attribute__((visibility("hidden")))
@interface GoalDialog : HSMenuLayer <TrialGameControllerDelegate> {
	UIImage* screenShot;
	TrialLayer* trialLayer;
	TrialSession* session;
	Level* levelState;
	NSDictionary* levelData;
	NSDictionary* groupData;
	unsigned newMedalsBits;
	unsigned oldMedalsBits;
	int currentGoalTime;
	int diff;
	BOOL newRecord;
	BOOL newTime;
	BOOL lockedAlerts;
	BOOL trialLayerFadedOut;
	HSAdjustedOpacityNode* timeNode;
	NSMutableArray* medalScaleBounceAnimations;
	NSMutableArray* medalParticles;
	CCSprite* emptyMedals;
	CCSprite* superStarEmpty;
	CCSprite* superStar;
	SuperStarSunBeams* superStarSunBeams;
	HSLabelSafeBMFont* superStarTargetLabel;
	NSMutableArray* superStarParticles;
	MedalReward* rewardMedalsDialog;
	HSMenuLayer* rewardSuperStarDialog;
	NSMutableArray* rewardDialogs;
	NSMutableDictionary* menuItems;
	CCSprite* heroBody;
	HSScale9Sprite* heroBodyBg;
	HSScale9Sprite* heroBodyFg;
	HSMenuItem* storeButton;
	HSMenuItem* challengesButton;
	HSLabelSafeBMFont* challengeSentLabel;
	HSMenuItem* restartButton;
	CCSprite* blinkArrow;
	CCSprite* challengesButtonArrow;
	BOOL goalAnimated;
	BOOL clickedNextLevel;
	BOOL disabledForChallenges;
}
+(id)menuWithSession:(id)session levelData:(id)data state:(id)state checkpoints:(id)checkpoints startScreenShot:(id)shot oldMedals:(unsigned)medals newMedals:(unsigned)medals7;
-(void).cxx_destruct;
-(id)controllerItemForIndex:(unsigned)index;
-(id)controllerItemConfig;
-(unsigned)controllerDefaultItem;
-(void)controllerCancel;
-(void)postFirstVisit;
-(void)cleanup;
-(void)medalRewardDialogClosed:(id)closed;
-(void)showNextRewardDialog:(float)dialog;
-(void)setOpacity:(unsigned char)opacity;
-(void)postTransitionIn;
-(void)setChallengeSentLabel:(BOOL)label;
-(BOOL)inviteFacebookFriend:(id)aFriend;
-(void)challengeButtonAction:(id)action;
-(void)createMenu;
-(void)createMedals;
-(void)createTime;
-(BOOL)createFriendsList;
-(void)createHero;
-(id)initWithMenu:(id)menu session:(id)session levelData:(id)data state:(id)state checkpoints:(id)checkpoints startScreenShot:(id)shot oldMedals:(unsigned)medals newMedals:(unsigned)medals8;
-(id)initWithMenu:(id)menu;
@end

