/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface HSApplicationIconBadgeNumber : XXUnknownSuperclass {
}
+(void)report;
+(void)update;
+(void)reset;
+(void)setNumber:(unsigned)number for:(id)aFor;
+(unsigned)total;
+(void)setEnableHSNewsCounting:(BOOL)counting;
@end

