/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "NSObject.h"


@protocol HSB2QueryCallbackDelegate <NSObject>
-(bool)ReportFixture:(b2Fixture*)fixture;
@end

