/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "NSObject.h"


@protocol HSB2RaycastListenerDelegate <NSObject>
-(float)ReportFixture:(b2Fixture*)fixture point:(const b2Vec2*)point normal:(const b2Vec2*)normal fraction:(float)fraction;
@end

