/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "CCNode.h"
#import "CCRGBAProtocol.h"

@class CCLabelTTF, NSString, HSScale9Sprite;

__attribute__((visibility("hidden")))
@interface HSBadgeIndicator : CCNode <CCRGBAProtocol> {
	HSScale9Sprite* background;
	CCLabelTTF* label;
	ccColor3B color_;
	unsigned char opacity_;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) unsigned char opacity;
@property(assign, nonatomic) ccColor3B color;
+(id)badgeWithString:(id)string;
-(void).cxx_destruct;
-(void)setString:(id)string;
-(void)dealloc;
-(id)initWithString:(id)string;
@end

