/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "CCActionInterval.h"


__attribute__((visibility("hidden")))
@interface HSCallBlock : CCActionInterval {
	id hsBlock_;
	id hsBlockWithObject_;
	id object_;
}
+(id)actionWithDuration:(float)duration object:(id)object block:(id)block;
+(id)actionWithDuration:(float)duration block:(id)block;
+(id)actionWithBlock:(id)block;
-(void).cxx_destruct;
-(void)dealloc;
-(void)step:(float)step;
-(void)update:(float)update;
-(id)initWithHSBlock:(id)hsblock;
@end

