/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface HSDevice : XXUnknownSuperclass {
}
+(id)suffix;
+(id)postData;
+(id)deviceName;
+(id)firstName;
+(id)names;
+(id)fullName;
+(id)deviceHash;
+(id)pushId;
+(void)setPushId:(id)anId;
+(void)setDeviceId:(id)anId;
+(id)deviceId;
+(void)reset;
@end

