/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "CDLongAudioSourceDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class CDSoundEngine, CCScheduler, NSString;

__attribute__((visibility("hidden")))
@interface HSEngineSoundGenerator : XXUnknownSuperclass <CDLongAudioSourceDelegate> {
	NSString* soundId;
	float speed;
	float idleSpeed;
	float gain;
	float gainMin;
	float gainMax;
	float pitch;
	float pitchMin;
	float pitchMax;
	float originalMasterGain;
	float masterGain;
	BOOL isStopped;
	BOOL isMuted;
	unsigned source;
	unsigned currentSoundOffset;
	CDSoundEngine* soundEngine;
	unsigned soundSource1Aluint;
	float fadeOutFrom;
	float fadeOutTimer;
	float fadeOutTime;
	float speedEaseFrom;
	float speedEaseTo;
	float speedEaseTimer;
	float speedEaseTime;
	CCScheduler* scheduler;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) float idleSpeed;
@property(assign, nonatomic) float gainMax;
@property(assign, nonatomic) float gainMin;
@property(assign, nonatomic) float masterGain;
@property(assign, nonatomic) float pitchMax;
@property(assign, nonatomic) float pitchMin;
@property(assign, nonatomic) float fadeOutTime;
+(id)engineWithSound:(id)sound channel:(unsigned)channel;
+(id)engineWithSound:(id)sound source:(unsigned)source;
-(void).cxx_destruct;
-(void)dealloc;
-(void)setSpeed:(float)speed;
-(void)speedEase:(float)ease;
-(void)setSpeed:(float)speed ease:(BOOL)ease;
-(void)fadeOut:(float)anOut;
-(void)fadeOut;
-(void)setMute:(BOOL)mute;
-(id)initWithSound:(id)sound channel:(unsigned)channel source:(unsigned)source;
-(id)initWithSound:(id)sound source:(unsigned)source;
@end

