/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "CCNode.h"
#import "CCRGBAProtocol.h"
#import "CCTargetedTouchDelegate.h"

@class NSString, HSScale9Sprite;

__attribute__((visibility("hidden")))
@interface HSErrorBanner : CCNode <CCRGBAProtocol, CCTargetedTouchDelegate> {
	CGSize screenSize;
	unsigned retries;
	HSScale9Sprite* plate;
	BOOL cancelled;
	BOOL triggerPlayQueueOnDisappear;
	unsigned char opacity_;
	ccColor3B color_;
	BOOL opacityModifyRGB_;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) BOOL triggerPlayQueueOnDisappear;
+(void)continuePlayingQueue;
+(void)playQueue;
+(id)bannerWithMessage:(id)message font:(id)font spriteFrameName:(id)name;
-(void).cxx_destruct;
-(void)setOpacityModifyRGB:(BOOL)rgb;
-(BOOL)doesOpacityModifyRGB;
-(void)setOpacity:(unsigned char)opacity;
-(unsigned char)opacity;
-(void)setColor:(ccColor3B)color;
-(ccColor3B)color;
-(BOOL)ccTouchBegan:(id)began withEvent:(id)event;
-(void)cleanup;
-(void)show:(id)show alone:(BOOL)alone;
-(void)show:(id)show;
-(void)showAlone:(BOOL)alone;
-(void)show;
-(void)queue;
-(id)initWithMessage:(id)message font:(id)font spriteFrameName:(id)name;
@end

