/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "FBSDKSharingDelegate.h"

@class NSArray, NSString, NSURL, HSFacebookUser;

__attribute__((visibility("hidden")))
@interface HSFacebook : XXUnknownSuperclass <FBSDKSharingDelegate> {
	HSFacebookUser* me;
	NSArray* friends;
	NSURL* openedUrl;
	BOOL clientHasBeenConnected;
	NSString* initialConnectFrom;
	id _fbShareCallback;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(copy, nonatomic) NSString* initialConnectFrom;
@property(readonly, assign, nonatomic) NSArray* friends;
@property(readonly, assign, nonatomic) HSFacebookUser* me;
@property(copy, nonatomic) id fbShareCallback;
+(BOOL)canMessage;
+(id)sharedInstance;
+(BOOL)hasAccountInSettings;
+(BOOL)hasAppInstalled;
-(void).cxx_destruct;
-(BOOL)hasBeenInvited:(id)invited;
-(id)friendByID:(id)anId;
-(id)nonInvitedFriends;
-(id)invitedFriends;
-(void)invitedFriends:(id)friends;
-(void)friendsRequest:(id)request;
-(void)friends:(id)friends;
-(void)sharerDidCancel:(id)sharer;
-(void)sharer:(id)sharer didFailWithError:(id)error;
-(void)sharer:(id)sharer didCompleteWithResults:(id)results;
-(void)shareScreen:(id)screen withMessage:(id)message andUrl:(id)url andCallback:(id)callback;
-(BOOL)canShareScreen;
-(void)cantAccessAccountAlert;
-(void)logout;
-(void)checkTokenWithReadPermissions:(id)readPermissions callback:(id)callback;
-(void)requestForMe;
-(BOOL)isLoggedInWithPermissions:(id)permissions;
-(BOOL)isLoggedIn;
-(void)loggedIn;
-(void)loginToRead:(id)read callback:(id)callback;
-(void)login:(id)login;
-(void)login;
-(id)parseURLParams:(id)params;
-(void)dealloc;
-(id)init;
@end

