/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSDictionary, NSString;

__attribute__((visibility("hidden")))
@interface HSFacebookUser : XXUnknownSuperclass {
	NSDictionary* data;
	NSString* name;
	NSString* facebookID;
	BOOL installed;
	BOOL hasPicture;
}
@property(readonly, assign, nonatomic) BOOL hasPicture;
@property(readonly, assign, nonatomic) NSString* name;
@property(readonly, assign, nonatomic) NSString* facebookID;
@property(readonly, assign, nonatomic) BOOL installed;
+(id)temporaryFacebookUserByID:(id)anId;
-(void).cxx_destruct;
-(id)pictureWithWidth:(unsigned)width height:(unsigned)height callback:(id)callback;
-(id)initWithData:(id)data;
-(id)initTemporaryWithFacebookID:(id)facebookID;
@end

