/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol HSGameCenterManagerDelegate <NSObject>
@optional
-(void)unLoadPlayerByGameCenterPlayer:(id)player;
-(void)loadPlayerByGameCenterPlayer:(id)player;
-(void)gameCenterAchievementsSyncComplete:(id)complete;
@end

