/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "HSJustify.h"
#import "CCLabelTTF.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface HSLabelTTF : CCLabelTTF <HSJustify> {
	CGRect clip;
	BOOL clipping;
	CGPoint nonadjustedPosition;
	BOOL lockColor;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) NSUInteger hash;
+(id)labelWithString:(id)string fontName:(id)name fontSize:(float)size fontColor:(ccColor3B)color;
+(id)labelWithString:(id)string fontName:(id)name fontSize:(float)size;
-(void)visit;
-(void)postVisit;
-(void)preVisitWithClippingRect;
-(void)clip:(CGRect)clip;
-(float)relativeScale;
-(void)onEnter;
-(void)justifyRecursive;
-(void)justify;
-(void)setPosition:(CGPoint)position;
-(void)setColor:(ccColor3B)color;
-(void)lockColor;
@end

