/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "CCMenuItemSpriteIndependent.h"


__attribute__((visibility("hidden")))
@interface HSMenuItemSprite : CCMenuItemSpriteIndependent {
	id selected_block_;
	id unselected_block_;
}
@property(copy, nonatomic) id unselectedBlock;
@property(copy, nonatomic) id selectedBlock;
-(void).cxx_destruct;
-(void)setVisible:(BOOL)visible;
-(void)cleanup;
-(void)dealloc;
-(void)unselected;
-(void)selected;
-(CGPoint)convertToNodeSpace:(CGPoint)nodeSpace;
-(CGRect)rect;
@end

