/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "CCMenuItem.h"

@class HSScale9Sprite;

__attribute__((visibility("hidden")))
@interface HSMenuItemScale9Sprite : CCMenuItem {
	ccColor3B tint;
	ccColor3B selectedTint;
	HSScale9Sprite* bg;
}
+(id)itemWithSpriteFrameName:(id)spriteFrameName block:(id)block;
-(void).cxx_destruct;
-(void)dealloc;
-(void)setOpacity:(unsigned char)opacity;
-(void)cleanup;
-(void)setSelectedColor:(ccColor3B)color;
-(void)setColor:(ccColor3B)color;
-(void)unselected;
-(void)selected;
-(void)setContentSize:(CGSize)size;
-(id)initWithSpriteFrameName:(id)spriteFrameName block:(id)block;
@end

