/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "HSOpacityLayer.h"
#import "HSJustify.h"
#import "Boom-Structs.h"

@class CCArray, HSMenu, CCTouchDispatcher, NSString;

__attribute__((visibility("hidden")))
@interface HSMenuLayer : HSOpacityLayer <HSJustify> {
	HSMenu* menu;
	CGSize screenSize;
	BOOL isAnimating;
	BOOL isBeingRemoved;
	BOOL isBeingAdded;
	BOOL isOverlay;
	BOOL touchesPassThrough;
	BOOL destruct;
	BOOL purgeOtherLayers;
	BOOL isUnique;
	BOOL firstVisit;
	CCArray* touchDownNodes;
	CCTouchDispatcher* dispatcher;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) NSUInteger hash;
@property(readonly, assign, nonatomic) HSMenu* menu;
@property(assign, nonatomic) BOOL destruct;
@property(assign, nonatomic) BOOL touchesPassThrough;
@property(assign, nonatomic) BOOL isUnique;
@property(assign, nonatomic) BOOL isOverlay;
@property(assign, nonatomic) BOOL isBeingAdded;
@property(assign, nonatomic) BOOL isBeingRemoved;
@property(assign, nonatomic) BOOL isAnimating;
+(id)layerWithMenu:(id)menu;
+(id)scene;
+(id)menu;
//-(void).cxx_destruct;
-(void)dealloc;
-(void)cleanup;
-(void)ccTouchEnded:(id)ended withEvent:(id)event;
-(void)ccTouchCancelled:(id)cancelled withEvent:(id)event;
-(void)ccTouchMoved:(id)moved withEvent:(id)event;
-(BOOL)ccTouchBegan:(id)began withEvent:(id)event;
-(void)justifyRecursive;
-(void)justify;
-(BOOL)isPartOfThisLayer:(id)thisLayer;
-(void)postTransitionOut;
-(void)transitionOut;
-(void)preTransitionOut;
-(void)postTransitionIn;
-(void)transitionIn;
-(void)preTransitionIn;
-(id)transitionOutAction;
-(id)transitionInAction;
-(void)clearFirstVisit;
-(void)postFirstVisit;
-(void)visit;
-(void)onEnter;
-(id)initWithMenu:(id)menu;
-(id)init;
@end

