/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableData;

__attribute__((visibility("hidden")))
@interface HSMidpointDisplacement : XXUnknownSuperclass {
	unsigned steps_;
	float roughness_;
	float displacement_;
	NSMutableData* heightMap;
	float* heightMap_;
	float end;
	unsigned mapLen;
	unsigned mapPointer;
	float start;
}
@property(assign, nonatomic) float start;
-(void).cxx_destruct;
-(float)getNextInterpolated;
-(float)getNext;
-(void)generate;
-(id)initWithSteps:(unsigned)steps roughness:(float)roughness displacements:(float)displacements;
@end

