/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "HSPickerScrollDelegate.h"
#import "HSAdjustedOpacityLayer.h"
#import "Boom-Structs.h"

@class NSString;
@protocol HSPickerViewDataSource, HSPickerViewDelegate;

__attribute__((visibility("hidden")))
@interface HSPickerView : HSAdjustedOpacityLayer <HSPickerScrollDelegate> {
	BOOL repeatNodes;
	id<HSPickerViewDataSource> dataSource;
	id<HSPickerViewDelegate> delegate;
	int numberOfComponents;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(readonly, assign, nonatomic) int numberOfComponents;
@property(assign, nonatomic) id<HSPickerViewDelegate> delegate;
@property(assign, nonatomic) id<HSPickerViewDataSource> dataSource;
-(void)onDoneSpinning:(id)spinning;
-(void)onDoneSelecting:(id)selecting;
-(void)visit;
-(id)nodeForRow:(int)row forComponent:(int)component;
-(void)selectRow:(int)row inComponent:(int)component animated:(BOOL)animated;
-(int)selectedRowInComponent:(int)component;
-(CGSize)rowSizeForComponent:(int)component;
-(void)reloadComponent:(int)component;
-(void)reloadAllComponents;
-(int)numberOfRowsInComponent:(int)component;
-(void)spinComponent:(int)component speed:(float)speed easeRate:(float)rate repeat:(int)repeat stopRow:(int)row;
-(void)autoRepeatNodes:(BOOL)nodes;
-(void)initialLoad;
-(id)init;
@end

