/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "CCNode.h"


__attribute__((visibility("hidden")))
@interface HSProgressBar : CCNode {
	float progress;
	ccColor4F barColor;
	ccColor4F frameColor;
}
@property(assign, nonatomic) ccColor4F frameColor;
@property(assign, nonatomic) ccColor4F barColor;
@property(assign, nonatomic) float progress;
-(void)draw;
-(id)initWithPosition:(CGPoint)position dimension:(CGSize)dimension;
@end

