/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface HSRequestSecurity : XXUnknownSuperclass {
}
+(void)extractDataAndFiles:(id)files key:(id)key output:(id)output;
+(id)request:(id)request path:(id)path parameters:(id)parameters secureString:(id)string post:(BOOL)post secretKey:(id)key result:(id)result progress:(id)progress timeout:(double)timeout packetSize:(unsigned)size packetDelay:(double)delay;
+(id)request:(id)request path:(id)path parameters:(id)parameters secureString:(id)string post:(BOOL)post secretKey:(id)key result:(id)result progress:(id)progress timeout:(double)timeout;
+(id)request:(id)request path:(id)path parameters:(id)parameters secureString:(id)string post:(BOOL)post secretKey:(id)key result:(id)result progress:(id)progress;
+(id)request:(id)request path:(id)path parameters:(id)parameters secureString:(id)string post:(BOOL)post secretKey:(id)key result:(id)result packetSize:(unsigned)size packetDelay:(double)delay;
+(id)request:(id)request path:(id)path parameters:(id)parameters secureString:(id)string post:(BOOL)post secretKey:(id)key result:(id)result;
+(BOOL)isSecure:(id)secure secretKey:(id)key;
+(BOOL)isSecure:(id)secure;
+(void)secure:(id)secure secretKey:(id)key string:(id)string;
+(id)flatten:(id)flatten;
+(id)masterKey;
@end

