/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "CCSprite.h"


__attribute__((visibility("hidden")))
@interface HSSpriteSlice : CCSprite {
	ccV3F_C4B_T2F_Quad sliceQuad_;
	float startAngle;
	float endAngle;
	float centerAngle;
}
-(void)draw;
-(void)buildSlice;
-(void)sliceFrom:(float)from to:(float)to;
-(id)initWithTexture:(id)texture rect:(CGRect)rect rotated:(BOOL)rotated;
@end

