/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "CCSprite.h"


__attribute__((visibility("hidden")))
@interface HSSprite : CCSprite {
	CGRect clip;
	BOOL clipping;
}
-(void)visit;
-(void)postVisit;
-(void)preVisitWithClippingRect;
-(void)clip:(CGRect)clip;
-(float)relativeScale;
@end

