/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSIndexPath, NSString;

__attribute__((visibility("hidden")))
@interface HSTableCellInfo : XXUnknownSuperclass {
	BOOL header;
	BOOL footer;
	BOOL row;
	NSString* cellId;
	NSIndexPath* indexPath;
	unsigned section;
	float top;
	float bottom;
}
@property(assign, nonatomic) float bottom;
@property(assign, nonatomic) float top;
@property(assign, nonatomic) BOOL row;
@property(assign, nonatomic) BOOL footer;
@property(assign, nonatomic) BOOL header;
@property(assign, nonatomic) unsigned section;
@property(retain, nonatomic) NSIndexPath* indexPath;
@property(retain, nonatomic) NSString* cellId;
+(id)infoForFooterWithIdentifier:(id)identifier top:(float)top bottom:(float)bottom section:(unsigned)section;
+(id)infoForHeaderWithIdentifier:(id)identifier top:(float)top bottom:(float)bottom section:(unsigned)section;
+(id)infoForRowWithIdentifier:(id)identifier top:(float)top bottom:(float)bottom indexPath:(id)path;
-(void).cxx_destruct;
-(id)description;
-(BOOL)isAboveRowAtIndexPath:(id)indexPath;
-(BOOL)isBelowRowAtIndexPath:(id)indexPath;
-(BOOL)isAboveFooterInSection:(unsigned)section;
-(BOOL)isBelowFooterInSection:(unsigned)section;
-(BOOL)isAboveHeaderInSection:(unsigned)section;
-(BOOL)isBelowHeaderInSection:(unsigned)section;
@end

