/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "TrialGameControllerDelegate.h"
#import "HSTableViewDataSource.h"
#import "HSTableViewDelegate.h"
#import "HSMenuLayer.h"

@class NSMutableDictionary, CCMenu, NSArray, HSTableView, HSAdjustedSprite, HSAdjustedOpacityNode, NSString, NSMutableSet;

__attribute__((visibility("hidden")))
@interface InviteFriendsPopup : HSMenuLayer <HSTableViewDataSource, HSTableViewDelegate, TrialGameControllerDelegate> {
	HSAdjustedSprite* dialog;
	HSAdjustedOpacityNode* scroller;
	NSArray* rewards;
	BOOL havePresentedFacebookInviteRewards;
	CCMenu* menuItems;
	NSArray* friends;
	NSMutableSet* checkedFriends;
	NSMutableDictionary* friendNames;
	HSTableView* tableView;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
-(void).cxx_destruct;
-(id)controllerItemForIndex:(unsigned)index;
-(id)controllerItemConfig;
-(unsigned)controllerDefaultItem;
-(void)controllerCancel;
-(void)postFirstVisit;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(float)tableView:(id)view heightForRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(int)numberOfSectionsInTableView:(id)tableView;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(void)unSelectAll;
-(void)selectAll;
-(void)buildInvitePopup;
-(void)invite;
-(void)showFriends;
-(void)connectToFacebook;
-(void)close;
-(void)create:(id)create image:(id)image amount:(unsigned)amount;
-(void)setupScrollContent:(int)content checked:(BOOL)checked pos:(int)pos;
-(void)setupScroller;
-(void)buildPopup;
-(void)cleanup;
-(void)onExit;
-(id)initWithMenu:(id)menu;
@end

