/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface iPhoneEventSimulator : XXUnknownSuperclass {
	CFSocketRef cfSocket;
	CFRunLoopSourceRef cfSource;
	int sockHandle;
	id keyUpHandlers[512];
	id keyDownHandlers[512];
}
+(id)sharedSimulatorWithPort:(unsigned)port;
-(void).cxx_destruct;
-(void)dealloc;
-(void)resetHandlers;
-(void)addHandlersForKey:(int)key keyDown:(id)down keyUp:(id)up;
-(id)initWithPort:(unsigned)port;
-(id)downHandler:(unsigned short)handler;
-(id)upHandler:(unsigned short)handler;
@end

