/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "HSMenuItem.h"

@class CCSprite, HSLabelSafeBMFont, NSString;

__attribute__((visibility("hidden")))
@interface LevelSign : HSMenuItem {
	NSString* levelId;
	HSLabelSafeBMFont* levelName;
	HSLabelSafeBMFont* totalTime;
	CCSprite* medal1;
	CCSprite* medal2;
	CCSprite* medal3;
	CCSprite* superStar;
	CCSprite* collectedSuperStarSprite;
}
+(id)unLockedItemWithLevelData:(id)levelData levelState:(id)state selected:(BOOL)selected;
+(id)lockedItemWithCollectedSuperStars:(int)collectedSuperStars requiredSuperStars:(unsigned)stars animateSuperStar:(BOOL)star;
-(void).cxx_destruct;
-(void)cleanup;
-(void)setLevelData:(id)data levelState:(id)state;
-(void)showMedalsAndStars:(id)stars levelState:(id)state;
@end

