/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableDictionary, NSArray;

__attribute__((visibility("hidden")))
@interface LevelHandler : XXUnknownSuperclass {
	unsigned totalNumberOfMedalsAvailable;
	unsigned currentGroup;
	unsigned currentLevel;
	NSMutableDictionary* levelsById;
	NSMutableDictionary* groupsById;
	NSArray* allLevelGroups;
	unsigned lastSavedGroup;
	BOOL nextRunLevelKeepsCurrent;
	NSArray* levels;
	NSArray* levelGroups;
	unsigned count;
	unsigned groupCount;
}
@property(assign, nonatomic) BOOL nextRunLevelKeepsCurrent;
@property(assign, nonatomic) unsigned currentGroup;
@property(readonly, assign, nonatomic) unsigned totalNumberOfMedalsAvailable;
@property(readonly, assign, nonatomic) unsigned groupCount;
@property(readonly, assign, nonatomic) unsigned count;
@property(readonly, assign, nonatomic) NSArray* levelGroups;
@property(readonly, assign, nonatomic) NSArray* levels;
+(id)descriptionForTargetAtom:(id)targetAtom;
+(id)descriptionForTarget:(id)target;
+(void)reset;
+(id)sharedInstance;
-(void).cxx_destruct;
-(id)loadLevelHelperData:(id)data bgName:(id*)name hasClouds:(BOOL*)clouds;
-(void)tagLevelHelperData:(id)data bgName:(id*)name hasClouds:(BOOL*)clouds;
-(void)retag:(id)retag tagId:(int)anId tagName:(id)name;
-(void)runLevel:(id)level;
-(BOOL)unLockNextLevel;
-(id)firstLockedGroup;
-(id)groupDataByLevelId:(id)anId;
-(id)currentLevelDataByGroupId:(id)anId;
-(id)previousGroupIdById:(id)anId;
-(id)groupDataById:(id)anId;
-(id)levelDataById:(id)anId;
-(BOOL)onLastLevel;
-(id)nextLevelGroupData;
-(id)nextLevelDataWithoutLockedSuper;
-(id)nextLevelDataWithoutSuper;
-(BOOL)levelIsLocked:(id)locked;
-(id)nextLevelData;
-(BOOL)isNextLevelAvailable;
-(void)nextLevel:(id)level;
-(void)previousGroup;
-(id)currentLevelData;
-(id)currentGroupData;
-(unsigned)currentLevelInGroupById:(id)groupById;
-(unsigned)currentLevelInGroup:(unsigned)group;
-(void)setCurrentGroupByGroupId:(id)anId;
-(void)setCurrentGroupByProduct:(id)product;
-(void)setCurrentLevel:(unsigned)level forGroupId:(id)groupId;
-(void)setCurrentLevel:(unsigned)level;
-(void)resetToLastSavedGroup;
-(BOOL)lastLevel;
-(BOOL)firstLevel;
-(unsigned)numOfUnlockedGroups;
-(void)unlockGroups;
-(void)initGroups;
-(id)init;
@end

