/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "HSMenuLayer.h"
#import "HSTableViewDataSource.h"
#import "TrialGameControllerDelegate.h"
#import "HSTableViewDelegate.h"

@class NSArray, HSTableView, NSDictionary, NSString, NSIndexPath, CCMenu;

__attribute__((visibility("hidden")))
@interface LevelSelect : HSMenuLayer <HSTableViewDataSource, HSTableViewDelegate, TrialGameControllerDelegate> {
	HSTableView* tableView;
	NSDictionary* groupData;
	NSArray* groupLevels;
	BOOL hasTotalTime;
	unsigned totalTimeForGroup;
	unsigned normalLevels;
	unsigned superStarLevels;
	int collectedSuperStars;
	NSIndexPath* selectedIndexPath;
	CCMenu* menuItems;
	NSString* levelGroupId;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(readonly, assign, nonatomic) NSString* levelGroupId;
+(id)sceneWithLevelGroupId:(id)levelGroupId animateSuperStar:(unsigned)star;
+(id)sceneWithLevelGroupId:(id)levelGroupId;
+(id)layerWithMenu:(id)menu levelGroupId:(id)anId animateSuperStar:(unsigned)star;
+(id)layerWithMenu:(id)menu levelGroupId:(id)anId;
-(void).cxx_destruct;
-(id)controllerItemForIndex:(unsigned)index;
-(id)controllerItemConfig;
-(unsigned)controllerDefaultItem;
-(void)controllerCancel;
-(void)postFirstVisit;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(int)numberOfSectionsInTableView:(id)tableView;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view viewForHeaderInSection:(int)section;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(float)tableView:(id)view heightForHeaderInSection:(int)section;
-(float)tableView:(id)view heightForRowAtIndexPath:(id)indexPath;
-(void)cleanup;
-(void)postTransitionIn;
-(id)initWithMenu:(id)menu levelGroupId:(id)anId animateSuperStar:(unsigned)star;
-(id)initWithMenu:(id)menu;
@end

