/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class CCTexture2D;

__attribute__((visibility("hidden")))
@interface LHBezierBlendingInfo : XXUnknownSuperclass {
	CCTexture2D* texture;
	unsigned blendSource;
	unsigned blendDestination;
	bool tile;
}
+(id)bezierBlendingInfoWithTexture:(id)texture blendSource:(unsigned)source blendDestination:(unsigned)destination tile:(bool)tile;
-(void).cxx_destruct;
-(bool)tile;
-(unsigned)blendDestination;
-(unsigned)blendSource;
-(id)texture;
-(id)initBezierBlendingInfoWithTexture:(id)texture blendSource:(unsigned)source blendDestination:(unsigned)destination tile:(bool)tile;
-(void)dealloc;
@end

