/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "HSOpacityNode.h"
#import "CCStandardTouchDelegate.h"
#import "CCTargetedTouchDelegate.h"

@class NSMutableArray, NSString, LevelHelperLoader, LHObserverPair, CCTexture2D;

__attribute__((visibility("hidden")))
@interface LHBezierNode : HSOpacityNode <CCStandardTouchDelegate, CCTargetedTouchDelegate> {
	bool isClosed;
	bool isTile;
	bool isVisible;
	bool isLine;
	bool isPath;
	NSString* uniqueName;
	b2Body* body;
	NSMutableArray* pathPoints;
	CCTexture2D* texture;
	CGRect color;
	CGRect lineColor;
	float lineWidth;
	CGSize winSize;
	NSMutableArray* trianglesHolder;
	NSMutableArray* linesHolder;
	NSMutableArray* blendingTextures;
	CGSize imageSize;
	LHObserverPair* touchBeginObserver;
	LHObserverPair* touchMovedObserver;
	LHObserverPair* touchEndedObserver;
	LHObserverPair* tagTouchBeginObserver;
	LHObserverPair* tagTouchMovedObserver;
	LHObserverPair* tagTouchEndedObserver;
	bool swallowTouches;
	LevelHelperLoader* parentLoader;
	ccV3F_C4B_T2F_Triangle* _points;
	CGPoint* line_verts;
	unsigned VBOname_;
	unsigned VAOname_;
	ccBlendFunc blendFunc_;
	int u_color_location;
	int triangles;
	unsigned baseOpacity;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign) bool swallowTouches;
@property(readonly, assign) bool isLine;
@property(readonly, assign) bool isVisible;
@property(readonly, assign) bool isTile;
@property(readonly, assign) bool isClosed;
+(bool)isLHBezierNode:(id)node;
+(id)nodeWithDictionary:(id)dictionary cocosLayer:(id)layer physicWorld:(b2World*)world parent:(id)parent;
+(CGPoint)pointOnCurve:(CGPoint)curve p2:(CGPoint)a2 p3:(CGPoint)a3 p4:(CGPoint)a4 t:(float)t;
-(void).cxx_destruct;
-(void)ccTouchEnded:(id)ended withEvent:(id)event;
-(void)ccTouchMoved:(id)moved withEvent:(id)event;
-(BOOL)ccTouchBegan:(id)began withEvent:(id)event;
-(void)registerTouchEndedObserver:(id)observer selector:(SEL)selector;
-(void)registerTouchMovedObserver:(id)observer selector:(SEL)selector;
-(void)registerTouchBeginObserver:(id)observer selector:(SEL)selector;
-(bool)isTouchedAtPoint:(CGPoint)point;
-(void)pushBlendingTextureNamed:(id)named;
-(void)pushBlendingTextureNamed:(id)named shouldTile:(bool)tile;
-(void)pushBlendingTextureNamed:(id)named shouldTile:(bool)tile blendingSource:(unsigned)source blendingDestination:(unsigned)destination;
-(id)addSpriteOnPath:(id)path speed:(float)speed startAtEndPoint:(bool)endPoint isCyclic:(bool)cyclic restartAtOtherEnd:(bool)otherEnd axisOrientation:(int)orientation flipX:(bool)x flipY:(bool)y deltaMovement:(bool)movement;
-(void)draw;
-(void)visit;
-(b2Body*)body;
-(id)uniqueName;
-(void)setupVBOandVAO;
-(void)setOpacity:(unsigned char)opacity;
-(id)initWithDictionary:(id)dictionary cocosLayer:(id)layer physicWorld:(b2World*)world parent:(id)parent;
-(void)createBodyFromDictionary:(id)dictionary physicWorld:(b2World*)world;
-(void)initPathPointsFromDictionary:(id)dictionary;
-(void)initTileVerticesFromDictionary:(id)dictionary;
-(void)cleanup;
-(void)dealloc;
-(void)setTagTouchEndedObserver:(id)observer;
-(void)setTagTouchMovedObserver:(id)observer;
-(void)setTagTouchBeginObserver:(id)observer;
@end

