/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface LHContactNodeInfo : XXUnknownSuperclass {
	int tagB;
	id listenerId;
	SEL listenerSel;
}
+(id)contactInfoWithTag:(int)tag listenerId:(id)anId listenerSel:(SEL)sel;
-(void).cxx_destruct;
-(void)callListenerWithBodyA:(b2Body*)bodyA bodyB:(b2Body*)b contact:(b2Contact*)contact contactType:(int)type oldManifold:(const b2Manifold*)manifold impulse:(const b2ContactImpulse*)impulse;
-(int)tagB;
-(id)initContactInfoWithTag:(int)tag listenerId:(id)anId listenerSel:(SEL)sel;
-(void)dealloc;
@end

