/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface LHContactInfo : XXUnknownSuperclass {
	b2Body* bodyA;
	b2Body* bodyB;
	int contactType;
	b2Contact* contact;
	const b2Manifold* oldManifold;
	const b2ContactImpulse* impulse;
}
+(id)contactInfoWithBodyA:(b2Body*)bodyA bodyB:(b2Body*)b contact:(b2Contact*)contact contactType:(int)type manifold:(const b2Manifold*)manifold impulse:(const b2ContactImpulse*)impulse;
-(const b2ContactImpulse*)impulse;
-(const b2Manifold*)oldManifold;
-(b2Contact*)contact;
-(id)bezierB;
-(id)bezierA;
-(id)spriteB;
-(id)spriteA;
-(CGPoint)contactPoint;
-(int)contactType;
-(b2Fixture*)fixtureB;
-(b2Fixture*)fixtureA;
-(b2Body*)bodyB;
-(b2Body*)bodyA;
-(void)setupWithInfo:(b2Body*)info bodyB:(b2Body*)b contact:(b2Contact*)contact contactType:(int)type manifold:(const b2Manifold*)manifold impulse:(const b2ContactImpulse*)impulse;
-(id)initWithInfo:(b2Body*)info bodyB:(b2Body*)b contact:(b2Contact*)contact contactType:(int)type manifold:(const b2Manifold*)manifold impulse:(const b2ContactImpulse*)impulse;
-(void)dealloc;
@end

