/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableDictionary;

__attribute__((visibility("hidden")))
@interface LHCustomSpriteMgr : XXUnknownSuperclass {
	NSMutableDictionary* classesDictionary;
}
+(id)sharedInstance;
-(void).cxx_destruct;
-(Class)customSpriteClassForTag:(int)tag;
-(void)registerCustomSpriteClass:(Class)aClass forTag:(int)tag;
-(id)init;
-(void)dealloc;
@end

