/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface LHSettings : XXUnknownSuperclass {
	bool useRetinaOnIpad;
	float lhPtmRatio;
	float customAlpha;
	int newBodyId;
	CGPoint convertRatio;
	CGPoint realConvertRatio;
	bool convertLevel;
	bool stretchArt;
	CGPoint possitionOffset;
	bool levelPaused;
	bool isCoronaUser;
	bool preloadBatchNodes;
}
@property(assign) bool preloadBatchNodes;
@property(assign) bool isCoronaUser;
@property(assign) bool levelPaused;
@property(assign) bool convertLevel;
@property(assign) float customAlpha;
@property(assign) float lhPtmRatio;
@property(assign) bool useRetinaOnIpad;
+(id)sharedInstance;
-(CGPoint)realConvertRatio;
-(CGPoint)convertRatio;
-(CGPoint)possitionOffset;
-(void)setConvertRatio:(CGPoint)ratio usesCustomSize:(bool)size;
-(bool)stretchArt;
-(void)setStretchArt:(bool)art;
-(bool)isIphone5;
-(bool)isIpad;
-(int)runningDevice;
-(bool)usesFallbackResolution:(id)resolution;
-(bool)shouldScaleImageOnRetina:(id)retina;
-(id)imagePath:(id)path imageFolder:(id)folder;
-(int)newBodyId;
-(id)init;
-(void)dealloc;
@end

