/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableDictionary;

__attribute__((visibility("hidden")))
@interface LHTouchMgr : XXUnknownSuperclass {
	NSMutableDictionary* onTouchBeginOnSpriteOfTag;
	NSMutableDictionary* onTouchMovedOnSpriteOfTag;
	NSMutableDictionary* onTouchEndedOnSpriteOfTag;
	NSMutableDictionary* swallowTouchesOnTag;
	NSMutableDictionary* priorityForTouchesOfTag;
}
+(id)sharedInstance;
-(void).cxx_destruct;
-(int)priorityForTag:(int)tag;
-(bool)shouldTouchesBeSwallowedForTag:(int)tag;
-(id)onTouchEndedObserverForTag:(int)tag;
-(id)onTouchMovedObserverForTag:(int)tag;
-(id)onTouchBeginObserverForTag:(int)tag;
-(void)removeTouchEndedObserver:(id)observer;
-(void)removeTouchMovedObserver:(id)observer;
-(void)removeTouchBeginObserver:(id)observer;
-(void)registerTouchEndedObserver:(id)observer selector:(SEL)selector forTag:(int)tag;
-(void)registerTouchMovedObserver:(id)observer selector:(SEL)selector forTag:(int)tag;
-(void)registerTouchBeginObserver:(id)observer selector:(SEL)selector forTag:(int)tag;
-(void)swallowTouchesForTag:(int)tag;
-(void)setPriority:(int)priority forTouchesOfTag:(int)tag;
-(id)init;
-(void)dealloc;
@end

