/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "TrialGameControllerDelegate.h"
#import "HSOpacityNode.h"

@class HSLabelSafeBMFont, NSObject, CCMenu, HSAdjustedSprite, Spinner;

__attribute__((visibility("hidden")))
@interface LoadingPopup : HSOpacityNode <TrialGameControllerDelegate> {
	HSLabelSafeBMFont* message;
	Spinner* loading;
	HSAdjustedSprite* dialog;
	NSObject<TrialGameControllerDelegate>* parentDelegate;
	CCMenu* menuItems;
}
-(void).cxx_destruct;
-(id)controllerItemForIndex:(unsigned)index;
-(id)controllerItemConfig;
-(unsigned)controllerDefaultItem;
-(void)controllerCancel;
-(void)releaseGameController;
-(void)takeGameController;
-(void)cleanup;
-(void)close;
-(void)showCloseButtonWithCallback:(id)callback retryButtonWithCallback:(id)callback2;
-(void)showCloseButtonWithCallback:(id)callback;
-(void)showCloseButton;
-(void)setMessage:(id)message;
-(void)showDialogWithMessage:(id)message;
-(id)initWithMessage:(id)message;
-(id)init;
@end

