/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "TrialGameControllerDelegate.h"
#import "HSMenuLayer.h"

@class CCMenu, NSDictionary, HSAdjustedSprite, GoalDialog;

__attribute__((visibility("hidden")))
@interface MedalReward : HSMenuLayer <TrialGameControllerDelegate> {
	HSAdjustedSprite* dialog;
	GoalDialog* goalDialog;
	NSDictionary* reward;
	CCMenu* menuItems;
	NSDictionary* nextReward;
}
@property(retain, nonatomic) GoalDialog* goalDialog;
+(id)maybeShowReward:(id)reward;
+(void)resetRewards;
-(void).cxx_destruct;
-(id)controllerItemForIndex:(unsigned)index;
-(id)controllerItemConfig;
-(unsigned)controllerDefaultItem;
-(void)controllerCancel;
-(void)postFirstVisit;
-(void)cleanup;
-(void)postTransitionIn;
-(void)close;
-(void)continue;
-(void)setupReward;
-(BOOL)hasContinueScreen;
-(void)setupMedalReward;
-(void)setupThemeReward;
-(id)initWithMenu:(id)menu rewardInfo:(id)info nextRewardInfo:(id)info3;
@end

