/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MedalReward.h"

@class Wheely, CCRenderTexture;

__attribute__((visibility("hidden")))
@interface MedalRewardChallenge : MedalReward {
	CCRenderTexture* ghost;
	Wheely* youGhost;
}
-(void).cxx_destruct;
-(BOOL)hasContinueScreen;
-(void)visit;
-(void)cleanup;
-(void)continue;
-(void)setupReward;
-(void)postTransitionIn;
@end

