/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "MedalReward.h"

@class HSLabelSafeBMFont;

__attribute__((visibility("hidden")))
@interface MedalRewardCoins : MedalReward {
	HSLabelSafeBMFont* rewardUnLockedLabel;
}
-(void).cxx_destruct;
-(void)cleanup;
-(BOOL)hasContinueScreen;
-(void)updateCoinbar;
-(void)continue;
-(void)setupReward;
@end

