/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "LHSprite.h"


__attribute__((visibility("hidden")))
@interface MovingFlat : LHSprite {
	b2Vec2 startPos;
	b2Vec2 endPos;
	BOOL targetSet;
	float speed;
	BOOL startToEnd;
	b2Vec2 dir;
	BOOL wrap;
	BOOL hasTrigger;
	BOOL triggered;
}
-(id).cxx_construct;
-(void)trigger;
-(void)startMoving;
-(void)postUpdate:(float)update;
-(void)postInitialization;
@end

