/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "HSMenuLayer.h"
#import "Boom-Structs.h"

@class HSScrollView, MenuTrial;

__attribute__((visibility("hidden")))
@interface News : HSMenuLayer {
	HSScrollView* newsScroller;
	CGRect newsRect;
	MenuTrial* menuTrial;
}
+(CGAffineTransform)transformForOrientation:(id)orientation size:(CGSize)size;
+(id)resizedImage:(id)image size:(CGSize)size transform:(CGAffineTransform)transform drawTransposed:(BOOL)transposed interpolationQuality:(int)quality;
+(void)listNews:(id)news newsRect:(CGRect)rect parent:(id)parent;
-(void).cxx_destruct;
-(void)cleanup;
-(void)onExit;
-(void)update:(float)update;
-(void)setMenuTrialLayer:(id)layer;
-(id)initWithMenu:(id)menu;
@end

