/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableDictionary, NSDictionary;

__attribute__((visibility("hidden")))
@interface OfferHandler : XXUnknownSuperclass {
	NSMutableDictionary* offerState;
	NSDictionary* offers;
}
+(id)sharedInstance;
-(void).cxx_destruct;
-(void)maybeShowOffer;
-(id)activeOfferWithMenu:(id)menu;
-(id)activeOfferTime;
-(void)closeActiveOffer;
-(void)registerEvent:(id)event trigger:(BOOL)trigger force:(BOOL)force;
-(void)registerEvent:(id)event trigger:(BOOL)trigger;
-(void)registerEvent:(id)event;
-(id)realProductsForOffer:(id)offer;
-(id)allOfferProducts;
-(void)triggerOffer:(unsigned)offer;
-(void)reset;
-(id)init;
@end

