/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "HSMenuLayer.h"
#import "TrialGameControllerDelegate.h"
#import "Boom-Structs.h"

@class NSMutableDictionary, HSScrollView;

__attribute__((visibility("hidden")))
@interface PauseDialog : HSMenuLayer <TrialGameControllerDelegate> {
	HSScrollView* newsScroller;
	CGRect newsRect;
	BOOL clickedNextLevel;
	NSMutableDictionary* buttons;
}
+(id)menuWithSession:(id)session levelServer:(id)server;
+(id)layerWithMenu:(id)menu session:(id)session levelServer:(id)server;
-(void).cxx_destruct;
-(id)controllerItemForIndex:(unsigned)index;
-(id)controllerItemConfig;
-(unsigned)controllerDefaultItem;
-(void)controllerCancel;
-(void)postFirstVisit;
-(void)postTransitionIn;
-(void)cleanup;
-(void)setOpacity:(unsigned char)opacity;
-(id)initWithMenu:(id)menu session:(id)session levelServer:(id)server;
-(id)initWithMenu:(id)menu;
@end

