/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "HSMenuLayer.h"
#import "TrialGameControllerDelegate.h"

@class HSMenuItem, FBShare, UIImage, CCSprite, CCMenu, LoadingPopup;

__attribute__((visibility("hidden")))
@interface Profile : HSMenuLayer <TrialGameControllerDelegate> {
	CCSprite* license;
	CCMenu* menuItems;
	CCSprite* levelPhoto;
	HSMenuItem* challengeButton;
	HSMenuItem* backButton;
	LoadingPopup* loading;
	FBShare* shareButton;
	BOOL grabScreen;
	UIImage* screenShot;
	unsigned levelPhotoTouchCount;
	BOOL isSelf;
	BOOL isFriend;
}
@property(assign, nonatomic) BOOL isFriend;
+(id)countryFlagByCode:(id)code;
+(id)countryByCode:(id)code;
//-(void).cxx_destruct;
-(BOOL)ccTouchBegan:(id)began withEvent:(id)event;
-(void)registerWithTouchDispatcher;
-(id)controllerItemForIndex:(unsigned)index;
-(id)controllerItemConfig;
-(unsigned)controllerDefaultItem;
-(void)controllerCancel;
-(void)postFirstVisit;
-(void)postTransitionIn;
-(void)visit;
-(void)cleanup;
-(void)onEnter;
-(void)back;
-(id)label:(id)label info:(id)info icon:(id)icon ttf:(BOOL)ttf;
-(void)screenShotDone;
-(void)shareScreen;
-(id)infoNode:(id)node suffix:(id)suffix label:(id)label label2ndLine:(id)line subLabel:(id)label5;
-(void)setPlayer:(id)player;
-(id)initWithMenu:(id)menu;
@end

