/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol ProfileDataSource <NSObject>
-(id)worldRank;
-(id)maxGroupIdUnlocked;
-(float)totalDistance;
-(unsigned)totalEarnedSuperStars;
-(unsigned)totalEarnedMedals;
-(id)tournamentStats;
-(id)challengeStats;
-(id)countryCode;
-(id)nickname;
-(id)wheelStyle;
-(id)engineStyle;
-(id)heroStyle;
-(id)uuid;
@end

