/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "HSIAPManagerRestoreProtocol.h"
#import "Boom-Structs.h"
#import "HSMenuLayer.h"

@class Spinner, CCSprite, HSLabelSafeBMFont, NSString;

__attribute__((visibility("hidden")))
@interface RestorePurchases : HSMenuLayer <HSIAPManagerRestoreProtocol> {
	CCSprite* processing;
	Spinner* spinner;
	HSLabelSafeBMFont* processingLabel;
	NSString* productId;
	id onComplete;
	BOOL restoredPurchases;
}
+(id)layerWithMenu:(id)menu onComplete:(id)complete;
-(void).cxx_destruct;
-(void)restoreFinished:(BOOL)finished;
-(void)restoreCallback:(BOOL)callback productIdentifier:(id)identifier;
-(void)cleanup;
-(BOOL)ccTouchBegan:(id)began withEvent:(id)event;
-(void)restoreItems;
-(id)initWithMenu:(id)menu onComplete:(id)complete;
-(id)initWithMenu:(id)menu;
@end

