/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AppRemoteNotifications.h"
#import "Boom-Structs.h"
#import "TrialGameControllerDelegate.h"
#import "HSTableViewDataSource.h"
#import "HSTableViewDelegate.h"
#import "HSMenuLayer.h"

@class CCMenu, NSMutableArray, HSTableView, NSString;

__attribute__((visibility("hidden")))
@interface Settings : HSMenuLayer <HSTableViewDataSource, HSTableViewDelegate, AppRemoteNotifications, TrialGameControllerDelegate> {
	HSTableView* tableView;
	BOOL showNoICloudSetupInfo;
	BOOL showNotificationsSettings;
	NSMutableArray* settings;
	BOOL isConnectingToFacebook;
	CCMenu* menuItems;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
+(id)scene;
-(void).cxx_destruct;
-(id)controllerItemForIndex:(unsigned)index;
-(id)controllerItemConfig;
-(unsigned)controllerDefaultItem;
-(void)controllerCancel;
-(void)postFirstVisit;
-(void)postTransitionIn;
-(void)remoteNotificationError:(id)error;
-(void)remoteNotificationDeviceToken:(id)token;
-(id)tableView:(id)view viewForFooterInSection:(int)section;
-(float)tableView:(id)view heightForFooterInSection:(int)section;
-(void)promptChallengeNotifications:(id)notifications;
-(void)promptEmail:(id)email;
-(void)promptUsername:(id)username;
-(void)waitForLogin:(id)login;
-(void)setLowerButtonsIsEnabled:(BOOL)enabled;
-(void)setSoundIsEnabled:(BOOL)enabled;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(int)numberOfSectionsInTableView:(id)tableView;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view viewForHeaderInSection:(int)section;
-(float)tableView:(id)view heightForHeaderInSection:(int)section;
-(float)tableView:(id)view heightForRowAtIndexPath:(id)indexPath;
-(void)onExit;
-(void)onEnter;
-(void)createMenu;
-(void)cleanup;
-(id)initWithMenu:(id)menu;
@end

