/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableDictionary, NSArray;

__attribute__((visibility("hidden")))
@interface SHSceneNode : XXUnknownSuperclass {
	NSMutableDictionary* sprites;
	NSArray* animations;
}
@property(readonly, assign) NSArray* animations;
+(id)SHSceneNodeWithContentOfFile:(id)file;
-(void).cxx_destruct;
-(id)infoForSpriteNamed:(id)spriteNamed;
-(id)initWithContentOfFile:(id)file;
-(void)dealloc;
@end

