/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSFileHandle, NSURLConnection, NSObject, NSString;
@protocol SingleFileDownloaderDelegate;

__attribute__((visibility("hidden")))
@interface SingleFileDownloader : XXUnknownSuperclass {
	BOOL _downloading;
	NSURLConnection* _connection;
	NSFileHandle* _fileHandle;
	NSString* _filename;
	NSString* _sourcePath;
	NSObject<SingleFileDownloaderDelegate>* _delegate;
	unsigned _bytesReceived;
	unsigned _bytesTotal;
}
+(id)fileDownloaderWithSourcePath:(id)sourcePath targetFilename:(id)filename delegate:(id)delegate;
+(id)newFileWithName:(id)name;
+(BOOL)checkTargetDirectory:(id)directory;
+(id)destinationDirectoryPath;
+(id)tmpPathWithFilename:(id)filename;
+(id)tmpSuffix;
-(void)connection:(id)connection didFailWithError:(id)error;
-(void)connectionDidFinishLoading:(id)connection;
-(void)connection:(id)connection didReceiveData:(id)data;
-(id)connection:(id)connection willSendRequest:(id)request redirectResponse:(id)response;
-(void)connection:(id)connection didReceiveResponse:(id)response;
-(unsigned)contentLength;
-(unsigned)contentDownloaded;
-(id)targetPath;
-(void)cancelDownload;
-(void)startDownload;
-(void)dealloc;
-(id)initWithSourcePath:(id)sourcePath targetFilename:(id)filename delegate:(id)delegate;
@end

