/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "HSAdjustedSprite.h"

@class UITextView;

__attribute__((visibility("hidden")))
@interface SpeechBubble : HSAdjustedSprite {
	UITextView* textView;
}
+(id)bubbleWithText:(id)text atPosition:(CGPoint)position;
-(void).cxx_destruct;
-(void)cleanup;
-(void)onEnter;
-(void)setupWithText:(id)text;
@end

