/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "HSMenuItem.h"


__attribute__((visibility("hidden")))
@interface TextButton : HSMenuItem {
}
+(id)greenUltrawideButtonWithLabel:(id)label block:(id)block;
+(id)greenWideButtonWithLabel:(id)label block:(id)block;
+(id)greenTextButtonWithLabel:(id)label block:(id)block;
+(id)textButtonWithLabel:(id)label block:(id)block;
@end

