/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "HSAdjustedSprite.h"

@class HSMenuItem, CCNode, HSMenu, CCSprite, NSString;

__attribute__((visibility("hidden")))
@interface ThemeSelector : HSAdjustedSprite {
	HSMenu* menu_;
	CCNode* medals;
	CCSprite* cover;
	HSMenuItem* button;
	NSString* groupId;
	NSString* levelId;
	BOOL sunken;
	HSAdjustedSprite* flag;
	CGPoint friendFlagPosition;
	CGPoint sunkFriendFlagPosition;
	CGSize screenSize;
	BOOL checkOnScreen;
	id doneBlock;
}
@property(assign, nonatomic) CGPoint sunkFriendFlagPosition;
@property(assign, nonatomic) CGPoint friendFlagPosition;
+(id)extremeWithMenu:(id)menu;
+(id)comingSoonWithMenu:(id)menu;
+(id)festivalParkWithMenu:(id)menu;
+(id)robotFactoryWithMenu:(id)menu;
+(id)pyramidDunesWithMenu:(id)menu;
+(id)frozenHillsWithMenu:(id)menu;
+(id)lostCityWithMenu:(id)menu;
+(id)jurassicJungleWithMenu:(id)menu;
-(void).cxx_destruct;
-(void)visit;
-(void)onScreen;
-(void)showExtremePopup;
-(void)setupComingSoon;
-(void)removeLockWithDoneBlock:(id)doneBlock;
-(void)showLoadingOnSelect;
-(void)replaceSceneAndShowLevelSelect;
-(void)replaceSceneAndShowLevelSelectOnSelect;
-(void)playLevel;
-(void)playLevelOnSelect;
-(void)hideFlag;
-(void)setupFlag:(id)flag animate:(BOOL)animate;
-(void)setup:(id)setup forceLocked:(BOOL)locked;
-(void)buildExtreme;
-(void)showInfoQuick;
-(void)riseWithDoneBlock:(id)doneBlock;
-(void)rise;
-(void)shake;
-(void)doRiseWithoutInfo;
-(void)doRise;
-(void)sink;
-(void)showInfo;
-(void)updateMedals;
-(void)hideInfo;
-(void)cleanup;
-(id)button;
@end

