/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSSet, NSDate, Level, TournamentState, NSNumber, NSString;

__attribute__((visibility("hidden")))
@interface Tournament : XXUnknownSuperclass {
}
@property(retain, nonatomic) NSNumber* noSuper;
@property(retain, nonatomic) TournamentState* state;
@property(retain, nonatomic) NSSet* players;
@property(retain, nonatomic) Level* level;
@property(retain, nonatomic) NSSet* cachedPlayers;
@property(retain, nonatomic) NSNumber* multiTarget;
@property(retain, nonatomic) NSNumber* validTime;
@property(retain, nonatomic) NSString* uuid;
@property(retain, nonatomic) NSDate* startTime;
@property(retain, nonatomic) NSNumber* rank;
@property(retain, nonatomic) NSNumber* qualified;
@property(retain, nonatomic) NSNumber* notified;
@property(retain, nonatomic) NSString* group_uuid;
@property(retain, nonatomic) NSNumber* group;
@property(retain, nonatomic) NSDate* endTime;
@property(retain, nonatomic) NSNumber* currentTime;
@property(retain, nonatomic) NSNumber* completed;
@property(retain, nonatomic) NSNumber* active;
+(id)tournamentWithDictionary:(id)dictionary;
+(id)tournamentWithUUID:(id)uuid;
-(BOOL)isLevelAvailable;
-(void)setAsCompleted;
-(id)leader;
-(id)orderedPlayers;
-(void)addPlayerWithDictionary:(id)dictionary;
-(BOOL)isCurrent;
-(BOOL)withoutSuper;
-(BOOL)isQualified;
-(id)description;
-(void)awakeFromFetch;
@end

