/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "CCSprite.h"

@class HSLabelSafeBMFont, NSString;

__attribute__((visibility("hidden")))
@interface TournamentHeader : CCSprite {
	HSLabelSafeBMFont* label;
	NSString* _title;
}
@property(retain, nonatomic) NSString* title;
+(id)headerWithTitle:(id)title;
-(void).cxx_destruct;
@end

