/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "HSGameStateProtocol.h"
#import "TrialGameControllerDelegate.h"
#import "HSTableViewDataSource.h"
#import "HSTableViewDelegate.h"
#import "HSMenuLayer.h"

@class NSMutableDictionary, CCMenu, HSTableView, SignPost, NSString, LoadingPopup, TournamentsClient;

__attribute__((visibility("hidden")))
@interface Tournaments : HSMenuLayer <HSGameStateProtocol, HSTableViewDataSource, HSTableViewDelegate, TrialGameControllerDelegate> {
	TournamentsClient* client;
	LoadingPopup* loading;
	HSTableView* tableView;
	BOOL updatingCurrent;
	SignPost* signPost;
	NSMutableDictionary* buttons;
	CCMenu* menuItems;
	BOOL triggerGameControllerOnNextVisit;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
+(id)scene;
-(void).cxx_destruct;
-(void)visit;
-(id)controllerItemForIndex:(unsigned)index;
-(id)scrollToAndReturn:(id)andReturn pos:(float)pos;
-(id)controllerItemConfig;
-(unsigned)controllerDefaultItem;
-(void)controllerCancel;
-(void)postFirstVisit;
-(void)postTransitionIn;
-(id)menuForUserAttention;
-(BOOL)canGrabUserAttention:(id)attention;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(int)numberOfSectionsInTableView:(id)tableView;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view viewForHeaderInSection:(int)section;
-(float)tableView:(id)view heightForHeaderInSection:(int)section;
-(float)tableView:(id)view heightForRowAtIndexPath:(id)indexPath;
-(void)tournamentsClientUpdateCompleted;
-(void)tournamentsClientSyncFailed;
-(void)tournamentsClientSyncCompleted;
-(void)cleanup;
-(void)reSync;
-(void)createMenu;
-(void)didBecomeActive;
-(void)onExit;
-(void)syncClient;
-(id)initWithMenu:(id)menu;
@end

