/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "HSAdjustedSprite.h"

@class NSMutableDictionary, LoadingPopup, HSMenu, Tournament;

__attribute__((visibility("hidden")))
@interface TournamentCompletedSign : HSAdjustedSprite {
	HSMenu* menu;
	Tournament* tournament;
	LoadingPopup* loading;
	NSMutableDictionary* buttons;
}
+(id)fakeCompletedPodium;
+(id)tournamentCompletedPodiumWithTournament:(id)tournament menu:(id)menu;
+(id)tournamentCompletedSignWithTournament:(id)tournament menu:(id)menu;
-(void).cxx_destruct;
-(void)cleanup;
-(id)simpleGroupForPlayerOutsideTop3:(id)playerOutsideTop3 animate:(BOOL)animate;
-(id)groupForPlayerOutsideTop3:(id)playerOutsideTop3 animate:(BOOL)animate;
-(id)groupForPlayer:(id)player simple:(BOOL)simple animate:(BOOL)animate;
-(void)setupFakeSign;
-(void)setupSign:(id)sign yOffset:(float)offset simple:(BOOL)simple animate:(BOOL)animate;
-(id)buttons;
@end

