/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "HSMenuLayer.h"
#import "TrialGameControllerDelegate.h"

@class TrialSession, Tournament, NSMutableArray, Wheely, TrialLayer;

__attribute__((visibility("hidden")))
@interface TournamentGoalDialogSelf : HSMenuLayer <TrialGameControllerDelegate> {
	TrialLayer* trialLayer;
	TrialSession* session;
	BOOL trialLayerFadedOut;
	Tournament* currentTournament;
	Wheely* yourHero;
	NSMutableArray* menuItemsArray;
}
+(id)layerWithMenu:(id)menu session:(id)session tournament:(id)tournament checkpoints:(id)checkpoints;
+(id)menuWithSession:(id)session tournament:(id)tournament checkpoints:(id)checkpoints;
-(void).cxx_destruct;
-(id)controllerItemForIndex:(unsigned)index;
-(id)controllerItemConfig;
-(unsigned)controllerDefaultItem;
-(void)controllerCancel;
-(void)postFirstVisit;
-(void)postTransitionIn;
-(void)cleanup;
-(void)setOpacity:(unsigned char)opacity;
-(void)onEnter;
-(void)onExit;
-(id)initWithMenu:(id)menu session:(id)session tournament:(id)tournament checkpoints:(id)checkpoints;
-(id)initWithMenu:(id)menu;
@end

