/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "HSMenuItem.h"

@class CCSprite, Wheely, TournamentPlayer, HSLabelSafeBMFont, InfoButton;

__attribute__((visibility("hidden")))
@interface TournamentScoreBoardSign : HSMenuItem {
	HSLabelSafeBMFont* nickLabel;
	HSLabelSafeBMFont* rankLabel;
	HSLabelSafeBMFont* timeLabel;
	CCNode* flag;
	Wheely* character;
	CCSprite* brightenOverlay;
	InfoButton* infoButton;
	CCSprite* photoFrame;
	CCSprite* photo;
	id infoBlock;
	TournamentPlayer* player_;
}
@property(retain, nonatomic) TournamentPlayer* player;
+(id)signWithPlayer:(id)player sprite:(id)sprite block:(id)block infoBlock:(id)block4;
+(id)slowerSignWithPlayer:(id)player block:(id)block infoBlock:(id)block3;
+(id)selfSignWithPlayer:(id)player block:(id)block infoBlock:(id)block3;
+(id)fasterSignWithPlayer:(id)player block:(id)block infoBlock:(id)block3;
-(void).cxx_destruct;
-(void)blur;
-(void)focus;
-(id)itemForTouch:(id)touch;
-(void)dealloc;
-(void)cleanup;
-(void)setupPhoto:(id)photo;
-(void)unselected;
-(void)selected;
-(void)setupSign:(id)sign sprite:(id)sprite;
@end

