/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "HSGameStateProtocol.h"
#import "TrialGameControllerDelegate.h"
#import "HSMenuLayer.h"

@class CCMenu, UIImage, NSDictionary, FBShare, HSMenuItem, NSString, LoadingPopup;

__attribute__((visibility("hidden")))
@interface TournamentSplash : HSMenuLayer <HSGameStateProtocol, TrialGameControllerDelegate> {
	HSMenuItem* continueButton;
	CCMenu* menuItems;
	LoadingPopup* loading;
	unsigned rank;
	FBShare* shareButton;
	UIImage* screenShot;
	BOOL grabScreen;
	NSString* shouldTriggerEventFor;
	NSDictionary* signButtons;
}
+(id)scene;
-(void).cxx_destruct;
-(id)controllerItemForIndex:(unsigned)index;
-(id)controllerItemConfig;
-(unsigned)controllerDefaultItem;
-(void)controllerCancel;
-(void)postFirstVisit;
-(void)postTransitionIn;
-(id)menuForUserAttention;
-(BOOL)canGrabUserAttention:(id)attention;
-(void)visit;
-(void)cleanup;
-(void)onEnter;
-(id)initWithMenu:(id)menu;
@end

