/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



@protocol TrialGameControllerDelegate
-(unsigned)controllerDefaultItem;
-(id)controllerItemForIndex:(unsigned)index;
-(id)controllerItemConfig;
-(void)controllerCancel;
@optional
-(int)controllerItemIndex:(int)index;
@end

