/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "TrialGameControllerDelegate.h"
#import "HSMenuLayer.h"

@class CCMenu, Wheely, CCSprite, HSAdjustedSprite;

__attribute__((visibility("hidden")))
@interface TutorialBreak : HSMenuLayer <TrialGameControllerDelegate> {
	CCMenu* menuItems;
	CCSprite* fingerLeftPressed;
	CCSprite* fingerRightPressed;
	CCSprite* fingerLeftUnpressed;
	CCSprite* fingerRightUnpressed;
	CCSprite* leftButton;
	CCSprite* rightButton;
	HSAdjustedSprite* dialog;
	Wheely* hero;
}
+(id)menuWithSession:(id)session;
+(id)layerWithMenu:(id)menu session:(id)session;
-(void).cxx_destruct;
-(id)controllerItemForIndex:(unsigned)index;
-(id)controllerItemConfig;
-(unsigned)controllerDefaultItem;
-(void)controllerCancel;
-(void)postFirstVisit;
-(void)postTransitionIn;
-(void)onEnter;
-(void)start;
-(void)both;
-(void)cleanup;
-(id)initWithMenu:(id)menu session:(id)session;
-(id)initWithMenu:(id)menu;
@end

