/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "TrialGameControllerDelegate.h"
#import "HSMenuLayer.h"
#import "Boom-Structs.h"

@class Wheely, CCSprite, BoostIndicator, CCMenu;

__attribute__((visibility("hidden")))
@interface TutorialBoost : HSMenuLayer <TrialGameControllerDelegate> {
	CCMenu* menuItems;
	BoostIndicator* boostIndicator;
	CCSprite* fingerUnpressed;
	CCSprite* fingerPressed;
	CCSprite* button;
	Wheely* hero;
	int animationStep;
	unsigned boostLevel;
}
+(BOOL)hasBeenPresented;
+(id)menuWithSession:(id)session;
+(id)layerWithMenu:(id)menu session:(id)session;
-(void).cxx_destruct;
-(id)controllerItemForIndex:(unsigned)index;
-(id)controllerItemConfig;
-(unsigned)controllerDefaultItem;
-(void)controllerCancel;
-(void)postFirstVisit;
-(void)cleanup;
-(void)animateBoost;
-(void)postTransitionIn;
-(void)onEnter;
-(id)initWithMenu:(id)menu session:(id)session;
-(id)initWithMenu:(id)menu;
@end

