/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "CCNode.h"
#import "CCRGBAProtocol.h"

@class NSMutableArray, NSString;

__attribute__((visibility("hidden")))
@interface WaterItemEffect : CCNode <CCRGBAProtocol> {
	float totalTime;
	float period;
	NSMutableArray* twirls;
	unsigned char opacity_;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
-(void).cxx_destruct;
-(ccColor3B)color;
-(void)setColor:(ccColor3B)color;
-(unsigned char)opacity;
-(void)setOpacity:(unsigned char)opacity;
-(void)cleanup;
-(void)update:(float)update;
-(id)init;
@end

