/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AFURLConnectionOperation.h"

@class NSHTTPURLResponse, NSRecursiveLock, NSError, NSObject, NSURLRequest;
@protocol OS_dispatch_queue;

__attribute__((visibility("hidden")))
@interface AFHTTPRequestOperation : AFURLConnectionOperation {
	NSError* _HTTPError;
	NSObject<OS_dispatch_queue>* _successCallbackQueue;
	NSObject<OS_dispatch_queue>* _failureCallbackQueue;
}
@property(assign, nonatomic) NSObject<OS_dispatch_queue>* failureCallbackQueue;
@property(assign, nonatomic) NSObject<OS_dispatch_queue>* successCallbackQueue;
@property(readonly, assign, nonatomic) BOOL hasAcceptableContentType;
@property(readonly, assign, nonatomic) BOOL hasAcceptableStatusCode;
@property(retain, nonatomic) NSRecursiveLock* lock;
@property(retain, nonatomic) NSError* HTTPError;
@property(retain, nonatomic) NSHTTPURLResponse* response;
@property(retain, nonatomic) NSURLRequest* request;
+(BOOL)canProcessRequest:(id)request;
+(void)addAcceptableContentTypes:(id)types;
+(id)acceptableContentTypes;
+(void)addAcceptableStatusCodes:(id)codes;
+(id)acceptableStatusCodes;
-(void).cxx_destruct;
-(void)setCompletionBlockWithSuccess:(id)success failure:(id)failure;
-(void)pause;
-(unsigned)responseStringEncoding;
-(id)error;
-(void)dealloc;
@end

