/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AFHTTPRequestOperation.h"

@class UIImage;

__attribute__((visibility("hidden")))
@interface AFImageRequestOperation : AFHTTPRequestOperation {
	BOOL _automaticallyInflatesResponseImage;
	UIImage* _responseImage;
	float _imageScale;
}
@property(assign, nonatomic) BOOL automaticallyInflatesResponseImage;
@property(assign, nonatomic) float imageScale;
@property(retain, nonatomic) UIImage* responseImage;
+(BOOL)canProcessRequest:(id)request;
+(id)acceptableContentTypes;
+(id)imageRequestOperationWithRequest:(id)request imageProcessingBlock:(id)block success:(id)success failure:(id)failure;
+(id)imageRequestOperationWithRequest:(id)request success:(id)success;
-(void).cxx_destruct;
-(void)setCompletionBlockWithSuccess:(id)success failure:(id)failure;
-(id)initWithRequest:(id)request;
@end

