/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "LHSprite.h"


__attribute__((visibility("hidden")))
@interface Buoyant : LHSprite {
	float lower;
	float upper;
	unsigned sides;
	float damping;
	float defaultAngle;
	float Object390;
	float dampingForce;
	float linearDamping;
	float waterLevel;
	float Object304;
	float time;
	BOOL active;
	BOOL inWater;
}
@property(assign, nonatomic) BOOL inWater;
-(bool)removeBodyFromWorld;
-(void)outOfWater;
-(void)sinkAndBounce:(float)bounce;
-(void)postUpdate:(float)update;
-(void)postInitialization;
-(void)cleanup;
@end

