/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "LHSprite.h"

@class HSLine;

__attribute__((visibility("hidden")))
@interface Cage : LHSprite {
	LHSprite* bottom;
	LHSprite* back;
	LHSprite* captive;
	LHSprite* hook;
	LHSprite* poffAnimation;
	b2Joint* leftHinge;
	BOOL triggered;
	BOOL running;
	BOOL poff;
	BOOL triggerPoff;
	b2DistanceJoint** ropeLinks;
	b2DistanceJoint* extraJoint;
	unsigned links;
	unsigned cageSteps;
	HSLine* ropeLine;
	float runningTime;
	float poffTime;
}
-(void).cxx_destruct;
-(void)setupTags;
-(void)setPosition:(CGPoint)position rotation:(float)rotation;
-(void)setRotation:(float)rotation;
-(void)setPosition:(CGPoint)position;
-(CGPoint)position;
-(void)postUpdate:(float)update;
-(void)update:(float)update;
-(void)pinkyNextAnimation;
-(void)poffDone;
-(void)updateRope:(float)rope;
-(void)triggerPoff;
-(void)triggerWithoutPoff;
-(void)trigger;
-(void)setOpacity:(unsigned char)opacity;
-(void)setRopeNode:(id)node;
-(void)postInitialization;
-(void)cleanup;
@end

