/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "CCActionInterval.h"
#import "NSCopying.h"


__attribute__((visibility("hidden")))
@interface CCActionCamera : CCActionInterval <NSCopying> {
	float centerXOrig_;
	float centerYOrig_;
	float centerZOrig_;
	float eyeXOrig_;
	float eyeYOrig_;
	float eyeZOrig_;
	float upXOrig_;
	float upYOrig_;
	float upZOrig_;
}
-(id)reverse;
-(void)startWithTarget:(id)target;
@end

