/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "NSCopying.h"
#import "CCActionInterval.h"


__attribute__((visibility("hidden")))
@interface CCBlink : CCActionInterval <NSCopying> {
	unsigned times_;
}
+(id)actionWithDuration:(float)duration blinks:(unsigned)blinks;
-(id)reverse;
-(void)update:(float)update;
-(id)copyWithZone:(NSZone*)zone;
-(id)initWithDuration:(float)duration blinks:(unsigned)blinks;
@end

