/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "CCActionInterval.h"
#import "Boom-Structs.h"

@class CCPointArray;

__attribute__((visibility("hidden")))
@interface CCCardinalSplineTo : CCActionInterval {
	CCPointArray* points_;
	float deltaT_;
	float tension_;
}
@property(retain, nonatomic) CCPointArray* points;
+(id)actionWithDuration:(float)duration points:(id)points tension:(float)tension;
-(id)reverse;
-(void)updatePosition:(CGPoint)position;
-(void)update:(float)update;
-(id)copyWithZone:(NSZone*)zone;
-(void)startWithTarget:(id)target;
-(void)dealloc;
-(id)initWithDuration:(float)duration points:(id)points tension:(float)tension;
@end

