/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "CCCallFunc.h"


__attribute__((visibility("hidden")))
@interface CCCallFuncO : CCCallFunc {
	id object_;
}
@property(retain, nonatomic) id object;
+(id)actionWithTarget:(id)target selector:(SEL)selector object:(id)object;
-(void)execute;
-(id)copyWithZone:(NSZone*)zone;
-(void)dealloc;
-(id)initWithTarget:(id)target selector:(SEL)selector object:(id)object;
@end

