/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "CCCallFuncN.h"


__attribute__((visibility("hidden")))
@interface CCCallFuncND : CCCallFuncN {
	void* data_;
	/*function-pointer*/ void* callbackMethod_;
}
@property(assign, nonatomic) /*function-pointer*/ void* callbackMethod;
+(id)actionWithTarget:(id)target selector:(SEL)selector data:(void*)data;
-(void)execute;
-(void)dealloc;
-(id)copyWithZone:(NSZone*)zone;
-(id)initWithTarget:(id)target selector:(SEL)selector data:(void*)data;
@end

