/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "CCActionEase.h"
#import "NSCopying.h"


__attribute__((visibility("hidden")))
@interface CCEaseElastic : CCActionEase <NSCopying> {
	float period_;
}
@property(assign, nonatomic) float period;
+(id)actionWithAction:(id)action period:(float)period;
+(id)actionWithAction:(id)action;
-(id)reverse;
-(id)copyWithZone:(NSZone*)zone;
-(id)initWithAction:(id)action period:(float)period;
-(id)initWithAction:(id)action;
@end

