/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "CCActionEase.h"
#import "NSCopying.h"


__attribute__((visibility("hidden")))
@interface CCEaseRateAction : CCActionEase <NSCopying> {
	float rate;
}
@property(assign, nonatomic) float rate;
+(id)actionWithAction:(id)action rate:(float)rate;
-(id)reverse;
-(void)dealloc;
-(id)copyWithZone:(NSZone*)zone;
-(id)initWithAction:(id)action rate:(float)rate;
@end

