/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "CCTiledGrid3DAction.h"
#import "Boom-Structs.h"


__attribute__((visibility("hidden")))
@interface CCFadeOutTRTiles : CCTiledGrid3DAction {
}
-(void)update:(float)update;
-(void)transformTile:(ccGridSize)tile distance:(float)distance;
-(void)turnOffTile:(ccGridSize)tile;
-(void)turnOnTile:(ccGridSize)tile;
-(float)testFunc:(ccGridSize)func time:(float)time;
@end

