/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "CCFadeOutTRTiles.h"


__attribute__((visibility("hidden")))
@interface CCFadeOutBLTiles : CCFadeOutTRTiles {
}
-(float)testFunc:(ccGridSize)func time:(float)time;
@end

