/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "CCAction.h"
#import "NSCopying.h"


__attribute__((visibility("hidden")))
@interface CCFiniteTimeAction : CCAction <NSCopying> {
	float duration_;
}
@property(assign, nonatomic) float duration;
-(id)reverse;
@end

