/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface CCGLProgram : XXUnknownSuperclass {
	hashUniformEntry* hashForUniforms_;
	unsigned program_;
	unsigned vertShader_;
	unsigned fragShader_;
	int uniforms_[2];
}
-(void)dealloc;
-(void)setUniformForModelViewProjectionMatrix;
-(void)setUniformLocation:(unsigned)location withMatrix4fv:(void*)matrix4fv count:(unsigned)count;
-(void)setUniformLocation:(unsigned)location with4fv:(void*)a4fv count:(unsigned)count;
-(void)setUniformLocation:(unsigned)location with3fv:(float*)a3fv count:(unsigned)count;
-(void)setUniformLocation:(unsigned)location with2fv:(float*)a2fv count:(unsigned)count;
-(void)setUniformLocation:(unsigned)location withF1:(float)f1 f2:(float)a2 f3:(float)a3 f4:(float)a4;
-(void)setUniformLocation:(unsigned)location withF1:(float)f1 f2:(float)a2 f3:(float)a3;
-(void)setUniformLocation:(unsigned)location withF1:(float)f1 f2:(float)a2;
-(void)setUniformLocation:(unsigned)location withF1:(float)f1;
-(void)setUniformLocation:(unsigned)location withI1:(int)i1;
-(BOOL)updateUniformLocation:(unsigned)location withData:(void*)data sizeOfData:(unsigned)data3;
-(id)programLog;
-(id)fragmentShaderLog;
-(id)vertexShaderLog;
-(id)logForOpenGLObject:(unsigned)openGLObject infoCallback:(/*function-pointer*/ void*)callback logFunc:(/*function-pointer*/ void*)func;
-(void)use;
-(BOOL)link;
-(void)updateUniforms;
-(void)addAttribute:(id)attribute index:(unsigned)index;
-(BOOL)compileShader:(unsigned*)shader type:(unsigned)type byteArray:(const char*)array;
-(id)description;
-(id)initWithVertexShaderFilename:(id)vertexShaderFilename fragmentShaderFilename:(id)filename;
-(id)initWithVertexShaderByteArray:(const char*)vertexShaderByteArray fragmentShaderByteArray:(const char*)array;
@end

