/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface CCGrabber : XXUnknownSuperclass {
	unsigned fbo_;
	int oldFBO_;
	float oldClearColor_[4];
}
-(void)dealloc;
-(void)afterRender:(id)render;
-(void)beforeRender:(id)render;
-(void)grab:(id)grab;
-(id)init;
@end

