/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "CCActionInterval.h"
#import "Boom-Structs.h"


__attribute__((visibility("hidden")))
@interface CCGridAction : CCActionInterval {
	ccGridSize gridSize_;
}
@property(assign, nonatomic) ccGridSize gridSize;
+(id)actionWithSize:(ccGridSize)size duration:(float)duration;
-(id)copyWithZone:(NSZone*)zone;
-(id)reverse;
-(id)grid;
-(void)startWithTarget:(id)target;
-(id)initWithSize:(ccGridSize)size duration:(float)duration;
@end

