/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSCopying.h"
#import "Boom-Structs.h"
#import "CCJumpBy.h"


__attribute__((visibility("hidden")))
@interface CCJumpTo : CCJumpBy <NSCopying> {
}
-(void)startWithTarget:(id)target;
@end

