/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "CCStandardTouchDelegate.h"
#import "CCTargetedTouchDelegate.h"
#import "CCNode.h"
#import "UIAccelerometerDelegate.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface CCLayer : CCNode <UIAccelerometerDelegate, CCStandardTouchDelegate, CCTargetedTouchDelegate> {
	BOOL isTouchEnabled_;
	BOOL isAccelerometerEnabled_;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) NSUInteger hash;
@property(assign, nonatomic) BOOL isAccelerometerEnabled;
@property(assign, nonatomic) BOOL isTouchEnabled;
-(BOOL)ccTouchBegan:(id)began withEvent:(id)event;
-(void)onExit;
-(void)onEnterTransitionDidFinish;
-(void)onEnter;
-(void)registerWithTouchDispatcher;
-(id)init;
@end

