/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "CCAtlasNode.h"
#import "CCLabelProtocol.h"
#import "Boom-Structs.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface CCLabelAtlas : CCAtlasNode <CCLabelProtocol> {
	NSString* string_;
	unsigned mapStartChar_;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
+(id)labelWithString:(id)string fntFile:(id)file;
+(id)labelWithString:(id)string charMapFile:(id)file itemWidth:(unsigned)width itemHeight:(unsigned)height startCharMap:(unsigned)map;
-(id)string;
-(void)setString:(id)string;
-(void)updateAtlasValues;
-(void)dealloc;
-(id)initWithString:(id)string charMapFile:(id)file itemWidth:(unsigned)width itemHeight:(unsigned)height startCharMap:(unsigned)map;
-(id)initWithString:(id)string fntFile:(id)file;
@end

