/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "CCLayer.h"
#import "CCRGBAProtocol.h"
#import "CCBlendProtocol.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface CCLayerColor : CCLayer <CCRGBAProtocol, CCBlendProtocol> {
	unsigned char opacity_;
	ccColor3B color_;
	ccVertex2F squareVertices_[4];
	ccColor4F squareColors_[4];
	ccBlendFunc blendFunc_;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) ccBlendFunc blendFunc;
@property(readonly, assign, nonatomic) ccColor3B color;
@property(readonly, assign, nonatomic) unsigned char opacity;
+(id)layerWithColor:(ccColor4B)color;
+(id)layerWithColor:(ccColor4B)color width:(float)width height:(float)height;
-(void)setOpacity:(unsigned char)opacity;
-(void)setColor:(ccColor3B)color;
-(void)draw;
-(void)updateColor;
-(void)changeHeight:(float)height;
-(void)changeWidth:(float)width;
-(void)changeWidth:(float)width height:(float)height;
-(void)setContentSize:(CGSize)size;
-(id)initWithColor:(ccColor4B)color;
-(id)initWithColor:(ccColor4B)color width:(float)width height:(float)height;
-(id)init;
@end

