/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "CCRGBAProtocol.h"
#import "Boom-Structs.h"
#import "CCMenuItem.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface CCMenuItemSprite : CCMenuItem <CCRGBAProtocol> {
	CCNode<CCRGBAProtocol>* normalImage_;
	CCNode<CCRGBAProtocol>* selectedImage_;
	CCNode<CCRGBAProtocol>* disabledImage_;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) NSUInteger hash;
@property(assign, nonatomic) CCNode<CCRGBAProtocol>* disabledImage;
@property(assign, nonatomic) CCNode<CCRGBAProtocol>* selectedImage;
@property(assign, nonatomic) CCNode<CCRGBAProtocol>* normalImage;
+(id)itemWithNormalSprite:(id)normalSprite selectedSprite:(id)sprite disabledSprite:(id)sprite3 block:(id)block;
+(id)itemWithNormalSprite:(id)normalSprite selectedSprite:(id)sprite block:(id)block;
+(id)itemWithNormalSprite:(id)normalSprite selectedSprite:(id)sprite disabledSprite:(id)sprite3 target:(id)target selector:(SEL)selector;
+(id)itemWithNormalSprite:(id)normalSprite selectedSprite:(id)sprite target:(id)target selector:(SEL)selector;
+(id)itemWithNormalSprite:(id)normalSprite selectedSprite:(id)sprite;
+(id)itemFromNormalSprite:(id)normalSprite selectedSprite:(id)sprite disabledSprite:(id)sprite3 block:(id)block;
+(id)itemFromNormalSprite:(id)normalSprite selectedSprite:(id)sprite block:(id)block;
+(id)itemFromNormalSprite:(id)normalSprite selectedSprite:(id)sprite disabledSprite:(id)sprite3 target:(id)target selector:(SEL)selector;
+(id)itemFromNormalSprite:(id)normalSprite selectedSprite:(id)sprite target:(id)target selector:(SEL)selector;
+(id)itemFromNormalSprite:(id)normalSprite selectedSprite:(id)sprite;
-(void)updateImagesVisibility;
-(void)setIsEnabled:(BOOL)enabled;
-(void)unselected;
-(void)selected;
-(ccColor3B)color;
-(unsigned char)opacity;
-(void)setColor:(ccColor3B)color;
-(void)setOpacity:(unsigned char)opacity;
-(id)initWithNormalSprite:(id)normalSprite selectedSprite:(id)sprite disabledSprite:(id)sprite3 block:(id)block;
-(id)initWithNormalSprite:(id)normalSprite selectedSprite:(id)sprite disabledSprite:(id)sprite3 target:(id)target selector:(SEL)selector;
-(id)initFromNormalSprite:(id)normalSprite selectedSprite:(id)sprite disabledSprite:(id)sprite3 block:(id)block;
-(id)initFromNormalSprite:(id)normalSprite selectedSprite:(id)sprite disabledSprite:(id)sprite3 target:(id)target selector:(SEL)selector;
@end

