/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "CCMenu.h"


__attribute__((visibility("hidden")))
@interface CCMenuAdvanced : CCMenu {
	int priority_;
	int selectedItemNumber_;
	CGRect boundaryRect_;
	float minimumTouchLengthToSlide_;
	float curTouchLength_;
	BOOL isDisabled_;
}
@property(assign) BOOL isDisabled;
@property(assign) int priority;
@property(assign) float minimumTouchLengthToSlide;
@property(assign) CGRect boundaryRect;
-(void)ccTouchMoved:(id)moved withEvent:(id)event;
-(void)ccTouchCancelled:(id)cancelled withEvent:(id)event;
-(void)ccTouchEnded:(id)ended withEvent:(id)event;
-(BOOL)ccTouchBegan:(id)began withEvent:(id)event;
-(BOOL)isTouchForMe:(id)me;
-(void)fixPosition;
-(void)alignItemsVerticallyWithPadding:(float)padding;
-(void)alignItemsHorizontallyWithPadding:(float)padding;
-(void)alignItemsHorizontallyWithPadding:(float)padding leftToRight:(BOOL)right;
-(void)alignItemsVerticallyWithPadding:(float)padding bottomToTop:(BOOL)top;
-(void)cancelSelectedItem;
-(void)activateSelectedItem;
-(void)selectPrevMenuItem;
-(void)selectNextMenuItem;
-(void)registerWithTouchDispatcher;
-(int)keyboardDelegatePriority;
-(int)mouseDelegatePriority;
-(void)dealloc;
-(id)initWithItems:(id)items vaList:(void*)list;
@end

