/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "CCNode.h"
#import "CCRGBAProtocol.h"
#import "CCTextureProtocol.h"
#import "Boom-Structs.h"

@class NSString, CCTexture2D;

__attribute__((visibility("hidden")))
@interface CCMotionStreak : CCNode <CCTextureProtocol, CCRGBAProtocol> {
	CCTexture2D* texture_;
	CGPoint positionR_;
	ccColor3B color_;
	ccBlendFunc blendFunc_;
	float stroke_;
	float fadeDelta_;
	float minSeg_;
	unsigned maxPoints_;
	unsigned nuPoints_;
	unsigned previousNuPoints_;
	CGPoint* pointVertexes_;
	float* pointState_;
	ccVertex2F* vertices_;
	char* colorPointer_;
	ccTex2F* texCoords_;
	BOOL fastMode_;
	BOOL startingPositionInitialized_;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) CCTexture2D* texture;
@property(assign, nonatomic, getter=isFastMode) BOOL fastMode;
@property(assign, nonatomic) ccBlendFunc blendFunc;
+(id)streakWithFade:(float)fade minSeg:(float)seg width:(float)width color:(ccColor3B)color texture:(id)texture;
+(id)streakWithFade:(float)fade minSeg:(float)seg width:(float)width color:(ccColor3B)color textureFilename:(id)filename;
-(void)dealloc;
-(void)draw;
-(void)reset;
-(void)update:(float)update;
-(unsigned char)opacity;
-(void)setOpacity:(unsigned char)opacity;
-(ccColor3B)color;
-(void)setColor:(ccColor3B)color;
-(void)tintWithColor:(ccColor3B)color;
-(void)setPosition:(CGPoint)position;
-(id)initWithFade:(float)fade minSeg:(float)seg width:(float)width color:(ccColor3B)color texture:(id)texture;
-(id)initWithFade:(float)fade minSeg:(float)seg width:(float)width color:(ccColor3B)color textureFilename:(id)filename;
@end

