/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "CCMoveTo.h"
#import "NSCopying.h"


__attribute__((visibility("hidden")))
@interface CCMoveBy : CCMoveTo <NSCopying> {
}
+(id)actionWithDuration:(float)duration position:(CGPoint)position;
-(id)reverse;
-(void)startWithTarget:(id)target;
-(id)copyWithZone:(NSZone*)zone;
-(id)initWithDuration:(float)duration position:(CGPoint)position;
@end

