/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "CCParticleSystem.h"


__attribute__((visibility("hidden")))
@interface CCParticleSystemQuad : CCParticleSystem {
	ccV3F_C4B_T2F_Quad* quads_;
	unsigned short* indices_;
	unsigned VAOname_;
	unsigned buffersVBO_[2];
}
-(void)setBatchNode:(id)node;
-(void)draw;
-(void)postStep;
-(void)updateQuadWithParticle:(sCCParticle*)particle newPosition:(CGPoint)position;
-(void)initIndices;
-(void)setDisplayFrame:(id)frame;
-(void)setTexture:(id)texture;
-(void)setTexture:(id)texture withRect:(CGRect)rect;
-(void)initTexCoordsWithRect:(CGRect)rect;
-(void)dealloc;
-(void)initVAO;
-(void)setTotalParticles:(unsigned)particles;
-(BOOL)allocMemory;
-(id)initWithTotalParticles:(unsigned)totalParticles;
@end

