/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableDictionary;

__attribute__((visibility("hidden")))
@interface CCShaderCache : XXUnknownSuperclass {
	NSMutableDictionary* programs_;
}
+(void)purgeSharedTextureCache;
+(id)alloc;
+(void)purgeSharedShaderCache;
+(id)sharedShaderCache;
-(void)addProgram:(id)program forKey:(id)key;
-(id)programForKey:(id)key;
-(void)loadDefaultShaders;
-(id)init;
-(void)dealloc;
@end

