/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "CCAction.h"
#import "Boom-Structs.h"
#import "NSCopying.h"

@class CCActionInterval;

__attribute__((visibility("hidden")))
@interface CCSpeed : CCAction <NSCopying> {
	CCActionInterval* innerAction_;
	float speed_;
}
@property(retain, nonatomic) CCActionInterval* innerAction;
@property(assign, nonatomic) float speed;
+(id)actionWithAction:(id)action speed:(float)speed;
-(id)reverse;
-(BOOL)isDone;
-(void)step:(float)step;
-(void)stop;
-(void)startWithTarget:(id)target;
-(void)dealloc;
-(id)copyWithZone:(NSZone*)zone;
-(id)initWithAction:(id)action speed:(float)speed;
@end

