/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol CCStandardTouchDelegate <NSObject>
@optional
-(void)ccTouchesCancelled:(id)cancelled withEvent:(id)event;
-(void)ccTouchesEnded:(id)ended withEvent:(id)event;
-(void)ccTouchesMoved:(id)moved withEvent:(id)event;
-(void)ccTouchesBegan:(id)began withEvent:(id)event;
@end

