/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "CCTouchHandler.h"


__attribute__((visibility("hidden")))
@interface CCStandardTouchHandler : CCTouchHandler {
}
-(id)initWithDelegate:(id)delegate priority:(int)priority;
@end

