/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class CCGLProgram;

__attribute__((visibility("hidden")))
@interface CCTexture2D : XXUnknownSuperclass {
	unsigned name_;
	CGSize size_;
	unsigned width_;
	unsigned height_;
	int format_;
	float maxS_;
	float maxT_;
	BOOL hasPremultipliedAlpha_;
	BOOL hasMipmaps_;
	int resolutionType_;
	CCGLProgram* shaderProgram_;
	BOOL stretchTexels;
}
@property(assign, nonatomic) int resolutionType;
@property(assign, nonatomic) BOOL stretchTexels;
@property(retain, nonatomic) CCGLProgram* shaderProgram;
@property(readonly, assign, nonatomic) BOOL hasPremultipliedAlpha;
@property(assign, nonatomic) float maxT;
@property(assign, nonatomic) float maxS;
@property(readonly, assign, nonatomic) CGSize contentSizeInPixels;
@property(readonly, assign, nonatomic) unsigned name;
@property(readonly, assign, nonatomic) unsigned pixelsHigh;
@property(readonly, assign, nonatomic) unsigned pixelsWide;
@property(readonly, assign, nonatomic) int pixelFormat;
+(void)PVRImagesHavePremultipliedAlpha:(BOOL)alpha;
+(unsigned)bitsPerPixelForFormat:(int)format;
+(int)defaultAlphaPixelFormat;
+(void)setDefaultAlphaPixelFormat:(int)format;
-(CGSize)contentSize;
-(id)description;
-(void)dealloc;
-(void*)keepData:(void*)data length:(unsigned)length;
-(void)releaseData:(void*)data;
-(id)initWithData:(const void*)data pixelFormat:(int)format pixelsWide:(unsigned)wide pixelsHigh:(unsigned)high contentSize:(CGSize)size;
-(id)initWithString:(id)string dimensions:(CGSize)dimensions alignment:(int)alignment fontName:(id)name fontSize:(float)size;
-(id)initWithString:(id)string dimensions:(CGSize)dimensions alignment:(int)alignment lineBreakMode:(int)mode fontName:(id)name fontSize:(float)size;
-(id)initWithCGImage:(CGImageRef)cgimage resolutionType:(int)type;
-(id)initWithString:(id)string dimensions:(CGSize)dimensions hAlignment:(int)alignment vAlignment:(int)alignment4 lineBreakMode:(int)mode fontName:(id)name fontSize:(float)size;
-(id)initWithString:(id)string dimensions:(CGSize)dimensions hAlignment:(int)alignment vAlignment:(int)alignment4 fontName:(id)name fontSize:(float)size;
-(id)initWithString:(id)string fontName:(id)name fontSize:(float)size;
-(id)initWithString:(id)string dimensions:(CGSize)dimensions hAlignment:(int)alignment vAlignment:(int)alignment4 lineBreakMode:(int)mode font:(id)font;
-(id)initWithString:(id)string fontDef:(id)def;
-(id)initWithPVRFile:(id)pvrfile;
-(void)drawInRect:(CGRect)rect;
-(void)drawAtPoint:(CGPoint)point;
-(void)setAntiAliasTexParameters;
-(void)setAliasTexParameters;
-(void)setTexParameters:(ccTexParams*)parameters;
-(void)generateMipmap;
-(id)stringForFormat;
-(unsigned)bitsPerPixelForFormat;
-(void)setMipMapTexParameters;
@end

