/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "CCGridBase.h"


__attribute__((visibility("hidden")))
@interface CCTiledGrid3D : CCGridBase {
	void* texCoordinates;
	void* vertices;
	void* originalVertices;
	unsigned short* indices;
}
-(void)reuse;
-(ccQuad3)tile:(ccGridSize)tile;
-(ccQuad3)originalTile:(ccGridSize)tile;
-(void)setTile:(ccGridSize)tile coords:(ccQuad3)coords;
-(void)calculateVertexPoints;
-(void)blit;
-(void)dealloc;
@end

