/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "CCAtlasNode.h"

@class NSMutableDictionary;

__attribute__((visibility("hidden")))
@interface CCTileMapAtlas : CCAtlasNode {
	sImageTGA* tgaInfo;
	NSMutableDictionary* posToAtlasIndex;
	int itemsToRender;
}
@property(readonly, assign, nonatomic) sImageTGA* tgaInfo;
+(id)tileMapAtlasWithTileFile:(id)tileFile mapFile:(id)file tileWidth:(int)width tileHeight:(int)height;
-(void)updateAtlasValues;
-(void)updateAtlasValueAt:(ccGridSize)at withValue:(ccColor3B)value withIndex:(unsigned)index;
-(ccColor3B)tileAt:(ccGridSize)at;
-(void)setTile:(ccColor3B)tile at:(ccGridSize)at;
-(void)loadTGAfile:(id)afile;
-(void)calculateItemsToRender;
-(void)releaseMap;
-(void)dealloc;
-(id)initWithTileFile:(id)tileFile mapFile:(id)file tileWidth:(int)width tileHeight:(int)height;
@end

