/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "CCSpriteBatchNode.h"

@class CCTMXTilesetInfo, NSMutableArray, CCSprite, NSString;

__attribute__((visibility("hidden")))
@interface CCTMXLayer : CCSpriteBatchNode {
	CCTMXTilesetInfo* tileset_;
	NSString* layerName_;
	CGSize layerSize_;
	CGSize mapTileSize_;
	unsigned* tiles_;
	unsigned layerOrientation_;
	NSMutableArray* properties_;
	unsigned char opacity_;
	unsigned minGID_;
	unsigned maxGID_;
	int vertexZvalue_;
	BOOL useAutomaticVertexZ_;
	CCSprite* reusedTile_;
	ccArray* atlasIndexArray_;
}
@property(retain, nonatomic) NSMutableArray* properties;
@property(assign, nonatomic) unsigned layerOrientation;
@property(retain, nonatomic) CCTMXTilesetInfo* tileset;
@property(assign, nonatomic) unsigned* tiles;
@property(assign, nonatomic) CGSize mapTileSize;
@property(assign, nonatomic) CGSize layerSize;
@property(retain, nonatomic) NSString* layerName;
+(id)layerWithTilesetInfo:(id)tilesetInfo layerInfo:(id)info mapInfo:(id)info3;
-(int)vertexZForPos:(CGPoint)pos;
-(CGPoint)positionForHexAt:(CGPoint)at;
-(CGPoint)positionForIsoAt:(CGPoint)at;
-(CGPoint)positionForOrthoAt:(CGPoint)at;
-(CGPoint)positionAt:(CGPoint)at;
-(CGPoint)calculateLayerOffset:(CGPoint)offset;
-(void)removeTileAt:(CGPoint)at;
-(void)removeChild:(id)child cleanup:(BOOL)cleanup;
-(void)addChild:(id)child z:(int)z tag:(int)tag;
-(void)setTileGID:(unsigned)gid at:(CGPoint)at withFlags:(int)flags;
-(void)setTileGID:(unsigned)gid at:(CGPoint)at;
-(unsigned)atlasIndexForNewZ:(unsigned)newZ;
-(unsigned)atlasIndexForExistantZ:(unsigned)existantZ;
-(id)appendTileForGID:(unsigned)gid at:(CGPoint)at;
-(id)updateTileForGID:(unsigned)gid at:(CGPoint)at;
-(id)insertTileForGID:(unsigned)gid at:(CGPoint)at;
-(void)setupTileSprite:(id)sprite position:(CGPoint)position withGID:(unsigned)gid;
-(unsigned)tileGIDAt:(CGPoint)at withFlags:(int*)flags;
-(unsigned)tileGIDAt:(CGPoint)at;
-(id)tileAt:(CGPoint)at;
-(void)parseInternalProperties;
-(id)propertyNamed:(id)named;
-(void)setupTiles;
-(id)reusedTileWithRect:(CGRect)rect;
-(void)releaseMap;
-(void)dealloc;
-(id)initWithTilesetInfo:(id)tilesetInfo layerInfo:(id)info mapInfo:(id)info3;
@end

