/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface CCTouchHandler : XXUnknownSuperclass {
	id delegate;
	int priority;
	int enabledSelectors_;
}
@property(assign, nonatomic) int enabledSelectors;
@property(assign, nonatomic) int priority;
@property(retain, nonatomic) id delegate;
+(id)handlerWithDelegate:(id)delegate priority:(int)priority;
-(void)dealloc;
-(id)initWithDelegate:(id)delegate priority:(int)priority;
@end

