/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "CCTouchDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "Boom-Structs.h"

@class NSMutableArray, NSString;

__attribute__((visibility("hidden")))
@interface CCTouchDispatcher : XXUnknownSuperclass <CCTouchDelegate> {
	NSMutableArray* targetedHandlers;
	NSMutableArray* standardHandlers;
	BOOL locked;
	BOOL toAdd;
	BOOL toRemove;
	NSMutableArray* handlersToAdd;
	NSMutableArray* handlersToRemove;
	BOOL toQuit;
	BOOL dispatchEvents;
	ccTouchHandlerHelperData handlerHelperData[4];
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) BOOL dispatchEvents;
+(id)sharedDispatcher;
-(void)touchesCancelled:(id)cancelled withEvent:(id)event;
-(void)touchesEnded:(id)ended withEvent:(id)event;
-(void)touchesMoved:(id)moved withEvent:(id)event;
-(void)touchesBegan:(id)began withEvent:(id)event;
-(void)touches:(id)touches withEvent:(id)event withTouchType:(unsigned)touchType;
-(void)setPriority:(int)priority forDelegate:(id)delegate;
-(void)rearrangeHandlers:(id)handlers;
-(id)findHandler:(id)handler;
-(void)removeAllDelegates;
-(void)forceRemoveAllDelegates;
-(void)removeDelegate:(id)delegate;
-(void)forceRemoveDelegate:(id)delegate;
-(void)addTargetedDelegate:(id)delegate priority:(int)priority swallowsTouches:(BOOL)touches;
-(void)addStandardDelegate:(id)delegate priority:(int)priority;
-(void)forceAddHandler:(id)handler array:(id)array;
-(void)dealloc;
-(id)init;
-(id)targetedHandlers;
@end

