/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "CCTransitionProgress.h"


__attribute__((visibility("hidden")))
@interface CCTransitionProgressInOut : CCTransitionProgress {
}
-(id)progressTimerNodeWithRenderTexture:(id)renderTexture;
-(void)setupTransition;
-(void)sceneOrder;
@end

