/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "CCGrid3DAction.h"


__attribute__((visibility("hidden")))
@interface CCTwirl : CCGrid3DAction {
	CGPoint position_;
	int twirls_;
	float amplitude_;
	float amplitudeRate_;
}
@property(assign, nonatomic) float amplitudeRate;
@property(assign, nonatomic) float amplitude;
@property(assign, nonatomic) CGPoint position;
+(id)actionWithPosition:(CGPoint)position twirls:(int)twirls amplitude:(float)amplitude grid:(ccGridSize)grid duration:(float)duration;
-(id)copyWithZone:(NSZone*)zone;
-(void)update:(float)update;
-(id)initWithPosition:(CGPoint)position twirls:(int)twirls amplitude:(float)amplitude grid:(ccGridSize)grid duration:(float)duration;
@end

