/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class CDSoundEngine, NSArray;

__attribute__((visibility("hidden")))
@interface CDAsynchBufferLoader : XXUnknownSuperclass {
	NSArray* _loadRequests;
	CDSoundEngine* _soundEngine;
}
-(void)dealloc;
-(void)main;
-(id)init:(id)init soundEngine:(id)engine;
@end

