/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "CDAudioInterruptProtocol.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableArray, NSString;

__attribute__((visibility("hidden")))
@interface CDAudioInterruptTargetGroup : XXUnknownSuperclass <CDAudioInterruptProtocol> {
	BOOL mute_;
	BOOL enabled_;
	NSMutableArray* children_;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
-(void)setEnabled:(BOOL)enabled;
-(BOOL)enabled;
-(void)setMute:(BOOL)mute;
-(BOOL)mute;
-(void)removeAudioInterruptTarget:(id)target;
-(void)addAudioInterruptTarget:(id)target;
-(id)init;
@end

