/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "CDAudioInterruptProtocol.h"
#import "CDLongAudioSourceDelegate.h"
#import "AVAudioSessionDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class CDSoundEngine, NSMutableArray, CDLongAudioSource, NSString;

__attribute__((visibility("hidden")))
@interface CDAudioManager : XXUnknownSuperclass <CDLongAudioSourceDelegate, CDAudioInterruptProtocol, AVAudioSessionDelegate> {
	CDSoundEngine* soundEngine;
	CDLongAudioSource* backgroundMusic;
	NSMutableArray* audioSourceChannels;
	NSString* _audioSessionCategory;
	BOOL _audioWasPlayingAtStartup;
	int _mode;
	SEL backgroundMusicCompletionSelector;
	id backgroundMusicCompletionListener;
	BOOL willPlayBackgroundMusic;
	BOOL _mute;
	BOOL _resigned;
	BOOL _interrupted;
	BOOL _audioSessionActive;
	BOOL enabled_;
	BOOL _isObservingAppEvents;
	int _resignBehavior;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(readonly, assign) BOOL willPlayBackgroundMusic;
@property(readonly, assign) CDLongAudioSource* backgroundMusic;
@property(readonly, assign) CDSoundEngine* soundEngine;
+(void)end;
+(void)configure:(int)configure;
+(id)alloc;
+(void)initAsynchronously:(int)asynchronously;
+(int)sharedManagerState;
+(id)sharedManager;
-(void)audioSessionResumed;
-(void)audioSessionInterrupted;
-(void)endInterruption;
-(void)beginInterruption;
-(void)cdAudioSourceDidFinishPlaying:(id)cdAudioSource;
-(void)applicationWillTerminate:(id)application;
-(void)applicationDidBecomeActive:(id)application;
-(void)applicationDidBecomeActive;
-(void)applicationWillResignActive:(id)application;
-(void)applicationWillResignActive;
-(void)setResignBehavior:(int)behavior autoHandle:(BOOL)handle;
-(void)setBackgroundMusicCompletionListener:(id)listener selector:(SEL)selector;
-(void)rewindBackgroundMusic;
-(void)resumeBackgroundMusic;
-(void)pauseBackgroundMusic;
-(void)stopBackgroundMusic;
-(void)playBackgroundMusic:(id)music loop:(BOOL)loop;
-(void)preloadBackgroundMusic:(id)music;
-(void)setEnabled:(BOOL)enabled;
-(BOOL)enabled;
-(void)setMute:(BOOL)mute;
-(BOOL)mute;
-(BOOL)isDeviceMuted;
-(BOOL)isBackgroundMusicPlaying;
-(id)audioSourceLoad:(id)load channel:(int)channel;
-(id)audioSourceForChannel:(int)channel;
-(void)dealloc;
-(void)interruption:(id)interruption;
-(id)init:(int)init;
-(void)badAlContextHandler;
-(void)setMode:(int)mode;
-(BOOL)isOtherAudioPlaying;
-(BOOL)audioSessionSetCategory:(id)category;
-(BOOL)audioSessionSetActive:(BOOL)active;
@end

