/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AVAudioPlayerDelegate.h"
#import "CDAudioInterruptProtocol.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class AVAudioPlayer, NSString;
@protocol CDLongAudioSourceDelegate;

__attribute__((visibility("hidden")))
@interface CDLongAudioSource : XXUnknownSuperclass <AVAudioPlayerDelegate, CDAudioInterruptProtocol> {
	AVAudioPlayer* audioSourcePlayer;
	NSString* audioSourceFilePath;
	int numberOfLoops;
	float volume;
	id<CDLongAudioSourceDelegate> delegate;
	BOOL mute;
	BOOL enabled_;
	BOOL backgroundMusic;
	BOOL systemPaused;
	double systemPauseLocation;
	int state;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) BOOL backgroundMusic;
@property(assign) id<CDLongAudioSourceDelegate> delegate;
@property(assign, nonatomic) float volume;
@property(assign, nonatomic) int numberOfLoops;
@property(readonly, assign) NSString* audioSourceFilePath;
@property(readonly, assign) AVAudioPlayer* audioSourcePlayer;
-(void)audioPlayerEndInterruption:(id)interruption;
-(void)audioPlayerBeginInterruption:(id)interruption;
-(void)audioPlayerDidFinishPlaying:(id)audioPlayer successfully:(BOOL)successfully;
-(void)setEnabled:(BOOL)enabled;
-(BOOL)enabled;
-(void)setMute:(BOOL)mute;
-(BOOL)mute;
-(BOOL)isPlaying;
-(void)resume;
-(void)rewind;
-(void)pause;
-(void)stop;
-(void)play;
-(void)load:(id)load;
-(void)dealloc;
-(id)init;
@end

