/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "CCActionInterval.h"

@class CDPropertyModifier;

__attribute__((visibility("hidden")))
@interface CDXPropertyModifierAction : CCActionInterval {
	CDPropertyModifier* modifier;
	float lastSetValue;
}
+(void)fadeBackgroundMusic:(float)music finalVolume:(float)volume curveType:(int)type shouldStop:(BOOL)stop;
+(void)fadeSoundEffect:(float)effect finalVolume:(float)volume curveType:(int)type shouldStop:(BOOL)stop effect:(id)effect5;
+(void)fadeSoundEffects:(float)effects finalVolume:(float)volume curveType:(int)type shouldStop:(BOOL)stop;
+(id)actionWithDuration:(float)duration modifier:(id)modifier;
-(void)update:(float)update;
-(id)copyWithZone:(NSZone*)zone;
-(void)dealloc;
-(void)startWithTarget:(id)target;
-(id)initWithDuration:(float)duration modifier:(id)modifier;
@end

