/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableDictionary, AFHTTPClient, NSMutableArray, NSMutableSet, NSDate, NSString;

__attribute__((visibility("hidden")))
@interface ChallengeClient : XXUnknownSuperclass {
	BOOL isEnabled;
	BOOL isSyncing;
	AFHTTPClient* syncClient;
	NSDate* lastSyncAttemptAt;
	NSString* urlScheme;
	BOOL coreDataSaveDelayed;
	unsigned syncRetries;
	unsigned authRetries;
	NSMutableSet* syncDelegates;
	NSDate* lastSuccessfulSyncAt;
	NSMutableDictionary* pushMessagesWaitingForSync;
	NSMutableDictionary* pushMessagesWaitingForDisplay;
	NSDate* lockChallengesWaitingForDisplay;
	NSMutableArray* facebookOutgoingNotificationsQueue;
	BOOL disableFacebookOutgoingNotification;
	NSMutableArray* randomChallengeRequests;
	NSMutableArray* facebookInvites;
}
@property(readonly, assign, nonatomic) AFHTTPClient* syncClient;
@property(assign, nonatomic) BOOL isSyncing;
@property(assign, nonatomic) BOOL isEnabled;
+(void)resetClient;
+(void)unbindClient;
+(id)sharedClient;
+(void)setHost:(id)host;
+(id)host;
-(void).cxx_destruct;
-(void)reportFacebookInvites:(id)invites;
-(id)forceRandomChallenge:(id)challenge progress:(id)progress;
-(void)handleRequestRandomChallengeQueue;
-(BOOL)requestRandomChallenge:(id)challenge type:(id)type;
-(unsigned)maxRandomRequests;
-(BOOL)requestRandomChallenge;
-(void)cancelLocalNotification:(id)notification;
-(void)handleLocalNotifications;
-(void)postSync;
-(void)syncEnded:(BOOL)ended;
-(void)syncStarted;
-(void)removeSyncDelegate:(id)delegate;
-(void)addSyncDelegate:(id)delegate;
-(void)poke:(id)poke;
-(BOOL)updateChallenges:(id)challenges archive:(BOOL)archive;
-(void)stopSync;
-(BOOL)syncResult:(id)result onComplete:(id)complete;
-(BOOL)synchronize:(BOOL)synchronize onComplete:(id)complete;
-(BOOL)synchronize:(BOOL)synchronize;
-(BOOL)synchronize;
-(BOOL)isCacheValid;
-(void)invalidateCache;
-(void)foreground;
-(void)showChooseTrack:(id)track;
-(void)showPreview:(id)preview;
-(void)showSummary:(id)summary;
-(void)showMenu:(id)menu;
-(void)completeTurn:(id)turn;
-(void)createTurnAndPlayChallenge:(id)challenge levelId:(id)anId;
-(BOOL)startChallenge:(id)challenge;
-(void)downloadPlayer:(id)player includeGhost:(BOOL)ghost onComplete:(id)complete;
-(void)downloadPlayerAndGhostByTinyUrl:(id)url onComplete:(id)complete;
-(void)downloadPlayerByUUID:(id)uuid onComplete:(id)complete;
-(void)downloadPlayerByFacebookID:(id)anId onComplete:(id)complete;
-(void)downloadPlayersByFacebookIDs:(id)ids onComplete:(id)complete;
-(BOOL)askToPlay:(id)play ghost:(id)ghost via:(id)via playedBefore:(BOOL)before;
-(void)createChallengeAgainst:(id)against ghost:(id)ghost via:(id)via askToPlay:(BOOL)play onComplete:(id)complete hasPlayedBefore:(BOOL)before;
-(void)createChallengeAgainst:(id)against ghost:(id)ghost via:(id)via askToPlay:(BOOL)play;
-(void)triggerChallengesWaitingForDisplay;
-(void)handleFacebookInvites;
-(void)disableFacebookOutgoingNotification:(BOOL)notification;
-(void)handleOutgoingFacebookPushMessages;
-(void)handleIncomingPushMessagesWaitingForSync;
-(void)handleFacebookRequests:(id)requests;
-(void)clearChallengeFromMessageQueues:(id)messageQueues;
-(BOOL)handleChallengeRandom:(id)random userTriggered:(BOOL)triggered;
-(BOOL)handleNotification:(id)notification userTriggered:(BOOL)triggered;
-(BOOL)handleUrl:(id)url;
-(void)setBadge:(unsigned)badge;
-(void)resetClient:(BOOL)client;
-(void)join:(id)join;
-(void)enable:(id)enable;
-(void)enable;
-(id)init;
@end

