/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "TrialGameControllerDelegate.h"
#import "HSTableViewDataSource.h"
#import "HSTableViewDelegate.h"
#import "HSMenuLayer.h"

@class Challenge, HSTableView, NSString, NSMutableSet;

__attribute__((visibility("hidden")))
@interface ChallengeChooseTheme : HSMenuLayer <HSTableViewDelegate, HSTableViewDataSource, TrialGameControllerDelegate> {
	Challenge* challenge;
	BOOL showInfo;
	NSMutableSet* unlockedLevels;
	HSTableView* tableView;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
+(id)layerWithMenu:(id)menu challenge:(id)challenge;
+(id)sceneWithChallenge:(id)challenge;
-(void).cxx_destruct;
-(id)controllerItemForIndex:(unsigned)index;
-(id)controllerItemConfig;
-(unsigned)controllerDefaultItem;
-(void)controllerCancel;
-(void)postFirstVisit;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(int)numberOfSectionsInTableView:(id)tableView;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view viewForHeaderInSection:(int)section;
-(float)tableView:(id)view heightForHeaderInSection:(int)section;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(float)tableView:(id)view heightForRowAtIndexPath:(id)indexPath;
-(void)reload;
-(void)createUI;
-(void)showInfo;
-(void)onEnter;
-(void)cleanup;
-(id)initWithMenu:(id)menu challenge:(id)challenge;
-(id)initWithMenu:(id)menu;
@end

