/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "HSMenuLayer.h"
#import "Boom-Structs.h"

@class Challenge, NSString;

__attribute__((visibility("hidden")))
@interface ChallengeChooseTrack : HSMenuLayer {
	Challenge* challenge;
	NSString* themeId;
	BOOL hasSpecifiedTheme;
}
+(id)layerWithMenu:(id)menu theme:(id)theme challenge:(id)challenge;
-(void).cxx_destruct;
-(void)runTrack:(id)track;
-(void)autoRunTrack;
-(void)migratePlayedLevels;
-(void)cleanup;
-(id)initWithMenu:(id)menu theme:(id)theme challenge:(id)challenge;
-(id)initWithMenu:(id)menu;
@end

