/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class Challenge, NSData, NSDate, ChallengePlayer, NSNumber, NSString;

__attribute__((visibility("hidden")))
@interface ChallengeTurn : XXUnknownSuperclass {
}
@property(retain, nonatomic) ChallengePlayer* receiver;
@property(retain, nonatomic) ChallengeTurn* preceededByTurn;
@property(retain, nonatomic) ChallengeTurn* followedByTurn;
@property(retain, nonatomic) ChallengePlayer* creator;
@property(retain, nonatomic) Challenge* challenge;
@property(retain, nonatomic) NSNumber* multiTarget;
@property(retain, nonatomic) NSNumber* turnId;
@property(retain, nonatomic) NSNumber* receiverTries;
@property(retain, nonatomic) NSData* receiverTimings;
@property(retain, nonatomic) NSNumber* receiverTime;
@property(retain, nonatomic) NSDate* receiverPlayedAt;
@property(retain, nonatomic) NSData* receiverData;
@property(retain, nonatomic) NSNumber* receiverComplete;
@property(retain, nonatomic) NSNumber* levelVersion;
@property(retain, nonatomic) NSString* levelId;
@property(retain, nonatomic) NSNumber* isPreviewed;
@property(retain, nonatomic) NSNumber* isCompleted;
@property(retain, nonatomic) NSNumber* creatorTries;
@property(retain, nonatomic) NSData* creatorTimings;
@property(retain, nonatomic) NSNumber* creatorTime;
@property(retain, nonatomic) NSDate* creatorPlayedAt;
@property(retain, nonatomic) NSData* creatorData;
@property(retain, nonatomic) NSNumber* creatorComplete;
+(id)createTurn:(id)turn data:(id)data;
+(id)createTurn:(id)turn levelId:(id)anId version:(id)version;
+(id)createTurn:(id)turn levelId:(id)anId;
-(id)postData;
-(void)updateRunWithTimings:(id)timings ghostFile:(id)file;
-(int)selfRetries;
-(BOOL)incrementRetries;
-(void)completeTurn:(BOOL)turn;
-(void)completeTurn;
-(BOOL)challengerIsCompleted;
-(BOOL)challengerIsWinner;
-(id)challengerTime;
-(id)challengerTimings;
-(id)challengerGhost;
-(id)selfGhost;
-(BOOL)challengerHasPlayed;
-(BOOL)selfHasPlayed;
-(BOOL)selfIsWinner;
-(id)selfTime;
-(id)selfTimings;
-(void)update:(id)update;
-(void)awakeFromFetch;
-(void)deleteChallengeTurn:(BOOL)turn;
-(void)deleteChallengeTurn;
@end

