/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "HSMenuItem.h"

@class Challenge, CCSprite, Wheely, HSHiddenSwipeMenuItem, HSLabelWithStroke, HSLabelSafeBMFont, InfoButton;

__attribute__((visibility("hidden")))
@interface ChallengeItem : HSMenuItem {
	Challenge* challenge;
	InfoButton* infoButton;
	Wheely* opponentCharacter;
	HSLabelWithStroke* opponentNick;
	HSLabelSafeBMFont* wins;
	HSLabelSafeBMFont* winsLabel;
	HSLabelSafeBMFont* losses;
	HSLabelSafeBMFont* lossesLabel;
	HSLabelSafeBMFont* glowLabel;
	HSLabelSafeBMFont* glowNumber;
	HSHiddenSwipeMenuItem* removeButton;
	HSMenuItem* pokeButton;
	CCSprite* fade;
	CCSprite* brightenOverlay;
	CCSprite* photoFrame;
	CCSprite* photo;
	BOOL isSwiped;
	id removeBlock;
	id profileBlock;
}
@property(copy, nonatomic) id profileBlock;
@property(retain, nonatomic) Challenge* challenge;
@property(readonly, assign, nonatomic) BOOL isSwiped;
+(id)itemWithChallenge:(id)challenge;
-(void).cxx_destruct;
-(void)blur;
-(void)focus;
-(id)itemForTouch:(id)touch;
-(BOOL)ccTouchBegan:(id)began withEvent:(id)event;
-(void)setRemoveBlock:(id)block;
-(void)remove;
-(void)activate;
-(void)onExit;
-(void)unselected;
-(void)selected;
-(void)updateSwipe:(BOOL)swipe;
-(void)poke;
-(void)hideRemoveButton;
-(void)swiped;
-(void)setupPhoto:(id)photo;
-(void)setup;
-(void)cleanup;
@end

