/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSSet, NSDate, NSNumber, NSString;

__attribute__((visibility("hidden")))
@interface ChallengePlayer : XXUnknownSuperclass {
}
@property(retain, nonatomic) NSSet* turnsAsReceiver;
@property(retain, nonatomic) NSSet* turnsAsCreator;
@property(retain, nonatomic) NSSet* challengesAsReceiver;
@property(retain, nonatomic) NSSet* challengesAsInitiator;
@property(retain, nonatomic) NSSet* challengesAsCreator;
@property(retain, nonatomic) NSString* uuid;
@property(retain, nonatomic) NSString* tinyUrl;
@property(retain, nonatomic) id profile;
@property(retain, nonatomic) NSString* notification;
@property(retain, nonatomic) NSString* nickname;
@property(retain, nonatomic) NSDate* lastLoginAt;
@property(retain, nonatomic) NSNumber* justCreated;
@property(retain, nonatomic) NSNumber* isSelf;
@property(retain, nonatomic) NSNumber* hasPlayedAgainst;
@property(retain, nonatomic) NSString* facebookID;
+(id)createChallengePlayerByData:(id)data archive:(BOOL)archive;
+(id)loadChallengePlayersByFacebookID:(id)anId;
+(id)loadChallengePlayerByFetchRequest:(id)request;
+(id)loadChallengePlayerByTinyUrl:(id)url;
+(id)loadChallengePlayersByUUID:(id)uuid;
+(id)loadChallengePlayerByUUID:(id)uuid;
+(id)playerSelf;
+(void)vacuum:(BOOL)vacuum;
-(id)maxGroupIdUnlocked;
-(float)totalDistance;
-(unsigned)totalEarnedSuperStars;
-(unsigned)totalEarnedMedals;
-(id)worldRank;
-(id)tournamentStats;
-(id)challengeStats;
-(id)countryCode;
-(id)wheelStyle;
-(id)engineStyle;
-(id)heroStyle;
-(BOOL)update:(id)update archive:(BOOL)archive;
-(id)nicknameCapped:(unsigned)capped;
-(id)rawNickname;
-(void)deletePlayer:(BOOL)player;
@end

