/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSArray, NSString;

@interface CLSMachOSlice : XXUnknownSuperclass {
	CLSMachOSlice _slice;
	NSString* _uuidString;
	NSArray* _linkedDylibs;
	XXStruct_VQhNEA _minimumOSVersion;
	XXStruct_VQhNEA _linkedSDKVersion;
}
@property(readonly, assign, nonatomic) XXStruct_VQhNEA linkedSDKVersion;
@property(readonly, assign, nonatomic) XXStruct_VQhNEA minimumOSVersion;
@property(readonly, assign, nonatomic) NSArray* linkedDylibs;
@property(readonly, copy, nonatomic) NSString* architectureName;
@property(readonly, copy, nonatomic) NSString* uuid;
+(id)runningSlice;
-(void).cxx_destruct;
-(id)initWithSlice:(CLSMachOSlice*)slice;
@end

