/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "TrialGameControllerDelegate.h"
#import "HSMenuLayer.h"
#import "Boom-Structs.h"

@class NSMutableArray, HSAdjustedSprite;

__attribute__((visibility("hidden")))
@interface EarnCoinsDialog : HSMenuLayer <TrialGameControllerDelegate> {
	HSAdjustedSprite* dialog;
	HSAdjustedSprite* facebookConnectNode;
	HSAdjustedSprite* facebookGameNode;
	HSAdjustedSprite* twitterGameNode;
	unsigned facebookGameLikeWaitRetries;
	unsigned facebookConnectWaitRetries;
	BOOL shouldWaitForFacebookGameLike;
	BOOL shouldWaitForConnectToFacebook;
	NSMutableArray* buttons;
}
-(void).cxx_destruct;
-(id)controllerItemForIndex:(unsigned)index;
-(id)controllerItemConfig;
-(unsigned)controllerDefaultItem;
-(void)controllerCancel;
-(void)postFirstVisit;
-(void)postTransitionIn;
-(void)cleanup;
-(void)stopWaitingForConnectToFacebook;
-(void)waitForConnectToFacebook;
-(void)connectToFacebook;
-(id)buildEarnTitle:(id)title earned:(BOOL)earned action:(id)action;
-(void)buildEarnItems;
-(void)back;
-(id)initWithMenu:(id)menu;
@end

