/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class FABIcon, NSDictionary, NSString;

@interface FABApplicationIdentiferModel : XXUnknownSuperclass {
	NSDictionary* _architectureUUIDMap;
	NSString* _installID;
	FABIcon* _icon;
	NSString* _bundleIdentifier;
	NSString* _instanceIdentifier;
	XXStruct_VQhNEA _builtSDK;
	XXStruct_VQhNEA _minimumSDK;
}
@property(readonly, assign, nonatomic) NSString* bundleIdentifier;
@property(readonly, assign, nonatomic) FABIcon* icon;
@property(readonly, assign, nonatomic) NSString* installID;
@property(readonly, assign, nonatomic) NSString* minimumSDKString;
@property(readonly, assign, nonatomic) NSString* builtSDKString;
@property(readonly, assign, nonatomic) XXStruct_VQhNEA minimumSDK;
@property(readonly, assign, nonatomic) XXStruct_VQhNEA builtSDK;
@property(copy, nonatomic) NSString* instanceIdentifier;
@property(copy, nonatomic) NSDictionary* architectureUUIDMap;
-(void).cxx_destruct;
-(BOOL)computeInstanceIdentifier;
-(BOOL)computeExecutableInfo;
-(id)initWithInstallID:(id)installID;
@end

