/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


@interface FBSDKButton : XXUnknownSuperclass {
	BOOL _skipIntrinsicContentSizing;
	BOOL _isExplicitlyDisabled;
}
-(float)_textPaddingCorrectionForHeight:(float)height;
-(float)_paddingForHeight:(float)height;
-(float)_marginForHeight:(float)height;
-(float)_heightForFont:(id)font;
-(float)_heightForContentRect:(CGRect)contentRect;
-(float)_fontSizeForHeight:(float)height;
-(void)_configureWithIcon:(id)icon title:(id)title backgroundColor:(id)color highlightedColor:(id)color4 selectedTitle:(id)title5 selectedIcon:(id)icon6 selectedColor:(id)color7 selectedHighlightedColor:(id)color8;
-(id)_backgroundImageWithColor:(id)color cornerRadius:(float)radius scale:(float)scale;
-(void)_applicationDidBecomeActiveNotification:(id)_application;
-(CGSize)sizeThatFits:(CGSize)fits title:(id)title;
-(BOOL)isImplicitlyDisabled;
-(id)defaultSelectedColor;
-(id)defaultIcon;
-(id)defaultHighlightedColor;
-(id)defaultDisabledColor;
-(id)defaultBackgroundColor;
-(void)configureWithIcon:(id)icon title:(id)title backgroundColor:(id)color highlightedColor:(id)color4 selectedTitle:(id)title5 selectedIcon:(id)icon6 selectedColor:(id)color7 selectedHighlightedColor:(id)color8;
-(void)configureWithIcon:(id)icon title:(id)title backgroundColor:(id)color highlightedColor:(id)color4;
-(void)configureButton;
-(void)checkImplicitlyDisabled;
-(CGRect)titleRectForContentRect:(CGRect)contentRect;
-(void)sizeToFit;
-(CGSize)sizeThatFits:(CGSize)fits;
-(void)layoutSubviews;
-(CGSize)intrinsicContentSize;
-(CGRect)imageRectForContentRect:(CGRect)contentRect;
-(void)setEnabled:(BOOL)enabled;
-(void)dealloc;
-(void)awakeFromNib;
-(id)initWithFrame:(CGRect)frame;
@end

