/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "FBSDKCopying.h"
#import "NSSecureCoding.h"

@class NSArray, NSString, NSURL;

@protocol FBSDKSharingContent <FBSDKCopying, NSSecureCoding>
@property(copy, nonatomic) NSString* ref;
@property(copy, nonatomic) NSString* placeID;
@property(copy, nonatomic) NSArray* peopleIDs;
@property(copy, nonatomic) NSURL* contentURL;
@end

