/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSSet;

@interface FBSDKGameRequestFrictionlessRecipientCache : XXUnknownSuperclass {
	NSSet* _recipientIDs;
}
-(void).cxx_destruct;
-(void)_updateCache;
-(void)_accessTokenDidChangeNotification:(id)_accessToken;
-(void)updateWithResults:(id)results;
-(BOOL)recipientsAreFrictionless:(id)frictionless;
-(void)dealloc;
-(id)init;
@end

