/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface FBSDKTimeSpentData : XXUnknownSuperclass {
	BOOL _isCurrentlyLoaded;
	BOOL _shouldLogActivateEvent;
	BOOL _shouldLogDeactivateEvent;
	long _secondsSpentInCurrentSession;
	long _timeSinceLastSuspend;
	int _numInterruptionsInCurrentSession;
	long _lastRestoreTime;
	int _numSecondsIdleToBeNewSession;
}
@property(assign, nonatomic) int numSecondsIdleToBeNewSession;
+(void)registerAutoResetSourceApplication;
+(void)resetSourceApplication;
+(id)getSourceApplication;
+(void)setSourceApplication:(id)application isFromAppLink:(BOOL)appLink;
+(void)setSourceApplication:(id)application openURL:(id)url;
+(id)singleton;
+(void)restore:(BOOL)restore;
+(void)suspend;
-(void)instanceRestore:(BOOL)restore;
-(void)instanceSuspend;
-(id)init;
@end

