/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "FBSDKSharingContent.h"
#import "Boom-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSURL, NSArray, NSDictionary, NSString;

@interface FBSDKShareLinkContent : XXUnknownSuperclass <FBSDKSharingContent> {
	NSURL* _contentURL;
	NSArray* _peopleIDs;
	NSString* _placeID;
	NSString* _ref;
	NSDictionary* _feedParameters;
	NSString* _contentDescription;
	NSString* _contentTitle;
	NSURL* _imageURL;
}
@property(copy, nonatomic) NSString* ref;
@property(copy, nonatomic) NSString* placeID;
@property(copy, nonatomic) NSArray* peopleIDs;
@property(copy, nonatomic) NSURL* contentURL;
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(copy, nonatomic) NSDictionary* feedParameters;
@property(copy, nonatomic) NSURL* imageURL;
@property(copy, nonatomic) NSString* contentTitle;
@property(copy, nonatomic) NSString* contentDescription;
+(BOOL)supportsSecureCoding;
-(void).cxx_destruct;
-(id)copyWithZone:(NSZone*)zone;
-(void)encodeWithCoder:(id)coder;
-(id)initWithCoder:(id)coder;
-(BOOL)isEqualToShareLinkContent:(id)shareLinkContent;
-(BOOL)isEqual:(id)equal;
@end

