/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "FBSDKWebDialogDelegate.h"
#import "FBSDKSharingDialog.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UIViewController, FBSDKWebDialog, NSString;
@protocol FBSDKSharingContent, FBSDKSharingDelegate;

@interface FBSDKShareDialog : XXUnknownSuperclass <FBSDKWebDialogDelegate, FBSDKSharingDialog> {
	FBSDKWebDialog* _webDialog;
	BOOL _shouldFailOnDataError;
	id<FBSDKSharingDelegate> _delegate;
	id<FBSDKSharingContent> _shareContent;
	UIViewController* _fromViewController;
	unsigned _mode;
}
@property(assign, nonatomic) BOOL shouldFailOnDataError;
@property(copy, nonatomic) id<FBSDKSharingContent> shareContent;
@property(assign, nonatomic) __weak id<FBSDKSharingDelegate> delegate;
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) unsigned mode;
@property(assign, nonatomic) __weak UIViewController* fromViewController;
+(id)showFromViewController:(id)viewController withContent:(id)content delegate:(id)delegate;
+(void)initialize;
-(void).cxx_destruct;
-(void)_logDialogShow;
-(void)_invokeDelegateDidFailWithError:(id)_invokeDelegate;
-(void)_invokeDelegateDidCompleteWithResults:(id)_invokeDelegate;
-(void)_invokeDelegateDidCancel;
-(BOOL)_validateShareContentForShareSheet:(id*)shareSheet;
-(BOOL)_validateShareContentForNative:(id*)native;
-(BOOL)_validateShareContentForFeed:(id*)feed;
-(BOOL)_validateShareContentForBrowser:(id*)browser;
-(BOOL)_showWeb:(id*)web;
-(BOOL)_showShareSheetWithCanShowError:(id*)canShowError validationError:(id*)error;
-(BOOL)_showNativeWithCanShowError:(id*)canShowError validationError:(id*)error;
-(BOOL)_showFeedWeb:(id*)web;
-(BOOL)_showFeedBrowser:(id*)browser;
-(BOOL)_showBrowser:(id*)browser;
-(void)_handleWebResponseParameters:(id)parameters error:(id)error;
-(id)_contentURLs;
-(id)_contentImages;
-(void)_cleanUpWebDialog;
-(BOOL)_canAttributeThroughShareSheet;
-(BOOL)_canShowShareSheet;
-(void)_loadNativeMethodName:(id*)name methodVersion:(id*)version;
-(BOOL)_showAutomatic:(id*)automatic;
-(BOOL)_isDefaultToShareSheet;
-(void)webDialogDidCancel:(id)webDialog;
-(void)webDialog:(id)dialog didFailWithError:(id)error;
-(void)webDialog:(id)dialog didCompleteWithResults:(id)results;
-(BOOL)validateWithError:(id*)error;
-(BOOL)show;
-(BOOL)canShow;
-(void)dealloc;
@end

