/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "FBSDKCopying.h"
#import "NSSecureCoding.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSArray, NSURL, NSString;

@interface FBSDKDialogConfiguration : XXUnknownSuperclass <FBSDKCopying, NSSecureCoding> {
	NSArray* _appVersions;
	NSString* _name;
	NSURL* _URL;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(readonly, copy, nonatomic) NSURL* URL;
@property(readonly, copy, nonatomic) NSString* name;
@property(readonly, copy, nonatomic) NSArray* appVersions;
+(BOOL)supportsSecureCoding;
-(void).cxx_destruct;
-(id)copyWithZone:(NSZone*)zone;
-(void)encodeWithCoder:(id)coder;
-(id)initWithCoder:(id)coder;
-(id)init;
-(id)initWithName:(id)name URL:(id)url appVersions:(id)versions;
@end

