/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSSecureCoding.h"
#import "NSObject.h"


@protocol FBSDKShareOpenGraphValueContaining <NSObject, NSSecureCoding>
-(id)URLForKey:(id)key;
-(id)stringForKey:(id)key;
-(void)setURL:(id)url forKey:(id)key;
-(void)setString:(id)string forKey:(id)key;
-(void)setPhoto:(id)photo forKey:(id)key;
-(void)setObject:(id)object forKey:(id)key;
-(void)setNumber:(id)number forKey:(id)key;
-(void)setArray:(id)array forKey:(id)key;
-(void)removeObjectForKey:(id)key;
-(id)photoForKey:(id)key;
-(void)parseProperties:(id)properties;
-(id)objectForKeyedSubscript:(id)keyedSubscript;
-(id)objectForKey:(id)key;
-(id)objectEnumerator;
-(id)numberForKey:(id)key;
-(id)keyEnumerator;
-(void)enumerateKeysAndObjectsUsingBlock:(id)block;
-(id)arrayForKey:(id)key;
@end

