/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "FBSDKWebDialogDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class FBSDKWebDialog, NSString;
@protocol FBSDKAppGroupJoinDialogDelegate;

@interface FBSDKAppGroupJoinDialog : XXUnknownSuperclass <FBSDKWebDialogDelegate> {
	FBSDKWebDialog* _webDialog;
	id<FBSDKAppGroupJoinDialogDelegate> _delegate;
	NSString* _groupID;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(copy, nonatomic) NSString* groupID;
@property(assign, nonatomic) __weak id<FBSDKAppGroupJoinDialogDelegate> delegate;
+(id)showWithGroupID:(id)groupID delegate:(id)delegate;
-(void).cxx_destruct;
-(void)_handleCompletionWithDialogResults:(id)dialogResults error:(id)error;
-(void)webDialogDidCancel:(id)webDialog;
-(void)webDialog:(id)dialog didFailWithError:(id)error;
-(void)webDialog:(id)dialog didCompleteWithResults:(id)results;
-(BOOL)validateWithError:(id*)error;
-(BOOL)show;
-(BOOL)canShow;
-(void)dealloc;
-(id)init;
@end

