/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "FBSDKURLOpening.h"
#import "FBSDKWebDialogDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSSet, FBSDKKeychainStore, FBSDKLoginManagerLogger, NSString;

@interface FBSDKLoginManager : XXUnknownSuperclass <FBSDKURLOpening, FBSDKWebDialogDelegate> {
	id _handler;
	NSSet* _requestedPermissions;
	FBSDKLoginManagerLogger* _logger;
	BOOL _performingLogIn;
	FBSDKKeychainStore* _keychainStore;
	unsigned _defaultAudience;
	unsigned _loginBehavior;
}
@property(assign, nonatomic) unsigned loginBehavior;
@property(assign, nonatomic) unsigned defaultAudience;
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
+(id)stringForChallenge;
+(void)renewSystemCredentials:(id)credentials;
+(void)initialize;
-(void).cxx_destruct;
-(void)setRequestedPermissions:(id)permissions;
-(void)setHandler:(id)handler;
-(void)validateReauthentication:(id)reauthentication withResult:(id)result;
-(void)storeExpectedChallenge:(id)challenge;
-(void)logInWithBehavior:(unsigned)behavior;
-(void)logInWithPermissions:(id)permissions handler:(id)handler;
-(id)logInParametersWithPermissions:(id)permissions;
-(id)loadExpectedChallenge;
-(void)invokeHandler:(id)handler error:(id)error;
-(void)determineRecentlyGrantedPermissions:(id*)permissions recentlyDeclinedPermissions:(id*)permissions2 forGrantedPermission:(id)grantedPermission declinedPermissions:(id)permissions4;
-(void)completeAuthentication:(id)authentication expectChallenge:(BOOL)challenge;
-(void)assertPermissions:(id)permissions;
-(void)logOut;
-(void)logInWithPublishPermissions:(id)publishPermissions handler:(id)handler;
-(void)logInWithReadPermissions:(id)readPermissions handler:(id)handler;
-(id)init;
-(void)handleImplicitCancelOfLogIn;
-(void)applicationDidBecomeActive:(id)application;
-(BOOL)application:(id)application openURL:(id)url sourceApplication:(id)application3 annotation:(id)annotation;
-(void)tryOpenURL:(id)url handler:(id)handler;
-(void)performBrowserLogInWithParameters:(id)parameters handler:(id)handler;
-(void)performNativeLogInWithParameters:(id)parameters handler:(id)handler;
-(void)fallbackToNativeBehavior;
-(void)continueSystemLogInWithTokenString:(id)tokenString error:(id)error state:(id)state;
-(void)performSystemLogIn;
-(void)beginSystemLogIn;
-(void)webDialogDidCancel:(id)webDialog;
-(void)webDialog:(id)dialog didFailWithError:(id)error;
-(void)webDialog:(id)dialog didCompleteWithResults:(id)results;
-(void)performWebLogInWithParameters:(id)parameters handler:(id)handler;
@end

