/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "UIAlertViewDelegate.h"

@class UIAlertView, FBSDKErrorRecoveryAttempter, NSError, NSString;
@protocol FBSDKGraphErrorRecoveryProcessorDelegate;

@interface FBSDKGraphErrorRecoveryProcessor : XXUnknownSuperclass <UIAlertViewDelegate> {
	FBSDKErrorRecoveryAttempter* _recoveryAttempter;
	NSError* _error;
	UIAlertView* _alertView;
	id<FBSDKGraphErrorRecoveryProcessorDelegate> _delegate;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) id<FBSDKGraphErrorRecoveryProcessorDelegate> delegate;
-(void).cxx_destruct;
-(void)didPresentErrorWithRecovery:(BOOL)recovery contextInfo:(void*)info;
-(void)alertView:(id)view clickedButtonAtIndex:(int)index;
-(BOOL)processError:(id)error request:(id)request delegate:(id)delegate;
-(void)dealloc;
@end

