/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "FBSDKCopying.h"
#import "NSSecureCoding.h"
#import "Boom-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSDictionary, NSDate, NSString, FBSDKErrorConfiguration;

@interface FBSDKServerConfiguration : XXUnknownSuperclass <FBSDKCopying, NSSecureCoding> {
	NSDictionary* _dialogConfigurations;
	BOOL _advertisingIDEnabled;
	BOOL _implicitLoggingEnabled;
	BOOL _implicitPurchaseLoggingEnabled;
	BOOL _loginTooltipEnabled;
	BOOL _systemAuthenticationEnabled;
	NSString* _appID;
	NSString* _appName;
	NSString* _loginTooltipText;
	NSString* _defaultShareMode;
	NSDate* _timestamp;
	FBSDKErrorConfiguration* _errorConfiguration;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(readonly, assign, nonatomic) FBSDKErrorConfiguration* errorConfiguration;
@property(readonly, copy, nonatomic) NSDate* timestamp;
@property(readonly, assign, nonatomic, getter=isSystemAuthenticationEnabled) BOOL systemAuthenticationEnabled;
@property(readonly, copy, nonatomic) NSString* defaultShareMode;
@property(readonly, copy, nonatomic) NSString* loginTooltipText;
@property(readonly, assign, nonatomic, getter=isLoginTooltipEnabled) BOOL loginTooltipEnabled;
@property(readonly, assign, nonatomic, getter=isImplicitPurchaseLoggingSupported) BOOL implicitPurchaseLoggingEnabled;
@property(readonly, assign, nonatomic, getter=isImplicitLoggingSupported) BOOL implicitLoggingEnabled;
@property(readonly, copy, nonatomic) NSString* appName;
@property(readonly, copy, nonatomic) NSString* appID;
@property(readonly, assign, nonatomic, getter=isAdvertisingIDEnabled) BOOL advertisingIDEnabled;
+(BOOL)supportsSecureCoding;
-(void).cxx_destruct;
-(id)copyWithZone:(NSZone*)zone;
-(void)encodeWithCoder:(id)coder;
-(id)initWithCoder:(id)coder;
-(id)dialogConfigurationForDialogName:(id)dialogName;
-(id)initWithAppID:(id)appID appName:(id)name loginTooltipEnabled:(BOOL)enabled loginTooltipText:(id)text defaultShareMode:(id)mode advertisingIDEnabled:(BOOL)enabled6 implicitLoggingEnabled:(BOOL)enabled7 implicitPurchaseLoggingEnabled:(BOOL)enabled8 systemAuthenticationEnabled:(BOOL)enabled9 dialogConfigurations:(id)configurations timestamp:(id)timestamp errorConfiguration:(id)configuration;
-(id)init;
@end

