/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "FBSDKBridgeAPIProtocol.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

@interface FBSDKBridgeAPIProtocolWebV1 : XXUnknownSuperclass <FBSDKBridgeAPIProtocol> {
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
-(id)responseParametersForActionID:(id)actionID queryParameters:(id)parameters cancelled:(BOOL*)cancelled error:(id*)error;
-(id)requestURLWithActionID:(id)actionID scheme:(id)scheme methodName:(id)name methodVersion:(id)version parameters:(id)parameters error:(id*)error;
@end

