/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableDictionary, NSError, NSString;

@interface FBSDKLoginManagerLogger : XXUnknownSuperclass {
	NSString* _identifier;
	NSMutableDictionary* _extras;
	NSString* _lastResult;
	NSError* _lastError;
	unsigned _loginBehavior;
}
+(id)loggerFromParameters:(id)parameters;
-(void).cxx_destruct;
-(void)logEvent:(id)event result:(id)result error:(id)error;
-(void)logEvent:(id)event params:(id)params;
-(id)parametersForNewEventWithBehavior:(const unsigned*)behavior;
-(id)identifierForBehavior:(unsigned)behavior;
-(id)clientStateForBehavior:(unsigned)behavior andExistingState:(id)state;
-(void)systemAuthDidShowDialog:(BOOL)systemAuth isUnTOSedDevice:(BOOL)device;
-(void)willAttemptAppSwitchingBehavior;
-(id)parametersWithTimeStampAndClientState:(id)timeStampAndClientState forLoginBehavior:(unsigned)loginBehavior;
-(void)endLoginWithResult:(unsigned)result error:(id)error;
-(void)startLoginWithBehavior:(unsigned)behavior;
-(void)endEvent;
-(void)startEventWithBehavior:(unsigned)behavior isReauthorize:(BOOL)reauthorize;
-(id)init;
@end

