/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "FBSDKLoginCompleting.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class FBSDKLoginCompletionParameters;

@interface FBSDKLoginSystemAccountCompleter : XXUnknownSuperclass <FBSDKLoginCompleting> {
	FBSDKLoginCompletionParameters* _parameters;
}
-(void).cxx_destruct;
-(void)completeLogIn:(id)anIn withHandler:(id)handler;
-(id)initWithTokenString:(id)tokenString appID:(id)anId;
-(id)init;
@end

