/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "FBSDKLiking.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class FBSDKLikeBoxView, UIView, UIColor, NSString, UILabel, FBSDKLikeButton;

@interface FBSDKLikeControl : XXUnknownSuperclass <FBSDKLiking> {
	BOOL _isExplicitlyDisabled;
	FBSDKLikeBoxView* _likeBoxView;
	FBSDKLikeButton* _likeButton;
	UIView* _likeButtonContainer;
	UILabel* _socialSentenceLabel;
	UIColor* _foregroundColor;
	unsigned _likeControlAuxiliaryPosition;
	unsigned _likeControlHorizontalAlignment;
	unsigned _likeControlStyle;
	float _preferredMaxLayoutWidth;
}
@property(assign, nonatomic) unsigned objectType;
@property(copy, nonatomic) NSString* objectID;
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic, getter=isSoundEnabled) BOOL soundEnabled;
@property(assign, nonatomic) float preferredMaxLayoutWidth;
@property(assign, nonatomic) unsigned likeControlStyle;
@property(assign, nonatomic) unsigned likeControlHorizontalAlignment;
@property(assign, nonatomic) unsigned likeControlAuxiliaryPosition;
@property(retain, nonatomic) UIColor* foregroundColor;
+(void)initialize;
-(void).cxx_destruct;
-(void)_updateLikeBoxCaretPosition;
-(void)_updateEnabled;
-(void)_likeActionControllerDidUpdateWithAnimated:(BOOL)_likeActionController;
-(void)_likeActionControllerDidUpdateNotification:(id)_likeActionController;
-(void)_likeActionControllerDidDisableNotification:(id)_likeActionController;
-(FBSDKLikeControlLayout)_layoutWithBounds:(CGRect)bounds subviewSizingBlock:(id)block;
-(void)observeValueForKeyPath:(id)keyPath ofObject:(id)object change:(id)change context:(void*)context;
-(void)_initializeContent;
-(void)_handleLikeButtonTap:(id)tap;
-(void)_ensureLikeActionController;
-(float)_auxiliaryViewPadding;
-(id)_auxiliaryView;
-(id)analyticsParameters;
-(CGSize)sizeThatFits:(CGSize)fits;
-(void)layoutSubviews;
-(CGSize)intrinsicContentSize;
-(void)setOpaque:(BOOL)opaque;
-(void)setEnabled:(BOOL)enabled;
-(void)setBackgroundColor:(id)color;
-(void)dealloc;
-(id)initWithCoder:(id)coder;
-(id)initWithFrame:(CGRect)frame;
@end

