/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableString, NSString;

@interface FBSDKLogger : XXUnknownSuperclass {
	BOOL _isActive;
	unsigned _loggerSerialNumber;
	NSString* _loggingBehavior;
	NSMutableString* _internalContents;
}
@property(readonly, assign, nonatomic) NSMutableString* internalContents;
@property(readonly, assign, nonatomic) BOOL isActive;
@property(readonly, copy, nonatomic) NSString* loggingBehavior;
@property(readonly, assign, nonatomic) unsigned loggerSerialNumber;
@property(copy, nonatomic) NSString* contents;
+(void)registerStringToReplace:(id)replace replaceWith:(id)with;
+(void)registerCurrentTime:(id)time withTag:(id)tag;
+(void)singleShotLogEntry:(id)entry timestampTag:(id)tag formatString:(id)string;
+(void)singleShotLogEntry:(id)entry formatString:(id)string;
+(void)singleShotLogEntry:(id)entry logEntry:(id)entry2;
+(unsigned)generateSerialNumber;
-(void).cxx_destruct;
-(void)emitToNSLog;
-(void)appendKey:(id)key value:(id)value;
-(void)appendFormat:(id)format;
-(void)appendString:(id)string;
-(id)initWithLoggingBehavior:(id)loggingBehavior;
@end

