/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "FBSDKCopying.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class FBSDKBridgeAPIRequest, NSDictionary, NSError, NSString;

@interface FBSDKBridgeAPIResponse : XXUnknownSuperclass <FBSDKCopying> {
	BOOL _cancelled;
	NSError* _error;
	FBSDKBridgeAPIRequest* _request;
	NSDictionary* _responseParameters;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(readonly, copy, nonatomic) NSDictionary* responseParameters;
@property(readonly, copy, nonatomic) FBSDKBridgeAPIRequest* request;
@property(readonly, copy, nonatomic) NSError* error;
@property(readonly, assign, nonatomic, getter=isCancelled) BOOL cancelled;
+(id)bridgeAPIResponseCancelledWithRequest:(id)request;
+(id)bridgeAPIResponseWithRequest:(id)request responseURL:(id)url sourceApplication:(id)application error:(id*)error;
+(id)bridgeAPIResponseWithRequest:(id)request error:(id)error;
-(void).cxx_destruct;
-(id)copyWithZone:(NSZone*)zone;
-(id)init;
-(id)initWithRequest:(id)request responseParameters:(id)parameters cancelled:(BOOL)cancelled error:(id)error;
@end

