/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface FBSDKLoginUtility : XXUnknownSuperclass {
}
+(id)userIDFromSignedRequest:(id)signedRequest;
+(id)queryParamsFromLoginURL:(id)loginURL;
+(id)stringForAudience:(unsigned)audience;
+(BOOL)areAllPermissionsPublishPermissions:(id)permissions;
+(BOOL)areAllPermissionsReadPermissions:(id)permissions;
+(BOOL)isPublishPermission:(id)permission;
-(id)init;
@end

