/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "FBSDKKeychainStore.h"


@interface FBSDKKeychainStoreViaBundleID : FBSDKKeychainStore {
}
-(id)queryForKey:(id)key;
-(id)initWithService:(id)service accessGroup:(id)group;
-(id)init;
@end

