/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableDictionary, NSString;

@interface FBSDKTestUsersManager : XXUnknownSuperclass {
	NSString* _appID;
	NSString* _appSecret;
	NSMutableDictionary* _accounts;
}
+(id)sharedInstanceForAppID:(id)appID appSecret:(id)secret;
-(void).cxx_destruct;
-(void)fetchExistingTestAccountsWithAfterCursor:(id)afterCursor handler:(id)handler;
-(id)appAccessToken;
-(id)userIdAndTokenOfExistingAccountWithPermissions:(id)permissions skip:(id)skip;
-(id)tokenDataForTokenString:(id)tokenString permissions:(id)permissions userId:(id)anId;
-(void)removeTestAccount:(id)account completionHandler:(id)handler;
-(void)makeFriendsWithFirst:(id)first second:(id)second callback:(id)callback;
-(void)addTestAccountWithPermissions:(id)permissions completionHandler:(id)handler;
-(void)requestTestAccountTokensWithArraysOfPermissions:(id)permissions createIfNotFound:(BOOL)found completionHandler:(id)handler;
-(id)init;
-(id)initWithAppID:(id)appID appSecret:(id)secret;
@end

