/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "FBSDKTooltipView.h"
#import "Boom-Structs.h"

@protocol FBSDKLoginTooltipViewDelegate;

@interface FBSDKLoginTooltipView : FBSDKTooltipView {
	BOOL _forceDisplay;
	id<FBSDKLoginTooltipViewDelegate> _delegate;
}
@property(assign, nonatomic) BOOL forceDisplay;
@property(assign, nonatomic) id<FBSDKLoginTooltipViewDelegate> delegate;
-(void)presentInView:(id)view withArrowPosition:(CGPoint)arrowPosition direction:(unsigned)direction;
-(id)init;
@end

