/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class FBSDKProfilePictureViewState, UIImageView, NSString;

@interface FBSDKProfilePictureView : XXUnknownSuperclass {
	BOOL _hasProfileImage;
	UIImageView* _imageView;
	FBSDKProfilePictureViewState* _lastState;
	BOOL _needsImageUpdate;
	BOOL _placeholderImageIsValid;
	unsigned _pictureMode;
	NSString* _profileID;
}
@property(copy, nonatomic) NSString* profileID;
@property(assign, nonatomic) unsigned pictureMode;
+(id)_imageURLWithState:(id)state;
+(void)_downloadImageWithState:(id)state completionBlock:(id)block;
-(void).cxx_destruct;
-(void)_updateImageWithData:(id)data state:(id)state;
-(void)_setPlaceholderImage;
-(void)_needsImageUpdate;
-(CGSize)_imageSize:(BOOL)size scale:(float)scale;
-(BOOL)_imageShouldFit;
-(void)_configureProfilePictureView;
-(void)_accessTokenDidChangeNotification:(id)_accessToken;
-(void)setNeedsImageUpdate;
-(void)setMode:(unsigned)mode;
-(void)setContentMode:(int)mode;
-(int)contentMode;
-(void)setBounds:(CGRect)bounds;
-(void)dealloc;
-(id)initWithCoder:(id)coder;
-(id)initWithFrame:(CGRect)frame;
@end

