/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface FBSDKBridgeAPICrypto : XXUnknownSuperclass {
}
+(id)_resetCipherKey;
+(id)_cipherKey;
+(void)reset;
+(id)decryptResponseForRequest:(id)request queryParameters:(id)parameters error:(id*)error;
+(void)addCipherKeyToQueryParameters:(id)queryParameters;
-(id)init;
@end

