/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "FBSDKErrorRecoveryAttempting.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

@interface FBSDKErrorRecoveryAttempter : XXUnknownSuperclass <FBSDKErrorRecoveryAttempting> {
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
+(id)recoveryAttempterFromConfiguration:(id)configuration;
-(void)attemptRecoveryFromError:(id)error optionIndex:(unsigned)index delegate:(id)delegate didRecoverSelector:(SEL)selector contextInfo:(void*)info;
-(void)completeRecovery:(BOOL)recovery delegate:(id)delegate didRecoverSelector:(SEL)selector contextInfo:(void*)info;
@end

