/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSData, NSString;

@interface FBSDKGraphRequestDataAttachment : XXUnknownSuperclass {
	NSString* _contentType;
	NSData* _data;
	NSString* _filename;
}
@property(readonly, copy, nonatomic) NSString* filename;
@property(readonly, assign, nonatomic) NSData* data;
@property(readonly, copy, nonatomic) NSString* contentType;
-(void).cxx_destruct;
-(id)init;
-(id)initWithData:(id)data filename:(id)filename contentType:(id)type;
@end

