/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SKProductsRequestDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class SKProductsRequest, SKPaymentTransaction, NSString;

@interface FBSDKPaymentProductRequestor : XXUnknownSuperclass <SKProductsRequestDelegate> {
	SKPaymentTransaction* _transaction;
	SKProductsRequest* _productRequest;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) SKProductsRequest* productRequest;
@property(retain, nonatomic) SKPaymentTransaction* transaction;
+(void)initialize;
-(void).cxx_destruct;
-(void)logImplicitPurchaseEvent:(id)event valueToSum:(double)sum parameters:(id)parameters;
-(void)cleanUp;
-(void)request:(id)request didFailWithError:(id)error;
-(void)requestDidFinish:(id)request;
-(void)productsRequest:(id)request didReceiveResponse:(id)response;
-(void)logTransactionEvent:(id)event;
-(id)getTruncatedString:(id)string;
-(void)resolveProducts;
-(id)initWithTransaction:(id)transaction;
@end

