/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "LHSprite.h"

@class HSParticleSystemQuad;

__attribute__((visibility("hidden")))
@interface FireBowl : LHSprite {
	float runningTime;
	float warmUpTime;
	BOOL active;
	b2Fixture* sensor;
	HSParticleSystemQuad* fire;
}
-(void).cxx_destruct;
-(void)postUpdate:(float)update;
-(BOOL)trigger:(b2Fixture*)trigger;
-(void)cleanup;
-(void)postInitialization;
@end

