/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "LHSprite.h"


__attribute__((visibility("hidden")))
@interface Flipper : LHSprite {
	b2RevoluteJoint* joint;
	int sgn;
	CGSize screenSize;
	CGPoint centerOfScreen;
}
-(void)unTrigger;
-(void)trigger;
-(void)postInitialization;
-(void)cleanup;
@end

