/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "Buoyant.h"

@class HSParticleSystemQuad;

__attribute__((visibility("hidden")))
@interface GlassBall : Buoyant {
	BOOL triggered;
	BOOL remove;
	HSParticleSystemQuad* q;
	BOOL touched;
}
@property(assign, nonatomic) BOOL touched;
-(void).cxx_destruct;
-(void)postUpdate:(float)update;
-(void)trigger;
-(void)break;
-(void)postInitialization;
-(void)cleanup;
@end

