/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "Boom-Structs.h"

@class UIWindow;

__attribute__((visibility("hidden")))
@interface HSAlertOverlayWindow : XXUnknownSuperclass {
	UIWindow* oldKeyWindow;
}
@property(retain, nonatomic) UIWindow* oldKeyWindow;
-(void).cxx_destruct;
-(void)dealloc;
-(void)drawRect:(CGRect)rect;
-(void)resignKeyWindow;
-(void)makeKeyAndVisible;
@end

