/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "CCNode.h"
#import "Boom-Structs.h"

@class NSMutableArray;

__attribute__((visibility("hidden")))
@interface HSFillNode : CCNode {
	NSMutableArray* _sprites;
	CGRect _frame;
	float firstX;
	float lastX;
	float width;
}
+(id)fillNodeWithSprite:(id)sprite;
-(void).cxx_destruct;
-(void)visit;
-(id)initWithSprite:(id)sprite;
-(id)initWithSprite:(id)sprite frame:(CGRect)frame;
@end

