/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



@protocol HSIAPManagerRestoreProtocol
-(void)restoreFinished:(BOOL)finished;
-(void)restoreCallback:(BOOL)callback productIdentifier:(id)identifier;
@end

