/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "HSLabelTTF.h"


__attribute__((visibility("hidden")))
@interface HSLabelWithStroke : HSLabelTTF {
	BOOL rendered;
}
+(id)label:(id)label font:(id)font size:(float)size color:(ccColor3B)color strokeSize:(float)size5 strokeColor:(ccColor3B)color6;
-(void)setAntiAliasTexParameters;
@end

