/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface HSLocalytics : XXUnknownSuperclass {
}
+(void)tag:(id)tag attribute:(id)attribute;
+(void)tag:(id)tag attributes:(id)attributes;
+(void)tag:(id)tag value:(id)value;
+(void)tag:(id)tag;
+(void)tagOnce:(id)once attribute:(id)attribute;
+(void)tagOnce:(id)once attributes:(id)attributes;
+(void)tagOnce:(id)once;
+(id)createAttributesDictionary:(id)dictionary vaList:(void*)list;
@end

