/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableDictionary, AFHTTPClient, NSDictionary, NSString;
@protocol HSNewsDelegate;

__attribute__((visibility("hidden")))
@interface HSNews : XXUnknownSuperclass {
	NSString* language;
	id<HSNewsDelegate> delegate;
	int lastReadTimestamp;
	NSDictionary* articles;
	NSDictionary* imageFiles;
	AFHTTPClient* client;
	BOOL downloadingNews;
	NSDictionary* downloadedArticles;
	NSMutableDictionary* downloadedArticlesImageFiles;
	int downloadedNewArticlesCount;
	int waitingForImageDownloads;
	NSString* requestUrl;
}
@property(retain, nonatomic) id delegate;
@property(readonly, assign, nonatomic) NSDictionary* imageFiles;
+(void)resetInstance;
+(id)sharedInstance;
+(void)showOnlyAppIconBadgeOnPopupNews;
+(void)setAppId:(id)anId;
+(void)setHost:(id)host;
-(void).cxx_destruct;
-(id)getActiveSplash;
-(void)showSplashNotification;
-(void)showPopupArticle;
-(id)articles;
-(void)downloadComplete;
-(void)stopSync;
-(void)fetchLatestUpdates;
-(void)fetchLatestUpdatesWithCompletionHandler:(id)completionHandler;
-(void)markNewsAsRead;
-(unsigned)numOfUnreadSplashArticles;
-(unsigned)numOfUnreadPopupArticles;
-(unsigned)numOfUnreadArticles;
-(BOOL)hasNews;
-(void)removeDelegate:(id)delegate;
-(void)load;
-(void)archive;
-(id)init;
@end

