/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "CCLayerColor.h"


__attribute__((visibility("hidden")))
@interface HSOverlay : CCLayerColor {
	unsigned char baseOpacity;
}
-(void)updateColor;
-(id)initWithColor:(ccColor4B)color width:(float)width height:(float)height;
@end

