/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableDictionary;

__attribute__((visibility("hidden")))
@interface HSParticleManager : XXUnknownSuperclass {
	NSMutableDictionary* particleSystems;
}
+(void)resetInstance;
+(id)sharedInstance;
-(void).cxx_destruct;
-(id)getParticleSystem:(id)system;
-(void)cache:(unsigned)cache particleSystems:(id)systems forNode:(id)node withZ:(int)z;
-(void)cache:(unsigned)cache particleSystems:(id)systems forNode:(id)node withZ:(int)z scheduled:(BOOL)scheduled;
-(id)init;
@end

