/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "CCRGBAProtocol.h"
#import "CCParticleSystemQuad.h"

@class NSArray, CCTextureAtlas, NSString;

__attribute__((visibility("hidden")))
@interface HSParticleSystemQuad : CCParticleSystemQuad <CCRGBAProtocol> {
	unsigned char opacity_;
	ccColor3B color_;
	CCTextureAtlas* textureAtlas_;
	NSString* plistFile_;
	BOOL pendingDone;
	NSArray* animationFrames_;
	float animationFrameDelay;
	float animationTimer;
	unsigned animationFrameIndex;
	id doneBlock_;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) BOOL pendingDone;
@property(copy, nonatomic) id doneBlock;
@property(assign, nonatomic) ccColor3B color;
@property(assign, nonatomic) unsigned char opacity;
-(void).cxx_destruct;
-(void)update:(float)update;
-(void)stopSystem;
-(void)setAnimationFrames:(id)frames delayPerFrame:(float)frame;
-(void)dealloc;
-(id)initWithFile:(id)file;
-(id)initWithTotalParticles:(unsigned)totalParticles;
-(void)setBatchNode:(id)node;
@end

