/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableArray, HSParticleSystemQuad;

__attribute__((visibility("hidden")))
@interface HSParticleSystem : XXUnknownSuperclass {
	unsigned idx;
	NSMutableArray* quadArray;
}
@property(readonly, assign, nonatomic) HSParticleSystemQuad* nextQuad;
@property(retain, nonatomic) NSMutableArray* quadArray;
-(void).cxx_destruct;
-(id)init;
@end

