/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "HSAdjustedOpacityNode.h"


__attribute__((visibility("hidden")))
@interface HSPaddedNode : HSAdjustedOpacityNode {
}
+(id)paddedNodeWithNode:(id)node vertical:(float)vertical horizontal:(float)horizontal;
+(id)paddedNodeWithNode:(id)node top:(float)top right:(float)right bottom:(float)bottom left:(float)left;
@end

