/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "CCTargetedTouchDelegate.h"
#import "Boom-Structs.h"
#import "HSAdjustedOpacityLayer.h"

@class NSDate, NSMutableArray, NSString;
@protocol HSPickerScrollDelegate;

__attribute__((visibility("hidden")))
@interface HSPickerScrollLayer : HSAdjustedOpacityLayer <CCTargetedTouchDelegate> {
	int currentPage;
	NSMutableArray* arrayPages;
	CGRect touchArea;
	CGPoint touchStartedPoint;
	CGPoint touchStartedWorldPosition;
	BOOL isTouching;
	BOOL didMove;
	int totalPagesCount;
	NSDate* touchStartedAt;
	HSAdjustedOpacityLayer* world;
	id<HSPickerScrollDelegate> delegate;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) CGRect touchArea;
@property(assign, nonatomic) int totalPagesCount;
@property(assign, nonatomic) id<HSPickerScrollDelegate> delegate;
@property(retain, nonatomic) NSMutableArray* arrayPages;
@property(assign, nonatomic) int currentPage;
-(void).cxx_destruct;
-(void)onDoneSpinning;
-(void)spin:(float)spin rate:(float)rate repeat:(int)repeat stopPage:(int)page;
-(void)moveToPagePosition:(BOOL)pagePosition;
-(void)setCurrentPage:(int)page animated:(BOOL)animated;
-(void)ccTouchCancelled:(id)cancelled withEvent:(id)event;
-(void)ccTouchEnded:(id)ended withEvent:(id)event;
-(void)ccTouchMoved:(id)moved withEvent:(id)event;
-(BOOL)ccTouchBegan:(id)began withEvent:(id)event;
-(BOOL)containsTouchLocation:(id)location;
-(void)makePages;
-(void)onExit;
-(void)onEnter;
-(id)init;
@end

