/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "NSObject.h"


@protocol HSPickerViewDelegate <NSObject>
-(id)overlayImage:(id)image;
-(CGSize)sizeOfPickerView:(id)pickerView;
-(float)spaceBetweenComponents:(id)components;
-(void)pickerView:(id)view didSelectRow:(int)row inComponent:(int)component;
-(id)pickerView:(id)view nodeForRow:(int)row forComponent:(int)component reusingNode:(id)node;
-(float)pickerView:(id)view widthForComponent:(int)component;
-(float)pickerView:(id)view rowHeightForComponent:(int)component;
@optional
-(void)onDoneSpinning:(id)spinning component:(int)component;
@end

