/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

__attribute__((visibility("hidden")))
@interface HSReachability : XXUnknownSuperclass {
	NSString* hostname;
	XXStruct_ecqpFB reachabilityForHostname;
	XXStruct_ecqpFB reachabilityForInternet;
	XXStruct_ecqpFB reachabilityForLocalWiFi;
}
@property(readonly, assign, nonatomic) XXStruct_ecqpFB reachabilityForLocalWiFi;
@property(readonly, assign, nonatomic) XXStruct_ecqpFB reachabilityForInternet;
@property(readonly, assign, nonatomic) XXStruct_ecqpFB reachabilityForHostname;
@property(readonly, assign, nonatomic) NSString* hostname;
+(id)sharedClient;
+(id)startSharedClient:(id)client;
-(void).cxx_destruct;
-(void)updateStatus:(XXStruct_ecqpFB*)status;
-(void)networkStatusForFlags:(unsigned)flags status:(XXStruct_ecqpFB*)status;
-(void)localWiFiStatusForFlags:(unsigned)flags status:(XXStruct_ecqpFB*)status;
-(void)reachabilityChanged;
-(void)stopNotifierForReachabilityRef:(SCNetworkReachabilityRef)reachabilityRef;
-(BOOL)startNotifierForReachabilityRef:(SCNetworkReachabilityRef)reachabilityRef;
-(void)stop;
-(void)start;
-(void)setupReachabilityForLocalWiFi;
-(void)setupReachabilityForInternetConnection;
-(void)setupReachabilityForHostname;
-(void)fakeReachable;
-(id)initWithHost:(id)host;
@end

