/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "CCMenuItem.h"
#import "Boom-Structs.h"

@class HSScale9Sprite;

__attribute__((visibility("hidden")))
@interface HSRoundedRectMenuItem : CCMenuItem {
	HSScale9Sprite* bg;
}
-(void).cxx_destruct;
-(void)unselected;
-(void)selected;
-(void)setOpacity:(unsigned char)opacity;
-(void)setContentSize:(CGSize)size;
-(id)initWithBlock:(id)block;
@end

