/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "CCLayer.h"
#import "Boom-Structs.h"

@class NSMutableArray;

__attribute__((visibility("hidden")))
@interface HSSwipeLayer : CCLayer {
	NSMutableArray* swipeLayers;
	int currentSwipeLayer;
}
-(void).cxx_destruct;
-(void)reset;
-(unsigned)size;
-(id)swipeLayerAt:(unsigned)at;
-(void)swipeTo:(unsigned)to duration:(float)duration onComplete:(id)complete;
-(void)swipeTo:(unsigned)to duration:(float)duration;
-(void)setCurrentSwipeLayer:(unsigned)layer;
-(int)currentSwipeLayerIndex;
-(id)currentSwipeLayer;
-(void)removeSwipeLayer:(unsigned)layer;
-(void)addSwipeLayer:(id)layer;
-(id)initWithPosition:(CGPoint)position dimension:(CGSize)dimension;
-(id)init;
@end

