/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "HSScrollView.h"

@class NSMutableDictionary, NSMutableArray, CCAction;
@protocol HSTableViewDataSource, HSTableViewDelegate;

__attribute__((visibility("hidden")))
@interface HSTableView : HSScrollView {
	NSMutableArray* visibleCells;
	NSMutableDictionary* reusableCells;
	BOOL dirty;
	float lastScrollPos;
	BOOL animating;
	float lastAmount;
	unsigned repositionIndex;
	int touchState;
	CCNode* selectedItem;
	CGPoint touchDownLocation;
	unsigned char opacity;
	CCAction* scrollAction;
	BOOL _isAnimating;
	BOOL _isBeingRemoved;
	BOOL _isBeingAdded;
	BOOL _isOverlay;
	BOOL _touchesPassThrough;
	BOOL _destruct;
	id<HSTableViewDelegate> delegate_;
	id<HSTableViewDataSource> dataSource_;
}
@property(assign, nonatomic) BOOL destruct;
@property(assign, nonatomic) BOOL touchesPassThrough;
@property(assign, nonatomic) BOOL isOverlay;
@property(assign, nonatomic) BOOL isBeingAdded;
@property(assign, nonatomic) BOOL isBeingRemoved;
@property(assign, nonatomic) BOOL isAnimating;
@property(retain, nonatomic) id<HSTableViewDelegate> delegate;
@property(retain, nonatomic) id<HSTableViewDataSource> dataSource;
-(void).cxx_destruct;
-(void)claimTouch:(id)touch;
-(void)ccTouchMoved:(id)moved withEvent:(id)event;
-(void)ccTouchCancelled:(id)cancelled withEvent:(id)event;
-(void)ccTouchEnded:(id)ended withEvent:(id)event;
-(BOOL)ccTouchBegan:(id)began withEvent:(id)event;
-(id)itemForTouch:(id)touch;
-(id)indexPathForSelectedRow;
-(void)deselectRowAtIndexPath:(id)indexPath animated:(BOOL)animated;
-(void)selectRowAtIndexPath:(id)indexPath animated:(BOOL)animated scrollPosition:(int)position;
-(id)visibleCells;
-(void)setOpacity:(unsigned char)opacity;
-(void)visit;
-(float)upperBound;
-(float)lowerBound;
-(id)dequeueReusableCellWithIdentifier:(id)identifier;
-(int)numberOfRowsInSection:(int)section;
-(int)numberOfSections;
-(void)scrollToRowAtIndexPath:(id)indexPath atScrollPosition:(int)scrollPosition animated:(BOOL)animated;
-(BOOL)below:(float)below;
-(BOOL)above:(float)above;
-(BOOL)visible:(float)visible;
-(void)setScrollPosition:(CGPoint)position;
-(void)setScrollpos:(float)scrollpos;
-(void)deleteRowAtIndexPath:(id)indexPath withRowAnimation:(int)rowAnimation;
-(void)setReposition:(float)reposition;
-(id)deleteVisibleNodeAtIndex:(unsigned)index;
-(int)indexForNodeAtIndexPath:(id)indexPath;
-(id)indexPathForCell:(id)cell;
-(void)reloadData;
-(void)reload;
-(void)resize;
-(float)calculateHeight;
-(void)cleanup;
-(id)initWithSize:(CGSize)size;
@end

