/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface ImpulseWithTarget : XXUnknownSuperclass {
	b2Body* body;
	b2Vec2 impulse;
	b2Vec2 point;
}
-(id).cxx_construct;
@end

