/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UITextViewDelegate.h"
#import "Boom-Structs.h"
#import "CCMenu.h"

@class UITextView, HSAdjustedSprite, NSString;

__attribute__((visibility("hidden")))
@interface InputSpeechBubble : CCMenu <UITextViewDelegate> {
	UITextView* inputView;
	UITextView* sizingView;
	HSAdjustedSprite* bubble;
	HSAdjustedSprite* plusSign;
	id doneBlock;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(copy, nonatomic) id doneBlock;
-(void).cxx_destruct;
-(BOOL)textView:(id)view shouldChangeTextInRange:(NSRange)range replacementText:(id)text;
-(void)cancelBubble;
-(void)submitWithBubble;
-(void)purchase100WithIAP;
-(void)purchase25WithIAP;
-(void)purchaseItem:(id)item amount:(id)amount;
-(void)purchaseWithCoins;
-(void)triggerInput;
-(void)cleanup;
-(id)init;
@end

