/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class CCSpriteBatchNode, NSMutableArray, NSMutableString;

__attribute__((visibility("hidden")))
@interface LHAnimationNode : XXUnknownSuperclass {
	NSMutableString* uniqueName;
	NSMutableString* imageName;
	bool loop;
	float speed;
	int repetitions;
	bool startAtLaunch;
	NSMutableArray* frames;
	NSMutableArray* framesInfo;
	NSMutableString* imageFolder;
	CCSpriteBatchNode* batchNode;
	BOOL computed;
}
@property(assign) bool startAtLaunch;
@property(assign) int repetitions;
@property(assign) float speed;
@property(assign) bool loop;
+(id)animationNodeWithUniqueName:(id)uniqueName;
-(void).cxx_destruct;
-(void)setFrame:(int)frame onSprite:(id)sprite;
-(void)setAnimationTexturePropertiesOnSprite:(id)sprite;
-(int)numberOfFrames;
-(void)runAnimationOnSprite:(id)sprite startingFromFrame:(int)frame withNotifierObj:(id)notifierObj notifierSel:(SEL)sel notifOnLoop:(bool)loop;
-(void)setBatchNode:(id)node;
-(id)frames;
-(void)computeFrames;
-(void)setFramesInfo:(id)info;
-(void)setImageName:(id)name;
-(id)imageName;
-(id)uniqueName;
-(void)setUniqueName:(id)name;
-(void)setImageFolder:(id)folder;
-(id)initWithUniqueName:(id)uniqueName;
-(void)dealloc;
@end

