/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "HSOpacityLayer.h"


__attribute__((visibility("hidden")))
@interface LHNode : HSOpacityLayer {
	b2World* world;
}
@property(assign, nonatomic) b2World* world;
@end

