/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "CCNode.h"
#import "Boom-Structs.h"

@class CCArray, LevelHelperLoader, LHSprite, NSString;

__attribute__((visibility("hidden")))
@interface LHParallaxNode : CCNode {
	bool isContinuous;
	int direction;
	float speed;
	CGPoint lastPosition;
	NSString* uniqueName;
	id movedEndListenerObj;
	SEL movedEndListenerSEL;
	CGSize winSize;
	bool paused;
	float screenNumberOnTheRight;
	float screenNumberOnTheLeft;
	float screenNumberOnTheTop;
	float screenNumberOnTheBottom;
	CCArray* sprites;
	LevelHelperLoader* lhLoader;
	bool removeSpritesOnDelete;
	LHSprite* followedSprite;
	CGPoint lastFollowedSpritePosition;
	bool followChangeX;
	bool followChangeY;
}
@property(assign) bool paused;
@property(assign) float speed;
@property(readonly, assign) int direction;
@property(readonly, assign) bool isContinuous;
+(id)nodeWithDictionary:(id)dictionary loader:(id)loader;
-(void).cxx_destruct;
-(void)tick:(float)tick;
-(void)repositionPoint:(id)point frameTime:(double)time;
-(CGSize)getBounds:(float)bounds height:(float)height angle:(float)angle;
-(id)bodiesInNode;
-(id)spritesInNode;
-(void)followSprite:(id)sprite changePositionOnX:(bool)x changePositionOnY:(bool)y;
-(id)uniqueName;
-(void)registerSpriteHasMovedToEndListener:(id)endListener selector:(SEL)selector;
-(void)removeChild:(id)child;
-(void)addNode:(id)node parallaxRatio:(CGPoint)ratio;
-(void)addSprite:(id)sprite parallaxRatio:(CGPoint)ratio;
-(id)createParallaxPointObjectWithNode:(id)node ratio:(CGPoint)ratio;
-(id)initWithDictionary:(id)dictionary loader:(id)loader;
-(void)dealloc;
-(void)setRemoveChildSprites:(bool)sprites;
@end

