/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "Boom-Structs.h"

@class UIEvent, UITouch, LHBezierNode, LHSprite;

__attribute__((visibility("hidden")))
@interface LHTouchInfo : XXUnknownSuperclass {
	CGPoint relativePoint;
	CGPoint glPoint;
	CGPoint delta;
	UIEvent* event;
	UITouch* touch;
	LHSprite* sprite;
	LHBezierNode* bezier;
}
@property(assign) UITouch* touch;
@property(assign) UIEvent* event;
@property(assign) LHBezierNode* bezier;
@property(assign) LHSprite* sprite;
@property(assign) CGPoint delta;
@property(assign) CGPoint glPoint;
@property(assign) CGPoint relativePoint;
+(id)touchInfo;
-(id)initLHTouchInfo;
@end

