/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "HSMenuLayer.h"

@class LoadingPopup;

__attribute__((visibility("hidden")))
@interface LoadingScene : HSMenuLayer {
	LoadingPopup* loading;
}
@property(readonly, assign, nonatomic) LoadingPopup* loading;
+(id)scene;
-(void).cxx_destruct;
-(void)showLoading;
-(void)cleanup;
-(id)initWithMenu:(id)menu;
@end

