/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "HSMenuLayer.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface NotEnoughCoins : HSMenuLayer {
	unsigned coinsNeeded;
	NSString* successfulPurchaseButtonLabel;
	id onSuccess;
}
+(id)layerWithMenu:(id)menu coinsNeeded:(unsigned)needed successfulPurchaseButtonLabel:(id)label onSuccess:(id)success;
-(void).cxx_destruct;
-(void)showNotEnoughCoins:(id)coins;
-(void)notEnoughCoins;
-(id)transitionOutAction;
-(id)transitionInAction;
-(id)initWithMenu:(id)menu coinsNeeded:(unsigned)needed successfulPurchaseButtonLabel:(id)label onSuccess:(id)success;
-(id)initWithMenu:(id)menu;
@end

