/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "LHSprite.h"

@class HSLabelSafeBMFont;

__attribute__((visibility("hidden")))
@interface PickupGate : LHSprite {
	HSLabelSafeBMFont* counter;
	unsigned pickupCount;
}
@property(assign, nonatomic) unsigned pickupCount;
-(void).cxx_destruct;
-(void)visit;
-(void)pickup;
-(void)cleanup;
@end

