/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "HSParticleSystemQuad.h"
#import "Boom-Structs.h"


__attribute__((visibility("hidden")))
@interface RecordStarSystem : HSParticleSystemQuad {
	float radius;
	unsigned extraParticles;
}
@property(assign, nonatomic) unsigned extraParticles;
@property(assign, nonatomic) float radius;
-(BOOL)addParticle;
-(void)initParticle:(sCCParticle*)particle;
-(id)initWithDictionary:(id)dictionary;
@end

