/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableArray, NSMutableDictionary, NSString;

__attribute__((visibility("hidden")))
@interface RRVerificationController : XXUnknownSuperclass {
	NSMutableDictionary* transactionsReceiptStorageDictionary;
	NSMutableArray* verificationsInProgress;
	NSString* itcContentProviderSharedSecret;
}
@property(retain) NSString* itcContentProviderSharedSecret;
+(id)sharedInstance;
-(void).cxx_destruct;
-(void)transactionVerifier:(id)verifier didFailWithError:(id)error;
-(void)transactionVerifier:(id)verifier didDetermineValidity:(BOOL)validity;
-(BOOL)verifyPurchase:(id)purchase withDelegate:(id)delegate error:(out id*)error;
-(id)init;
@end

