/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "Buoyant.h"

@class MappedSprite, HSParticleSystemQuad;

__attribute__((visibility("hidden")))
@interface SoftBox : Buoyant {
	MappedSprite* boxSprite;
	b2Body* bodies[8];
	float width;
	float height;
	float boxScale;
	BOOL presentOpened;
	HSParticleSystemQuad* q;
}
-(void).cxx_destruct;
-(void)drawSprite;
-(void)setPosition:(CGPoint)position rotation:(float)rotation;
-(void)update:(float)update;
-(void)postInitialization;
-(void)cleanup;
@end

