/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "Buoyant.h"

@class MappedSprite;

__attribute__((visibility("hidden")))
@interface SoftBall : Buoyant {
	MappedSprite* ballSprite;
	b2Body** bodies;
	float surfaceRadius;
}
-(void).cxx_destruct;
-(void)postUpdate:(float)update;
-(void)postInitialization;
-(void)cleanup;
@end

