/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "CCScene.h"


__attribute__((visibility("hidden")))
@interface SplashScene : CCScene {
}
+(id)scene;
-(void)soundInit;
-(void)bmFontInit;
-(void)prepareAssets;
-(void)onEnter;
-(void)prepareAllAssets;
-(void)onEnterTransitionDidFinish;
-(id)init;
@end

