/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableDictionary;

__attribute__((visibility("hidden")))
@interface SpriteHelperLoader : XXUnknownSuperclass {
	NSMutableDictionary* shSprites;
	NSMutableDictionary* shAnimations;
	NSMutableDictionary* batchInfo;
	int batchOrder;
}
-(void)loadSpriteHelperSceneFile:(id)file inDirectory:(id)directory imgSubfolder:(id)subfolder;
-(b2Body*)b2BodyFromDictionary:(id)dictionary spriteProperties:(id)properties data:(id)data world:(b2World*)world;
-(void)setFixtureDefPropertiesFromDictionary:(id)dictionary fixture:(b2FixtureDef*)fixture;
-(void)setSpriteProperties:(id)properties spriteProperties:(id)properties2 position:(CGPoint)position;
-(id)spriteFromDictionary:(id)dictionary;
-(void)dealloc;
-(oneway void)release;
-(id)runAnimationWithUniqueName:(id)uniqueName onBody:(b2Body*)body;
-(id)runAnimationWithUniqueName:(id)uniqueName onBody:(b2Body*)body endNotificationSEL:(SEL)sel endNotificationObj:(id)obj;
-(id)runAnimationWithUniqueName:(id)uniqueName onSprite:(id)sprite;
-(id)runAnimationWithUniqueName:(id)uniqueName onSprite:(id)sprite endNotificationSEL:(SEL)sel endNotificationObj:(id)obj;
-(b2Body*)bodyInBatchWithUniqueName:(id)uniqueName atPosition:(CGPoint)position inLayer:(id)layer world:(b2World*)world;
-(id)spriteInBatchWithUniqueName:(id)uniqueName atPosition:(CGPoint)position inLayer:(id)layer;
-(b2Body*)bodyWithUniqueName:(id)uniqueName atPosition:(CGPoint)position inLayer:(id)layer world:(b2World*)world;
-(id)spriteWithUniqueName:(id)uniqueName atPosition:(CGPoint)position inLayer:(id)layer;
-(id)initWithContentOfFile:(id)file sceneSubfolder:(id)subfolder;
-(id)initWithContentOfFile:(id)file;
@end

