/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "TrialGameControllerDelegate.h"
#import "HSPickerViewDataSource.h"
#import "HSPickerViewDelegate.h"
#import "HSMenuLayer.h"

@class CCMenu, HSPickerView, HSParticleSystemQuad, Wheely, NSDictionary, HSAdjustedSprite, HSMenuItem, SuperStarSunBeams, HSLabelSafeBMFont, NSString, TextButton;

__attribute__((visibility("hidden")))
@interface StoreDialog : HSMenuLayer <HSPickerViewDataSource, HSPickerViewDelegate, TrialGameControllerDelegate> {
	NSString* disableSuperLabel;
	HSAdjustedSprite* dialog;
	TextButton* coinsButton;
	TextButton* iapButton;
	HSLabelSafeBMFont* orLabel;
	HSLabelSafeBMFont* superPowerLabel;
	HSLabelSafeBMFont* superPowerDisabledLabel;
	HSLabelSafeBMFont* superPowerDescription;
	HSMenuItem* backButton;
	Wheely* wheely;
	HSPickerView* picker;
	NSString* pickedHub;
	NSString* pickedEngine;
	NSString* pickedWheel;
	NSDictionary* pickedHubItem;
	NSDictionary* pickedEngineItem;
	NSDictionary* pickedWheelItem;
	HSParticleSystemQuad* superPowerStarSystem;
	HSParticleSystemQuad* hubSystem;
	HSParticleSystemQuad* engineSystem;
	HSParticleSystemQuad* wheelSystem;
	NSString* newHub;
	NSString* newEngine;
	NSString* newWheel;
	SuperStarSunBeams* superStarSunBeams;
	CCMenu* menuItems;
	BOOL backToMenuTrial;
	id completedBlock;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(copy, nonatomic) id completedBlock;
@property(assign, nonatomic) BOOL backToMenuTrial;
-(void).cxx_destruct;
-(id)controllerItemForIndex:(unsigned)index;
-(id)controllerItemConfig;
-(unsigned)controllerDefaultItem;
-(void)controllerCancel;
-(void)postFirstVisit;
-(void)postTransitionIn;
-(id)overlayImage:(id)image;
-(CGSize)sizeOfPickerView:(id)pickerView;
-(float)spaceBetweenComponents:(id)components;
-(void)pickerView:(id)view didSelectRow:(int)row inComponent:(int)component;
-(id)pickerView:(id)view nodeForRow:(int)row forComponent:(int)component reusingNode:(id)node;
-(float)pickerView:(id)view widthForComponent:(int)component;
-(float)pickerView:(id)view rowHeightForComponent:(int)component;
-(int)pickerView:(id)view numberOfRowsInComponent:(int)component;
-(int)numberOfComponentsInPickerView:(id)pickerView;
-(void)newWheel:(float)wheel;
-(void)newEngine:(float)engine;
-(void)newHub:(float)hub;
-(void)pickOutfit:(BOOL)outfit;
-(void)back;
-(void)updateCoins;
-(void)showOutfitWithHub:(id)hub engine:(id)engine wheel:(id)wheel;
-(void)buildSlotMachine;
-(void)triggerIap;
-(void)onDoneSpinning:(id)spinning component:(int)component;
-(void)buildPrice;
-(void)buildSuperPower;
-(void)buildPreview;
-(void)onEnter;
-(void)offerEvents;
-(void)cleanup;
-(id)initWithMenu:(id)menu disabledSuperLabel:(id)label;
-(id)initWithMenu:(id)menu;
@end

