/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "TrialGameControllerDelegate.h"
#import "HSMenuLayer.h"
#import "Boom-Structs.h"

@class NSMutableArray, HSAdjustedSprite;

__attribute__((visibility("hidden")))
@interface StoreGetCoinsDialog : HSMenuLayer <TrialGameControllerDelegate> {
	HSAdjustedSprite* dialog;
	HSAdjustedSprite* loading;
	NSMutableArray* buttons;
}
-(void).cxx_destruct;
-(id)controllerItemForIndex:(unsigned)index;
-(id)controllerItemConfig;
-(unsigned)controllerDefaultItem;
-(void)controllerCancel;
-(void)postFirstVisit;
-(void)postTransitionIn;
-(void)cleanup;
-(void)showConfirmDialog:(id)dialog;
-(void)purchaseItem:(id)item;
-(void)earnCoins;
-(void)buildInAppItems;
-(id)createCoinInAppProductId:(id)appProductId image:(id)image offset:(CGPoint)offset amount:(unsigned)amount moreValueTag:(unsigned)tag moreValuePosition:(CGPoint)position twinkle:(id)twinkle;
-(void)back;
-(void)updateCoins;
-(void)buildStore;
-(void)showError;
-(void)stopLoading;
-(void)update:(float)update;
-(void)loadStore;
-(void)onEnter;
-(id)initWithMenu:(id)menu;
@end

