/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "HSMenuItem.h"

@class HSBadgeIndicator;

__attribute__((visibility("hidden")))
@interface StoreButton : HSMenuItem {
	HSBadgeIndicator* infoBadge;
}
+(id)storeButtonWithMenu:(id)menu localyticTag:(id)tag block:(id)block disabledSuperLabel:(id)label;
+(id)storeButtonWithMenu:(id)menu localyticTag:(id)tag block:(id)block;
+(id)storeButtonWithMenu:(id)menu localyticTag:(id)tag disabledSuperLabel:(id)label;
+(id)storeButtonWithMenu:(id)menu localyticTag:(id)tag;
-(void).cxx_destruct;
-(void)setupButton;
-(void)cleanup;
-(void)onEnter;
@end

