/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableDictionary;

__attribute__((visibility("hidden")))
@interface StrokeCache : XXUnknownSuperclass {
	NSMutableDictionary* cache;
}
+(id)sharedCache;
-(void).cxx_destruct;
-(void)reset;
-(id)objectForKey:(id)key;
-(void)cacheObject:(id)object forKey:(id)key;
-(id)init;
@end

