/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class Player, NSNumber, NSString;

__attribute__((visibility("hidden")))
@interface SuperStar : XXUnknownSuperclass {
}
@property(retain, nonatomic) Player* player;
@property(retain, nonatomic) NSString* theme;
@property(retain, nonatomic) NSNumber* count;
@end

