/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "CCSprite.h"

@class CCLabelBMFont;

__attribute__((visibility("hidden")))
@interface TestTableCell : CCSprite {
	CCLabelBMFont* labelLeft;
	CCLabelBMFont* labelRight;
}
@property(retain, nonatomic) CCLabelBMFont* labelRight;
@property(retain, nonatomic) CCLabelBMFont* labelLeft;
-(void).cxx_destruct;
@end

