/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "HSAdjustedSprite.h"


__attribute__((visibility("hidden")))
@interface ThemeSign : HSAdjustedSprite {
}
+(id)signWithTheme:(id)theme totalTime:(id)time;
+(id)signWithTheme:(id)theme;
-(void)setupExtremeWithTime:(id)time;
-(void)setupSimpleExtreme;
-(void)setupFestivalWithTime:(id)time;
-(void)setupSimpleFestival;
-(void)setupFactoryWithTime:(id)time;
-(void)setupPyramidWithTime:(id)time;
-(void)setupCityWithTime:(id)time;
-(void)setupIceWithTime:(id)time;
-(void)setupJungleWithTime:(id)time;
@end

