/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableDictionary, NSMutableSet, NSMutableArray, NSString;
@protocol TMXGeneratorDelegate;

__attribute__((visibility("hidden")))
@interface TMXGenerator : XXUnknownSuperclass {
	int highestGID;
	NSMutableDictionary* tileSets;
	NSMutableDictionary* mapAttributes;
	NSMutableArray* objectGroups;
	NSMutableArray* layers;
	NSString* path;
	NSMutableSet* copiedAtlasNames;
	id<TMXGeneratorDelegate> delegate_;
}
@property(retain, nonatomic) id<TMXGeneratorDelegate> delegate;
+(id)makeObjectWithName:(id)name type:(id)type x:(int)x y:(int)y width:(int)width height:(int)height properties:(id)properties;
+(id)tileSetWithImage:(id)image named:(id)named width:(int)width height:(int)height tileSpacing:(int)spacing;
+(id)layerNamed:(id)named width:(int)width height:(int)height data:(id)data visible:(BOOL)visible;
+(void)writeTMXFileWithXML:(id)xml fileName:(id)name;
+(id)XMLWithAttributes:(id)attributes tilesets:(id)tilesets layers:(id)layers objectGroups:(id)groups;
+(id)tileSetsToXML:(id)xml;
+(id)layersToXML:(id)xml;
+(id)objectGroupsToXML:(id)xml;
+(id)propertiesToXML:(id)xml;
-(void)saveSampleMapWithPath:(id)path;
-(BOOL)generateAndSaveTMXMap:(id*)map;
-(id)generateMapXML:(id*)xml;
-(id)tileIDFromTileSet:(id)tileSet thatMatchesKey:(id)key property:(id)property;
-(void)addObjectGroupNamed:(id)named width:(int)width height:(int)height objectList:(id)list;
-(BOOL)addTilesetWithImage:(id)image named:(id)named width:(int)width height:(int)height tileSpacing:(int)spacing tileProperties:(id)properties;
-(BOOL)addTilesetWithDictionary:(id)dictionary tileProperties:(id)properties;
-(void)addLayerNamed:(id)named width:(int)width height:(int)height data:(id)data visible:(BOOL)visible;
-(void)addMapAttributesWithPath:(id)path width:(int)width height:(int)height tileWidth:(int)width4 tileHeight:(int)height5 orientation:(id)orientation properties:(id)properties;
-(void)dealloc;
-(id)init;
@end

