/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSArray, TournamentPlayer, NSDictionary, TournamentState;
@protocol TournamentsClientDelegate;

__attribute__((visibility("hidden")))
@interface TournamentsClient : XXUnknownSuperclass {
	TournamentState* state;
	BOOL pendingSuccess;
	BOOL pendingFailure;
	BOOL completedLoaded;
	unsigned authRetries;
	NSDictionary* pendingNotification;
	BOOL syncingHistory;
	BOOL syncing_;
	id<TournamentsClientDelegate> delegate_;
	TournamentPlayer* currentPlayer_;
	NSArray* completed_;
	id updateCallback;
}
@property(copy, nonatomic) id updateCallback;
@property(readonly, assign, nonatomic) NSArray* completed;
@property(retain, nonatomic) TournamentPlayer* currentPlayer;
@property(readonly, assign, nonatomic) BOOL syncing;
@property(retain, nonatomic) id<TournamentsClientDelegate> delegate;
+(void)unbindClient;
+(id)sharedInstance;
+(void)setTournamentUrl:(id)url;
-(void).cxx_destruct;
-(void)resetClient:(BOOL)client;
-(void)updateCompletedWithSuccess:(id)success failure:(id)failure;
-(void)updateCompletedWithSuccess:(id)success failure:(id)failure retryCount:(unsigned)count;
-(void)syncHistory;
-(void)startRaceAgainstPlayer:(id)player;
-(void)startRaceAgainstPlayer:(id)player retryCount:(unsigned)count;
-(void)updateCurrentWithSuccess:(id)success failure:(id)failure;
-(void)updateCurrentWithSuccess:(id)success failure:(id)failure retryCount:(unsigned)count;
-(void)updateCurrentWithTime:(id)time ghost:(id)ghost success:(id)success failure:(id)failure;
-(void)updateCurrentWithTime:(id)time ghost:(id)ghost success:(id)success failure:(id)failure retryCount:(unsigned)count;
-(void)updateSuccess:(id)success callback:(id)callback;
-(void)joinCurrentWithTime:(id)time ghost:(id)ghost success:(id)success failure:(id)failure;
-(void)joinCurrentWithTime:(id)time ghost:(id)ghost success:(id)success failure:(id)failure retryCount:(unsigned)count;
-(void)joinSuccess:(id)success callback:(id)callback;
-(void)syncIfStaleWithSuccess:(id)success failure:(id)failure;
-(void)syncWithSuccess:(id)success failure:(id)failure;
-(void)syncWithSuccess:(id)success failure:(id)failure retryCount:(unsigned)count;
-(void)syncSuccess:(id)success success:(id)success2 failure:(id)failure;
-(void)showNotification:(id)notification;
-(void)gameStateUnlocked;
-(BOOL)handleNotification:(id)notification userTriggered:(BOOL)triggered;
-(id)currentLevel;
-(id)lastActiveTournament;
-(id)currentTournament;
-(unsigned)cleanPlayers;
-(id)init;
@end

