/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "HSGameStateProtocol.h"
#import "TrialGameControllerDelegate.h"
#import "HSTableViewDataSource.h"
#import "HSTableViewDelegate.h"
#import "HSMenuLayer.h"

@class CCMenu, Spinner, Tournament, NSArray, HSTableView, SignPost, HSLabelSafeBMFont, NSString, TournamentsClient;

__attribute__((visibility("hidden")))
@interface TournamentScoreBoard : HSMenuLayer <HSGameStateProtocol, HSTableViewDelegate, HSTableViewDataSource, TrialGameControllerDelegate> {
	TournamentsClient* client;
	Tournament* tournament;
	HSTableView* tableView;
	NSArray* players;
	BOOL syncFailure;
	HSLabelSafeBMFont* timeHeader;
	HSLabelSafeBMFont* timeLabel;
	Spinner* loadingIndicator;
	SignPost* signPost;
	CCMenu* menuItems;
	BOOL reportDelegateAfterVisitAndTableIsReady;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
+(id)sceneWithTournament:(id)tournament ghostTime:(id)time ghost:(id)ghost;
-(void).cxx_destruct;
-(id)controllerItemForIndex:(unsigned)index;
-(id)controllerItemConfig;
-(unsigned)controllerDefaultItem;
-(void)controllerCancel;
-(void)postFirstVisit;
-(void)postTransitionIn;
-(id)menuForUserAttention;
-(BOOL)canGrabUserAttention:(id)attention;
-(void)tournamentsClientSyncFailed;
-(void)tournamentsClientSyncFailedWithRetryBlock:(id)retryBlock;
-(void)tournamentsClientSyncCompleted;
-(void)visit;
-(void)updatePost;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(int)numberOfSectionsInTableView:(id)tableView;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view viewForHeaderInSection:(int)section;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(float)tableView:(id)view heightForHeaderInSection:(int)section;
-(float)tableView:(id)view heightForRowAtIndexPath:(id)indexPath;
-(void)cleanup;
-(void)onExit;
-(void)onEnter;
-(void)createMenu;
-(void)updateTimeLabel;
-(void)reloadScoreBoardCompleted;
-(void)reloadScoreBoard;
-(id)initWithMenu:(id)menu ghostTime:(id)time ghostFileUrl:(id)url;
@end

