/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSNumber, NSString;

__attribute__((visibility("hidden")))
@interface TournamentTempPlayer : XXUnknownSuperclass {
	BOOL _isSelf;
	NSString* nickname;
	NSString* heroStyle;
	NSString* engineStyle;
	NSString* wheelStyle;
	NSNumber* currentTime;
	NSNumber* ghost_version;
	NSNumber* uuid;
}
@property(assign, nonatomic) BOOL isSelf;
@property(retain, nonatomic) NSNumber* uuid;
@property(retain, nonatomic) NSNumber* ghost_version;
@property(retain, nonatomic) NSNumber* currentTime;
@property(retain, nonatomic) NSString* wheelStyle;
@property(retain, nonatomic) NSString* engineStyle;
@property(retain, nonatomic) NSString* heroStyle;
@property(retain, nonatomic) NSString* nickname;
-(void).cxx_destruct;
@end

