/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "HSAdjustedSprite.h"

@class HSLabelWithStroke, HSLabelSafeBMFont, HSMenu, Tournaments, FatTextButton, Tournament;

__attribute__((visibility("hidden")))
@interface TournamentSign : HSAdjustedSprite {
	HSLabelSafeBMFont* timeLabel;
	HSLabelWithStroke* leader;
	HSLabelSafeBMFont* yourPosition;
	Tournament* tournament_;
	FatTextButton* goButton;
	HSMenu* menu_;
	Tournaments* parentNode;
}
@property(readonly, assign, nonatomic) FatTextButton* goButton;
@property(retain, nonatomic) Tournaments* parentNode;
@property(retain, nonatomic) HSMenu* menu;
+(id)tournamentSignWithTournament:(id)tournament block:(id)block;
-(void).cxx_destruct;
-(void)tournamentsClientSyncCompleted;
-(void)cleanup;
-(void)updateTime;
-(id)price:(unsigned)price;
-(void)reloadCurrent;
-(void)setupSign:(id)sign block:(id)block;
-(id)ordinalNumberFormat:(int)format;
@end

