/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "CCScene.h"
#import "HSGameStateProtocol.h"


__attribute__((visibility("hidden")))
@interface TrialScene : CCScene <HSGameStateProtocol> {
}
-(id)menuForUserAttention;
-(BOOL)canGrabUserAttention:(id)attention;
@end

