/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "CCNode.h"
#import "Boom-Structs.h"

@class CCSprite, NSString;

__attribute__((visibility("hidden")))
@interface UnloadableSpriteNode : CCNode {
	NSString* _imageName;
	CGRect _activeRect;
	CCSprite* _sprite;
}
@property(copy) NSString* imageName;
@property(retain) CCSprite* sprite;
+(id)nodeWithImage:(id)image forRect:(CGRect)rect;
-(void)load;
-(void)unload;
-(void)loadedTexture:(id)texture;
-(void)dealloc;
-(CGRect)boundingBox;
-(void)visit;
-(id)initWithImage:(id)image forRect:(CGRect)rect;
@end

