/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import "CCNode.h"
#import "HSJustify.h"
#import "CCTargetedTouchDelegate.h"
#import "CCRGBAProtocol.h"

@class CCMenu, HSParticleSystemQuad, NSMutableArray, CCParticleBatchNode, HSAdjustedSprite, HSMenuItem, NSString;

__attribute__((visibility("hidden")))
@interface Wheely : CCNode <CCRGBAProtocol, HSJustify, CCTargetedTouchDelegate> {
	BOOL animated;
	BOOL slow;
	BOOL big;
	BOOL showExhaust_;
	NSString* hub;
	NSString* engine;
	NSString* wheel;
	CCNode* hubNode;
	CCNode* engineNode;
	CCNode* wheelNode;
	HSAdjustedSprite* hubLock;
	HSAdjustedSprite* engineLock;
	HSAdjustedSprite* wheelLock;
	float wheelRotation;
	CCParticleBatchNode* exhaustBatch;
	HSParticleSystemQuad* Object310;
	HSParticleSystemQuad* Object59;
	HSParticleSystemQuad* Object269;
	NSMutableArray* Object372;
	float Object37[5];
	CGPoint Object155[5];
	int windBladeFakeSinus[5];
	float Object33;
	BOOL Object195[5];
	unsigned Object10;
	CGPoint nonadjustedPosition;
	CCMenu* cartMenu;
	BOOL Object230;
	BOOL Object255;
	BOOL touchDown;
	HSMenuItem* shoppingCart;
	unsigned speed_;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) unsigned speed;
@property(copy, nonatomic) NSString* wheel;
@property(copy, nonatomic) NSString* engine;
@property(copy, nonatomic) NSString* hub;
+(id)animatedWheelyWithHub:(id)hub engine:(id)engine wheel:(id)wheel big:(BOOL)big slow:(BOOL)slow exhaust:(BOOL)exhaust;
+(id)animatedWheelyWithHub:(id)hub engine:(id)engine wheel:(id)wheel big:(BOOL)big slow:(BOOL)slow;
+(id)wheelyWithHub:(id)hub engine:(id)engine wheel:(id)wheel animated:(BOOL)animated big:(BOOL)big;
-(void).cxx_destruct;
-(void)ccTouchEnded:(id)ended withEvent:(id)event;
-(BOOL)ccTouchBegan:(id)began withEvent:(id)event;
-(BOOL)containsTouchLocation:(id)location;
-(void)showProfile;
-(void)enableProfile;
-(void)onExit;
-(void)onEnter;
-(void)justifyRecursive;
-(void)justify;
-(void)setPosition:(CGPoint)position;
-(void)setOpacity:(unsigned char)opacity;
-(unsigned char)opacity;
-(ccColor3B)color;
-(void)setColor:(ccColor3B)color;
-(CGSize)contentSize;
-(void)maybeHideShoppingCart;
-(void)heroChangedOutfit;
-(void)listenForPlayerChanges;
-(void)showShoppingCart:(id)cart;
-(void)updateWind:(float)wind;
-(void)update:(float)update;
-(void)setWheelLocked;
-(void)setEngineLocked;
-(void)setHubLocked;
-(id)animate:(id)animate frames:(id)frames;
-(void)cleanup;
-(id)shoppingCart;
-(void)start;
-(void)stop;
-(id)initWithHub:(id)hub engine:(id)engine wheel:(id)wheel animated:(BOOL)animated big:(BOOL)big slow:(BOOL)slow exhaust:(BOOL)exhaust;
@end

