/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Boom-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class AFImageRequestOperation;

@interface XXUnknownSuperclass (CC)
+(id)colorWithColor4F:(ccColor4F)color4F;
+(id)colorWithColor4B:(ccColor4B)color4B;
+(id)colorWithColor3B:(ccColor3B)color3B;
@end

@interface XXUnknownSuperclass (LHMutableArrayExt)
-(void)reverse;
-(id)reversedArray;
-(void)moveObjectFromIndex:(unsigned)index toIndex:(unsigned)index2;
@end

@interface XXUnknownSuperclass (JSONKitDeserializing)
-(id)mutableObjectFromJSONStringWithParseOptions:(unsigned)parseOptions error:(id*)error;
-(id)mutableObjectFromJSONStringWithParseOptions:(unsigned)parseOptions;
-(id)mutableObjectFromJSONString;
-(id)objectFromJSONStringWithParseOptions:(unsigned)parseOptions error:(id*)error;
-(id)objectFromJSONStringWithParseOptions:(unsigned)parseOptions;
-(id)objectFromJSONString;
@end

@interface XXUnknownSuperclass (JSONKitDeserializing)
-(id)mutableObjectFromJSONDataWithParseOptions:(unsigned)parseOptions error:(id*)error;
-(id)mutableObjectFromJSONDataWithParseOptions:(unsigned)parseOptions;
-(id)mutableObjectFromJSONData;
-(id)objectFromJSONDataWithParseOptions:(unsigned)parseOptions error:(id*)error;
-(id)objectFromJSONDataWithParseOptions:(unsigned)parseOptions;
-(id)objectFromJSONData;
@end

@interface XXUnknownSuperclass (JSONKitSerializing)
-(id)JSONStringWithOptions:(unsigned)options includeQuotes:(BOOL)quotes error:(id*)error;
-(id)JSONString;
-(id)JSONDataWithOptions:(unsigned)options includeQuotes:(BOOL)quotes error:(id*)error;
-(id)JSONData;
@end

@interface XXUnknownSuperclass (JSONKitSerializing)
-(id)JSONStringWithOptions:(unsigned)options serializeUnsupportedClassesUsingDelegate:(id)delegate selector:(SEL)selector error:(id*)error;
-(id)JSONStringWithOptions:(unsigned)options error:(id*)error;
-(id)JSONString;
-(id)JSONDataWithOptions:(unsigned)options serializeUnsupportedClassesUsingDelegate:(id)delegate selector:(SEL)selector error:(id*)error;
-(id)JSONDataWithOptions:(unsigned)options error:(id*)error;
-(id)JSONData;
@end

@interface XXUnknownSuperclass (JSONKitSerializing)
-(id)JSONStringWithOptions:(unsigned)options serializeUnsupportedClassesUsingDelegate:(id)delegate selector:(SEL)selector error:(id*)error;
-(id)JSONStringWithOptions:(unsigned)options error:(id*)error;
-(id)JSONString;
-(id)JSONDataWithOptions:(unsigned)options serializeUnsupportedClassesUsingDelegate:(id)delegate selector:(SEL)selector error:(id*)error;
-(id)JSONDataWithOptions:(unsigned)options error:(id*)error;
-(id)JSONData;
@end

@interface XXUnknownSuperclass (JSONKitSerializingBlockAdditions)
-(id)JSONStringWithOptions:(unsigned)options serializeUnsupportedClassesUsingBlock:(id)block error:(id*)error;
-(id)JSONDataWithOptions:(unsigned)options serializeUnsupportedClassesUsingBlock:(id)block error:(id*)error;
@end

@interface XXUnknownSuperclass (JSONKitSerializingBlockAdditions)
-(id)JSONStringWithOptions:(unsigned)options serializeUnsupportedClassesUsingBlock:(id)block error:(id*)error;
-(id)JSONDataWithOptions:(unsigned)options serializeUnsupportedClassesUsingBlock:(id)block error:(id*)error;
@end

@interface XXUnknownSuperclass (sendBlockToBackground)
-(void)executeBlock2:(id)a2;
-(void)executeBlock:(id)block;
-(void)performBlock:(id)block withObject:(id)object waitUntilDone:(BOOL)done;
-(void)performBlock:(id)block waitUntilDone:(BOOL)done;
-(void)performBlock:(id)block;
@end

@interface XXUnknownSuperclass (UnicharExtensions)
+(id)stringWithUnichar:(unsigned short)unichar;
-(unsigned short)unicharFromFirstCharacter:(id)firstCharacter;
@end

@interface XXUnknownSuperclass (RRTransactionParsingAdditions)
-(id)rr_dictionaryFromJSONDataWithError:(out id*)error;
-(id)rr_dictionaryFromPlistDataWithError:(out id*)error;
@end

@interface XXUnknownSuperclass (stringWithTimeInterval)
+(id)stringWithTimeInterval:(double)timeInterval;
@end

@interface XXUnknownSuperclass (gzip)
-(id)gunzip;
-(id)gzip;
@end

@interface XXUnknownSuperclass (MD5)
+(id)MD5HexDigest:(id)digest;
+(id)MD5Digest:(id)digest;
-(id)MD5HexDigest;
-(id)MD5Digest;
@end

@interface XXUnknownSuperclass (BinaryPropertyListData)
+(id)dictionaryFromBinaryPropertyListData:(id)binaryPropertyListData;
-(id)binaryPropertyListData;
@end

@interface XXUnknownSuperclass (UTCString)
+(id)dateFromUTCString:(id)utcstring;
-(id)UTCString;
@end

@interface XXUnknownSuperclass (Base64)
+(id)dataFromBase64String:(id)base64String;
-(id)base64EncodedString;
@end

@interface XXUnknownSuperclass (BinaryPropertyListData)
+(id)arrayFromBinaryPropertyListData:(id)binaryPropertyListData;
-(id)binaryPropertyListData;
@end

@interface XXUnknownSuperclass (_AFNetworking)
@property(retain, nonatomic, setter=af_setImageRequestOperation:) AFImageRequestOperation* af_imageRequestOperation;
@end

@interface XXUnknownSuperclass (AFNetworking)
+(id)af_sharedImageCache;
+(id)af_sharedImageRequestOperationQueue;
-(void)cancelImageRequestOperation;
-(void)setImageWithURLRequest:(id)urlrequest placeholderImage:(id)image success:(id)success failure:(id)failure;
-(void)setImageWithURL:(id)url placeholderImage:(id)image;
-(void)setImageWithURL:(id)url;
-(void)af_setImageRequestOperation:(id)operation;
-(id)af_imageRequestOperation;
@end

@interface XXUnknownSuperclass (MutableDeepCopy)
-(id)mutableDeepCopy;
@end

@interface XXUnknownSuperclass (MutableDeepCopy)
-(id)mutableDeepCopy;
@end

@interface XXUnknownSuperclass (MD5)
-(id)md5DigestStringAtPath:(id)path;
-(id)hexadecimalString:(id)string;
-(id)md5DigestAtPath2:(id)path2;
-(id)md5DigestAtPath:(id)path;
@end

